// @vitest-environment jsdom
import {beforeEach,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({reply:vi.fn(),writes:vi.fn()}));
vi.mock('@/lib/authSession',()=>({getSessionUser:async()=>({id:'actor-a'})}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{auth:{getUser:async()=>({data:{user:{id:'actor-a'}},error:null})},from:(table:string)=>{let op='read';let payload:unknown;const b={select:()=>b,eq:()=>b,is:()=>b,order:()=>b,limit:()=>b,insert:(input:unknown)=>{op='insert';payload=input;m.writes(table,input);return b;},single:()=>m.reply(table,op,payload),maybeSingle:()=>m.reply(table,op,payload),then:(resolve:(v:unknown)=>unknown)=>Promise.resolve().then(()=>m.reply(table,op,payload)).then(resolve)};return b;}}}));
import {createThread,saveMessages,loadLatestThread,loadThreadMessages} from '../chatEngine';
const parent={id:'thread-a',user_id:'actor-a',organization_id:'org-a'};
beforeEach(()=>{vi.clearAllMocks();localStorage.clear();localStorage.setItem('ihomecrm.selectedOrganizationId','org-a');m.reply.mockImplementation(async(table:string,op:string)=>({data:table==='ai_chat_threads'&&op==='read'?parent:null,error:null}));});
it.each([null,{}, {id:'thread-a',title:'wrong',updated_at:'2026-09-30T00:00:00Z',user_id:'actor-a',organization_id:'org-a'}])('create thread missing/wrong receipt is unconfirmed %j',async data=>{m.reply.mockResolvedValue({data,error:null});await expect(createThread('Question','org-a')).rejects.toBeInstanceOf(Error);});
it('create transport/missing receipt survives repeat calls without another insert',async()=>{m.reply.mockResolvedValue({data:null,error:null});await expect(createThread('Question','org-a')).rejects.toBeInstanceOf(Error);await expect(createThread('Question','org-a')).rejects.toBeInstanceOf(Error);expect(m.writes).toHaveBeenCalledTimes(1);});
it.each([null,[],[{}],[{id:'message-a',...parent,thread_id:'thread-a',role:'user',content:'old',tool_calls:null,tool_call_id:null,model:'m'}]])('save exact message batch requires returned IDs and content %j',async data=>{m.reply.mockImplementation(async(table:string)=>({data:table==='ai_chat_threads'?parent:data,error:null}));await expect(saveMessages('thread-a',[{role:'user',content:'Question'}],'m','org-a')).rejects.toBeInstanceOf(Error);});
it('save unknown blocks reinsert across new calls',async()=>{await expect(saveMessages('thread-a',[{role:'user',content:'Question'}],'m','org-a')).rejects.toBeInstanceOf(Error);await expect(saveMessages('thread-a',[{role:'user',content:'Question'}],'m','org-a')).rejects.toBeInstanceOf(Error);expect(m.writes).toHaveBeenCalledTimes(1);});
it('actual exact batch can complete and keeps backend ID',async()=>{m.reply.mockImplementation(async(table:string,op:string,payload:unknown)=>({data:op==='read'?parent:(payload as object[]).map((row,index)=>({id:'message-'+index,...row})),error:null}));await expect(saveMessages('thread-a',[{role:'user',content:'Question'}],'m','org-a')).resolves.toBeUndefined();expect(m.writes).toHaveBeenCalledTimes(1);});
it.each([null,{},[{}]])('message list malformed cannot be an empty history %j',async data=>{m.reply.mockImplementation(async(table:string)=>({data:table==='ai_chat_threads'?parent:data,error:null}));await expect(loadThreadMessages('thread-a','org-a')).rejects.toBeInstanceOf(Error);});
it('latest thread malformed cannot become a valid thread',async()=>{m.reply.mockResolvedValue({data:{id:'thread-a'},error:null});await expect(loadLatestThread('org-a')).rejects.toBeInstanceOf(Error);});

it('JSONB tool receipt may reorder object keys without changing values',async()=>{m.reply.mockImplementation(async(_table:string,op:string,payload:unknown)=>({data:op==='read'?parent:(payload as Record<string,unknown>[]).map((row,index)=>({id:'message-'+index,...row,tool_calls:[{function:{arguments:'{}',name:'tra_phong'},type:'function',id:'call-a'}]})),error:null}));await expect(saveMessages('thread-a',[{role:'assistant',content:null,tool_calls:[{id:'call-a',type:'function',function:{name:'tra_phong',arguments:'{}'}}]}],'m','org-a')).resolves.toBeUndefined();});
