import type {OrganizationMember,MemberAuthorization,OrganizationRole,AuthorizationCatalog,OrganizationProfile} from '@/hooks/useOrganizationAuthorization';
type Row=Record<string,unknown>;
const fail=():never=>{throw new TypeError('Invalid authorization read payload');};
const object=(value:unknown):Row=>value&&typeof value==='object'&&!Array.isArray(value)?value as Row:fail();
const text=(value:unknown):boolean=>typeof value==='string'&&!!value;
const nullableText=(value:unknown):boolean=>value===null||typeof value==='string';
const bool=(value:unknown):boolean=>typeof value==='boolean';
const number=(value:unknown):boolean=>typeof value==='number'&&Number.isSafeInteger(value)&&value>=0;
const timestamp=(value:unknown):boolean=>typeof value==='string'&&Number.isFinite(Date.parse(value));
const strings=(value:unknown):boolean=>Array.isArray(value)&&value.every(text)&&new Set(value).size===value.length;
const oneOf=(value:unknown,values:readonly string[])=>typeof value==='string'&&values.includes(value);
const scopes=['ORGANIZATION','AREA','BUILDING','CASHBOOK'];
const core=(r:Row)=>text(r.membershipId)&&text(r.userId)&&nullableText(r.email)&&nullableText(r.fullName)&&oneOf(r.memberType,['OWNER','STAFF','SHAREHOLDER','PARTNER','SERVICE'])&&oneOf(r.status,['INVITED','ACTIVE','SUSPENDED','REVOKED'])&&number(r.version)&&bool(r.isSelf);
const array=(value:unknown,valid:(r:Row)=>boolean)=>Array.isArray(value)&&value.every(item=>valid(object(item)));
function checked<T>(value:unknown,valid:(r:Row)=>boolean):T{if(!valid(object(value)))return fail();return value as T;}
function list<T>(value:unknown,valid:(r:Row)=>boolean,id:string):T[]{if(!array(value,valid))return fail();const rows=value as Row[];if(new Set(rows.map(row=>row[id])).size!==rows.length)return fail();return value as T[];}
const scopeRef=(r:Row)=>text(r.scopeId)&&oneOf(r.scopeType,scopes)&&typeof r.label==='string';
export function readOrganizationMembers(value:unknown):{organizationId:string;members:OrganizationMember[]}{const r=object(value);if(!text(r.organizationId))return fail();return {organizationId:r.organizationId as string,members:list<OrganizationMember>(r.members,m=>core(m)&&number(m.overrideAllow)&&number(m.overrideDeny)&&number(m.cashbooksHeld)&&number(m.permissionCount)&&array(m.roles,role=>text(role.bindingId)&&text(role.roleId)&&text(role.roleName)&&bool(role.isSystem)&&array(role.scopes,scopeRef)),'membershipId')};}
export function readMemberAuthorization(value:unknown,membershipId:string):MemberAuthorization{return checked(value,r=>core(r)&&r.membershipId===membershipId&&array(r.roleBindings,role=>text(role.bindingId)&&text(role.roleId)&&text(role.roleName)&&strings(role.scopeIds))&&array(r.overrides,item=>text(item.overrideId)&&text(item.permissionKey)&&oneOf(item.effect,['ALLOW','DENY'])&&oneOf(item.scopeMode,['ORGANIZATION','SCOPED'])&&nullableText(item.reason)&&(item.expiresAt===null||timestamp(item.expiresAt))&&timestamp(item.createdAt)&&strings(item.scopeIds))&&array(r.cashbooksHeld,item=>text(item.cashbookId)&&nullableText(item.name)&&text(item.kind))&&strings(r.effectiveKeys));}
export function readOrganizationRoles(value:unknown):OrganizationRole[]{return list(value,r=>text(r.roleId)&&text(r.name)&&bool(r.isSystem)&&text(r.status)&&number(r.version)&&number(r.memberCount)&&strings(r.allowKeys)&&strings(r.denyKeys),'roleId');}
export function readAuthorizationCatalog(value:unknown):AuthorizationCatalog{return checked(value,r=>array(r.scopes,scope=>scopeRef(scope)&&nullableText(scope.buildingId)&&nullableText(scope.areaId)&&nullableText(scope.cashbookId))&&array(r.permissions,permission=>text(permission.key)&&text(permission.resource)&&text(permission.action)&&nullableText(permission.sensitivity)&&Array.isArray(permission.scopeKinds)&&permission.scopeKinds.every(kind=>oneOf(kind,scopes))&&strings(permission.requiredDimensions)&&bool(permission.requiresCashbookPossession)));}
export function readOrganizationProfile(value:unknown):OrganizationProfile{return checked(value,r=>{const counts=object(r.counts);return text(r.organizationId)&&text(r.name)&&text(r.slug)&&text(r.status)&&bool(r.isDemo)&&timestamp(r.createdAt)&&number(r.authorizationVersion)&&bool(r.canEdit)&&['members','owners','roles','buildings','areas','cashbooks','pendingInvitations','activeOverrides'].every(key=>number(counts[key]))&&array(r.invitations,item=>text(item.invitationId)&&text(item.email)&&oneOf(item.memberType,['OWNER','STAFF','SHAREHOLDER','PARTNER','SERVICE'])&&oneOf(item.status,['PENDING','ACCEPTED','EXPIRED','REVOKED'])&&timestamp(item.expiresAt)&&timestamp(item.createdAt)&&nullableText(item.roleName)&&bool(item.isExpired))&&array(r.auditTrail,item=>text(item.eventId)&&timestamp(item.occurredAt)&&text(item.eventType)&&['resourceType','resourceId','reason','actorEmail','actorName'].every(key=>nullableText(item[key]))&&(item.newState===null||!!object(item.newState)));});}
