import type {ProfitClosePreview,ProfitClosePreviewRow,ProfitCloseSnapshot,ProfitCloseState,ProfitCloseStateRow,ProfitMonthly,ProfitAllocation,ProfitManagerAllocation,ShareholderDistribution,ManagerSalaryPayout,MonthlyBuildingProfit,ProfitCloseOrganizationScope} from '@/hooks/useShareholderProfit';
import type {ProfitUnallocatedDisposition,TotalGroupPeerMap} from './profitClose';
type Row=Record<string,unknown>;
const invalid=():never=>{throw new TypeError('Invalid profit read payload');};
export const profitObject=(value:unknown):Row=>value&&typeof value==='object'&&!Array.isArray(value)?value as Row:invalid();
export const profitString=(value:unknown):string=>typeof value==='string'&&!!value?value:invalid();
const nullableString=(value:unknown):string|null=>value===null?null:typeof value==='string'?value:invalid();
const bool=(value:unknown):boolean=>typeof value==='boolean'?value:invalid();
export const profitNumber=(value:unknown):number=>{
 if(typeof value!=='number'&&(typeof value!=='string'||!/^[-+]?\d+(?:\.\d+)?$/.test(value)))return invalid();
 const parsed=Number(value);return Number.isFinite(parsed)?parsed:invalid();
};
const count=(value:unknown):number=>{const result=profitNumber(value);return Number.isSafeInteger(result)&&result>=0?result:invalid();};
const date=(value:unknown,month=false):string=>{const result=profitString(value);const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(result);if(!match)return invalid();const d=new Date(Date.UTC(Number(match[1]),Number(match[2])-1,Number(match[3])));return d.getUTCMonth()===Number(match[2])-1&&d.getUTCDate()===Number(match[3])&&(!month||Number(match[3])===1)?result:invalid();};
const nullableDate=(value:unknown):string|null=>value===null?null:typeof value==='string'&&Number.isFinite(Date.parse(value))?value:invalid();
const hash=(value:unknown):string=>typeof value==='string'&&/^[a-f0-9]{32}$/i.test(value)?value:invalid();
const status=(value:unknown):'DRAFT'|'LOCKED'=>value==='DRAFT'||value==='LOCKED'?value:invalid();
const disposition=(value:unknown):ProfitUnallocatedDisposition|null=>{if(value===null)return null;if(value==='RETAINED_EARNINGS'||value==='CARRY_FORWARD')return value;return invalid();};
export function profitRows<T>(value:unknown,map:(row:Row)=>T):T[]{if(!Array.isArray(value))return invalid();return value.map(item=>map(profitObject(item)));}
const unique=<T,>(rows:T[],get:(row:T)=>string):T[]=>{if(new Set(rows.map(get)).size!==rows.length)return invalid();return rows;};
export function readProfitMonthly(value:unknown):ProfitMonthly[]{return unique(profitRows(value,r=>({...r,id:profitString(r.id),user_id:profitString(r.user_id),building_id:profitString(r.building_id),period_month:date(r.period_month,true),computed_profit:profitNumber(r.computed_profit),adjusted_profit:profitNumber(r.adjusted_profit),management_salary:profitNumber(r.management_salary),shareholder_percent_total:profitNumber(r.shareholder_percent_total),shareholder_allocated_amount:profitNumber(r.shareholder_allocated_amount),unallocated_profit:profitNumber(r.unallocated_profit),unallocated_disposition:disposition(r.unallocated_disposition),unallocated_disposition_reason:nullableString(r.unallocated_disposition_reason),status:status(r.status),note:nullableString(r.note),locked_at:nullableDate(r.locked_at),locked_by:nullableString(r.locked_by)})),r=>r.id);}
export function readProfitAllocations(value:unknown):ProfitAllocation[]{return unique(profitRows(value,r=>{const pm=profitObject(r.pm);status(pm.status);return {id:profitString(r.id),user_id:profitString(r.user_id),profit_monthly_id:profitString(r.profit_monthly_id),shareholder_id:profitString(r.shareholder_id),percent:profitNumber(r.percent),amount:profitNumber(r.amount),period_month:date(pm.period_month,true),building_id:profitString(pm.building_id)};}),r=>r.id);}
export function readManagerAllocations(value:unknown):ProfitManagerAllocation[]{return unique(profitRows(value,r=>{const pm=profitObject(r.pm);status(pm.status);return {id:profitString(r.id),user_id:profitString(r.user_id),profit_monthly_id:profitString(r.profit_monthly_id),manager_id:profitString(r.manager_id),amount:profitNumber(r.amount),period_month:date(pm.period_month,true),building_id:profitString(pm.building_id)};}),r=>r.id);}
function payout(value:unknown,manager:boolean){return unique(profitRows(value,r=>({id:profitString(r.id),subject:profitString(manager?r.profit_manager_id:r.shareholder_id),total_amount:profitNumber(r.total_amount),voucher_date:date(r.voucher_date),name:profitString(r.name),account_id:nullableString(r.account_id),building_id:profitString(r.building_id)})),r=>r.id);}
export function readShareholderDistributions(value:unknown):ShareholderDistribution[]{return payout(value,false).map(({subject,...row})=>({...row,shareholder_id:subject}));}
export function readManagerPayouts(value:unknown):ManagerSalaryPayout[]{return payout(value,true).map(({subject,...row})=>({...row,manager_id:subject}));}
export function readAccrualByBuilding(value:unknown):MonthlyBuildingProfit[]{const result=new Map<string,MonthlyBuildingProfit>();for(const r of profitRows(value,item=>{const row={building_id:profitString(item.building_id),building_name:profitString(item.building_name),is_virtual:bool(item.is_virtual),revenue:profitNumber(item.revenue),expense:profitNumber(item.expense),net:profitNumber(item.net)};return row;})){if(r.is_virtual)continue;const current=result.get(r.building_id)??{building_id:r.building_id,building_name:r.building_name,total_income:0,total_expense:0,net_profit:0};current.total_income=profitNumber(current.total_income+r.revenue);current.total_expense=profitNumber(current.total_expense+r.expense);current.net_profit=profitNumber(current.net_profit+r.net);result.set(r.building_id,current);}return [...result.values()];}
export function readProfitScopes(value:unknown):ProfitCloseOrganizationScope[]{return unique(profitRows(profitObject(value).organizations,r=>({organization_id:profitString(r.organization_id),organization_name:profitString(r.organization_name),organization_slug:profitString(r.organization_slug),can_lock:bool(r.can_lock),can_unlock:bool(r.can_unlock)})),r=>r.organization_id);}
export function readProfitPeers(value:unknown):TotalGroupPeerMap{const result:TotalGroupPeerMap={};for(const [id,entryValue] of Object.entries(profitObject(value))){profitString(id);const r=profitObject(entryValue);if(!Array.isArray(r.peer_ids))return invalid();const ids=r.peer_ids.map(profitString);if(new Set(ids).size!==ids.length)return invalid();result[id]={peerIds:ids,peerNames:profitString(r.peer_names),ruleLabels:profitString(r.rule_labels)};}return result;}
function snapshot(value:unknown):ProfitCloseSnapshot|null{if(value===null)return null;const r=profitObject(value);const adjusted=profitNumber(r.adjusted_profit),salary=profitNumber(r.management_salary);return {id:profitString(r.id),status:status(r.status),computed_profit:profitNumber(r.computed_profit),adjustment_amount:profitNumber(r.adjustment_amount),adjustment_reason:nullableString(r.adjustment_reason),adjusted_profit:adjusted,management_salary:salary,distributable_profit:r.distributable_profit===undefined?profitNumber(adjusted-salary):profitNumber(r.distributable_profit),shareholder_percent_total:profitNumber(r.shareholder_percent_total),shareholder_allocated_amount:profitNumber(r.shareholder_allocated_amount),unallocated_profit:profitNumber(r.unallocated_profit),unallocated_disposition:disposition(r.unallocated_disposition),unallocated_disposition_reason:nullableString(r.unallocated_disposition_reason),source_hash:hash(r.source_hash),locked_at:nullableDate(r.locked_at)};}
export function readProfitState(value:unknown,organizationId:string,periodMonth:string):ProfitCloseState{
 const r=profitObject(value);if(r.organization_id!==organizationId||r.period_month!==periodMonth)return invalid();
 const rows=unique(profitRows(r.rows,row=>({id:profitString(row.id),building_id:profitString(row.building_id),building_name:profitString(row.building_name),is_virtual:bool(row.is_virtual),building_deleted:bool(row.building_deleted),status:status(row.status),computed_profit:profitNumber(row.computed_profit),adjusted_profit:profitNumber(row.adjusted_profit),adjustment_amount:profitNumber(row.adjustment_amount),adjustment_reason:nullableString(row.adjustment_reason),management_salary:profitNumber(row.management_salary),distributable_profit:profitNumber(row.distributable_profit),shareholder_percent_total:profitNumber(row.shareholder_percent_total),shareholder_allocated_amount:profitNumber(row.shareholder_allocated_amount),unallocated_profit:profitNumber(row.unallocated_profit),unallocated_disposition:disposition(row.unallocated_disposition),unallocated_disposition_reason:nullableString(row.unallocated_disposition_reason),source_revenue:profitNumber(row.source_revenue),source_expense:profitNumber(row.source_expense),source_hash:hash(row.source_hash),is_stale:bool(row.is_stale),stale_reason:nullableString(row.stale_reason),revision_number:count(row.revision_number),locked_at:nullableDate(row.locked_at)})),row=>row.id);
 if(!Array.isArray(r.snapshot_ids))return invalid();const ids=r.snapshot_ids.map(profitString).sort();const rowIds=rows.map(row=>row.id).sort();const snapshotCount=count(r.snapshot_count),locked=count(r.locked_count),draft=count(r.draft_count);
 if(JSON.stringify(ids)!==JSON.stringify(rowIds)||snapshotCount!==rows.length||locked!==rows.filter(row=>row.status==='LOCKED').length||draft!==rows.filter(row=>row.status==='DRAFT').length)return invalid();
 return {organization_id:organizationId,period_month:date(periodMonth,true),can_lock:bool(r.can_lock),can_unlock:bool(r.can_unlock),state_hash:hash(r.state_hash),snapshot_ids:ids,snapshot_count:snapshotCount,locked_count:locked,draft_count:draft,real_building_count:count(r.real_building_count),active_real_snapshot_count:count(r.active_real_snapshot_count),has_out_of_scope_snapshots:bool(r.has_out_of_scope_snapshots),rows};
}
export function readProfitPreview(value:unknown,organizationId:string,periodMonth:string):ProfitClosePreview{
 const root=profitObject(value);if(root.organization_id!==organizationId||root.period_month!==periodMonth)return invalid();const rootHash=hash(root.source_hash);
 const rows=unique(profitRows(root.buildings,row=>{
  const current=snapshot(row.current_snapshot);const computed=profitNumber(row.computed_profit);const currentStale=bool(row.current_is_stale);
  if((current?status(row.current_status):row.current_status)!==(current?.status??null))return invalid();
  return {building_id:profitString(row.building_id),building_name:profitString(row.building_name),revenue:profitNumber(row.source_revenue),expense:profitNumber(row.source_expense),computed_profit:computed,adjustment_amount:profitNumber(row.adjustment_amount),management_salary:profitNumber(row.management_salary),distributable_profit:profitNumber(row.distributable_profit),shareholder_percent_total:profitNumber(row.shareholder_percent_total),shareholder_allocated_amount:profitNumber(row.shareholder_allocated_amount),unallocated_profit:profitNumber(row.unallocated_profit),unallocated_disposition:disposition(row.unallocated_disposition),unallocated_disposition_reason:nullableString(row.unallocated_disposition_reason),source_hash:hash(row.building_source_hash),is_stale:!!current&&currentStale,stale_reason:nullableString(row.current_stale_reason),delta_profit:row.delta_profit===undefined?profitNumber(current?computed-current.computed_profit:0):profitNumber(row.delta_profit),shareholder_allocations:unique(profitRows(row.shareholder_allocations,a=>({shareholder_id:profitString(a.shareholder_id),shareholder_name:profitString(a.shareholder_name),percent:profitNumber(a.percent),amount:profitNumber(a.amount)})),a=>a.shareholder_id),manager_allocations:unique(profitRows(row.manager_allocations,a=>({manager_id:profitString(a.manager_id),manager_name:profitString(a.manager_name),amount:profitNumber(a.amount)})),a=>a.manager_id),current_snapshot:current};
 }),row=>row.building_id);
 return {organization_id:organizationId,period_month:date(periodMonth,true),source_hash:rootHash,is_locked:root.is_locked===undefined?rows.some(row=>row.current_snapshot?.status==='LOCKED'):bool(root.is_locked),is_stale:root.is_stale===undefined?rows.some(row=>row.is_stale):bool(root.is_stale),rows};
}
