/** Only static labels, never IDs or arbitrary queryKey values, enter UI. */
const LABELS: Record<string, string> = {
  "acceptance-geofence-config": "phạm vi vị trí nghiệm thu",
  "address": "địa chỉ hành chính",
  "admin-users": "danh sách tài khoản",
  "ai-copilot-entitlement": "quyền sử dụng Copilot",
  "ai-copilot-entitlements-admin": "phân quyền Copilot",
  "ai-copilot-settings": "cài đặt Copilot",
  "ai-providers": "nhà cung cấp Copilot",
  "ai-providers-admin": "cấu hình nhà cung cấp Copilot",
  "ai-providers-gia": "giá sử dụng Copilot",
  "ai-usage-7d": "mức sử dụng Copilot trong 7 ngày",
  "ai-usage-token-hom-nay": "mức sử dụng Copilot hôm nay",
  "asset-categories": "danh mục tài sản",
  "asset-handovers": "biên bản bàn giao tài sản",
  "asset-maintenance": "phiếu bảo trì tài sản",
  "asset-movements": "lịch sử di chuyển tài sản",
  "asset_warehouses": "danh sách kho",
  "auth": "phiên đăng nhập",
  "auto_debt_config": "cấu hình gạch nợ",
  "building-organization": "tổ chức quản lý tòa nhà",
  "building-services": "dịch vụ của tòa nhà",
  "building-shareholders": "cổ đông của tòa nhà",
  "can-reverse-collection": "điều kiện hoàn tác khoản thu",
  "cash-book-summary": "tổng hợp sổ quỹ",
  "cash-flow-by-day": "dòng tiền theo ngày",
  "cash-handovers": "đề nghị bàn giao tiền",
  "cashbooks-for-expense-v2": "sổ quỹ được phép chi",
  "change-breakdown": "chi tiết tiền thối",
  "collection-cycle": "kỳ bàn giao tiền",
  "commission-manager-options": "người quản lý được nhận thưởng",
  "commission-prefill": "dữ liệu lập phiếu hoa hồng",
  "commission-voucher-facts": "thông tin phiếu hoa hồng",
  "compute-previous-debt": "công nợ kỳ trước",
  "contract-deposit-vouchers": "phiếu cọc của hợp đồng",
  "contract-discount-slot": "giảm trừ của hợp đồng",
  "contract-draft-signing": "thông tin ký hợp đồng nháp",
  "contract-drafts": "hợp đồng nháp",
  "contract-exit-case": "hồ sơ kết thúc hợp đồng",
  "contract-exit-cases": "danh sách hồ sơ kết thúc hợp đồng",
  "contract-history": "lịch sử hợp đồng",
  "contract-meter-boundaries": "chỉ số công tơ đầu và cuối hợp đồng",
  "contract-meter-followups": "công tơ cần bổ sung chỉ số",
  "contract-meter-interval": "khoảng chỉ số công tơ của hợp đồng",
  "contract-pending-forfeit": "đề nghị xử lý cọc của hợp đồng",
  "contract-settlement": "quyết toán hợp đồng",
  "contract-termination-info": "thông tin thanh lý hợp đồng",
  "contract-transfer-links": "liên kết chuyển nhượng hợp đồng",
  "contract-vehicles": "phương tiện trong hợp đồng",
  "ct01-declarations": "tờ khai CT01",
  "ct01-tenancies": "thông tin cư trú để lập CT01",
  "customer-contracts": "hợp đồng của khách hàng",
  "customer-stats": "thống kê khách hàng",
  "debt-chart": "biểu đồ công nợ",
  "departments": "danh sách bộ phận",
  "deposit-breakdown": "chi tiết tiền cọc",
  "deposit-dashboard": "tổng hợp tiền cọc",
  "document-template": "mẫu tài liệu",
  "document-templates": "danh sách mẫu tài liệu",
  "excess-amount": "tiền dư của hợp đồng",
  "existing-commission-vouchers": "phiếu hoa hồng đã lập",
  "fee-accounts": "sổ quỹ thanh toán phí",
  "fee-config-matrix": "cấu hình phí theo tòa nhà",
  "finance-v2-routes": "cấu hình ghi sổ thu chi",
  "first-invoice-details": "chi tiết hóa đơn đầu tiên",
  "flex-cancel-eligibility": "điều kiện hủy phiếu",
  "ie-form-rooms": "phòng được chọn cho phiếu thu chi",
  "ie-history": "lịch sử phiếu thu chi",
  "ie-related-invoice": "hóa đơn liên quan đến phiếu",
  "ie-types-hidden-in-report": "loại thu chi được loại khỏi báo cáo",
  "income-cancel-eligibility": "điều kiện hủy phiếu thu",
  "invoice": "hóa đơn",
  "invoice-collectors": "người thu tiền hóa đơn",
  "invoice-exists": "hóa đơn đã có trong kỳ",
  "invoice-history": "lịch sử hóa đơn",
  "invoice-payments-summary": "các khoản thanh toán của hóa đơn",
  "invoice-rent-periods": "kỳ tính tiền thuê của hóa đơn",
  "invoice-rounding-report": "báo cáo tiền làm tròn hóa đơn",
  "invoice-totals-by-ids": "số tiền của các hóa đơn",
  "invoice-vouchers": "phiếu thu chi của hóa đơn",
  "job_groups": "nhóm công việc",
  "job_types": "loại công việc",
  "lead-activities": "hoạt động của khách hẹn",
  "manager-salaries": "lương quản lý",
  "materials": "danh sách vật tư",
  "meter-reading-stats": "thống kê chỉ số công tơ",
  "meter_readings": "chỉ số công tơ",
  "monthly-building-profit": "lợi nhuận tháng của tòa nhà",
  "my-assignments": "các tòa nhà được phân công",
  "my-available-rooms": "phòng đang có thể cho thuê",
  "my-cashbook-access-v2": "quyền sử dụng sổ quỹ",
  "my-context": "thông tin tài khoản đang đăng nhập",
  "my-org-ids": "tổ chức của bạn",
  "my-org-names": "tên các tổ chức của bạn",
  "my-organizations": "danh sách tổ chức của bạn",
  "my-permissions": "quyền truy cập của bạn",
  "my-profit-manager": "thông tin quản lý lợi nhuận của bạn",
  "my-share-buildings": "các tòa nhà bạn có cổ phần",
  "my-shareholder": "thông tin cổ đông của bạn",
  "orphan-deposit-vouchers": "phiếu cọc chưa được liên kết",
  "pass-listing-room-customers": "khách hàng của phòng chuyển nhượng",
  "pending-approvals": "phiếu chờ duyệt",
  "pending-terminations": "hợp đồng chờ thanh lý",
  "phong-trong": "danh sách phòng trống",
  "profiles": "hồ sơ người dùng",
  "profiles-brief": "thông tin người dùng",
  "profiles-for-salary": "nhân viên được cấu hình lương",
  "public-contract-invoice": "hóa đơn được chia sẻ",
  "receiving-cashbook-settings": "cấu hình sổ nhận tiền",
  "receiving-cashbooks": "sổ nhận tiền",
  "recent-activities": "hoạt động gần đây",
  "refund-log": "lịch sử hoàn tiền",
  "renewed-contract-ids": "hợp đồng đã gia hạn",
  "reports": "báo cáo",
  "room-active-contract": "hợp đồng đang hiệu lực của phòng",
  "room-cash-lifecycle": "thu chi trong quá trình cho thuê phòng",
  "room-ids-by-code": "phòng theo mã đã nhập",
  "room-latest-invoice": "hóa đơn gần nhất của phòng",
  "room-price-history": "lịch sử giá phòng",
  "room-reservations": "đặt cọc giữ phòng",
  "room-turnover": "thông tin bàn giao phòng",
  "sale-bonus-status": "trạng thái phiếu thưởng Sale",
  "service_quotas": "định mức dịch vụ",
  "settlement-report": "báo cáo quyết toán",
  "shareholders": "danh sách cổ đông",
  "signed-url": "liên kết xem tệp",
  "special-fee-preview": "bản xem trước các phiếu phí",
  "special-fee-prices": "giá phí định kỳ",
  "spend-engine": "quy tắc duyệt chi",
  "staff_users": "danh sách nhân viên",
  "subscription_plans": "gói cước",
  "suppliers": "nhà cung cấp",
  "tt-deposit-ledger": "sổ tiền cọc",
  "unpaid-invoices": "hóa đơn chưa thu đủ",
  "unrecorded-meters": "công tơ chưa ghi chỉ số",
  "user_subscriptions": "gói cước đã đăng ký",
  "v5-building-coords": "vị trí tòa nhà",
  "v5-config-admin": "cấu hình lương và chấm công",
  "v5-coverage-all": "kết quả kiểm tra đủ ngày công",
  "v5-cron-runs": "lịch sử tác vụ lương và chấm công",
  "v5-flagged": "ngày công cần kiểm tra",
  "v5-insp-photos": "ảnh kiểm tra tòa nhà",
  "v5-inspection-log": "lịch sử kiểm tra tòa nhà",
  "v5-lock-assert": "điều kiện chốt bảng lương",
  "v5-my-day-summary": "trạng thái ngày làm việc",
  "v5-my-missions": "nhiệm vụ trong ngày",
  "v5-open-inspections": "phiên kiểm tra tòa nhà đang mở",
  "v5-pending-leaves": "đơn nghỉ đang chờ duyệt",
  "v5-shadow": "kết quả đối chiếu bảng lương",
  "voucher-cancellation": "thông tin hủy phiếu",
  "voucher-change-log": "lịch sử thay đổi phiếu",
  "voucher-slot-warning": "điều kiện tính khoản thu chi",
  "voucher-with-batch": "phiếu và đợt phiếu liên quan",

  "areas": "danh sách khu vực",
  "floors": "danh sách tầng",
  "buildings": "danh sách tòa nhà",
  "rooms": "danh sách phòng",
  "customers": "danh sách khách hàng",
  "tenants": "danh sách khách thuê",
  "vehicles": "danh sách phương tiện",
  "leads": "danh sách khách hẹn",
  "contracts": "danh sách hợp đồng",
  "contract-stats": "thống kê hợp đồng",
  "contract-customers": "khách hàng của hợp đồng",
  "contract-services": "dịch vụ của hợp đồng",
  "income-expense-items": "hạng mục của phiếu",
  "income-expense-batches": "đợt phiếu thu chi",
  "income-expenses": "danh sách phiếu thu chi",
  "income-expense": "phiếu thu chi",
  "invoices": "danh sách hóa đơn",
  "invoice-statistics": "thống kê hóa đơn",
  "payments": "các khoản thanh toán",
  "deposits": "danh sách phiếu cọc",
  "reservation": "tiền cọc giữ chỗ",
  "accounts": "danh sách sổ quỹ",
  "accounts-with-balance": "số dư sổ quỹ",
  "cashbook": "sổ quỹ",
  "approval": "yêu cầu duyệt",
  "services": "danh sách dịch vụ",
  "meters": "danh sách công tơ",
  "meter-readings": "chỉ số công tơ",
  "assets": "danh sách tài sản",
  "material": "vật tư",
  "warehouses": "danh sách kho",
  "jobs": "danh sách công việc",
  "tasks": "danh sách công việc",
  "notifications": "thông báo",
  "notification-settings": "tùy chọn thông báo",
  "manager-salary": "bảng lương",
  "salary": "dữ liệu lương",
  "my-manager-config": "cấu hình lương cá nhân",
  "profit": "lợi nhuận",
  "shareholder": "cổ đông",
  "personal-transactions": "các khoản thu chi cá nhân",
  "settings": "cài đặt",
  "profile": "thông tin cá nhân",
  "organization": "tổ chức",
  "roles": "vai trò",
  "members": "thành viên",
  "users": "tài khoản",
  "subscriptions": "gói cước",
  "templates": "mẫu tài liệu",
  "dashboard": "số liệu bảng tin",
  "revenue": "doanh thu",
  "occupancy": "tỷ lệ lấp đầy",
  "activities": "hoạt động gần đây",
  "hotlines": "danh sách hotline",
  "reconciliation": "đối soát",
  "handover": "bàn giao",
  "utility": "điện nước",
  "period": "phí định kỳ",
  "zalo": "hội thoại Zalo",
  "network": "thiết bị mạng",
  "copilot": "dữ liệu Copilot",
  "lucky": "sự kiện quay số",
  "residence": "hồ sơ cư trú",
  "my-day": "ngày làm việc",
  "report": "báo cáo"
};
export function queryLabel(queryKey: unknown, explicitLabel?: unknown): string {
  if (typeof explicitLabel === 'string' && explicitLabel.trim()) return explicitLabel;
  const key = Array.isArray(queryKey) && typeof queryKey[0] === 'string' ? queryKey[0] : '';
  if (LABELS[key]) return LABELS[key];
  const prefix = Object.keys(LABELS).sort((a,b) => b.length-a.length).find(name => key.startsWith(name + '-') || key.startsWith(name + ':'));
  // prefix came from Object.keys(LABELS), so the matching label exists.
  return prefix ? LABELS[prefix]! : 'dữ liệu của mục đang mở';
}
