import {z} from 'zod';
import type {Json} from '@/integrations/supabase/types';
const uuid=z.string().uuid(),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/),key=z.string().trim().regex(/^[A-Za-z0-9][A-Za-z0-9._:-]{7,199}$/);
const receiptSchema=z.object({amount:z.number().int().positive().max(Number.MAX_SAFE_INTEGER),accountId:uuid.nullable().optional(),voucherDate:date,name:z.string().trim().min(1).optional(),description:z.string().nullable().optional(),attachments:z.array(z.string().url().startsWith('https://')).optional()}).strict();
export type ReservationReceiptInput=z.infer<typeof receiptSchema>;
export interface CreateRoomReservationInput {roomId:string;customerId:string;holdUntil?:string|null;intendedMoveInOn?:string|null;topupDueOn?:string|null;depositTarget?:number|null;notes?:string|null;receipt?:ReservationReceiptInput;existingVoucherIds?:string[];idempotencyKey:string}
export interface UpdateRoomReservationInput {reservationId:string;expectedRevision:number;idempotencyKey:string;action:'UPDATE'|'TOPUP'|'CANCEL';changes?:{holdUntil?:string|null;intendedMoveInOn?:string|null;topupDueOn?:string|null;depositTarget?:number|null;notes?:string|null};receipt?:ReservationReceiptInput}
export interface RoomReservationFilters {roomId?:string;customerId?:string;status?:'HOLD'|'CONVERTED'|'CANCELLED';limit?:number}
const receiptResultSchema=z.object({source_voucher_id:uuid,source_item_id:uuid,amount:z.number().nonnegative(),received:z.boolean(),approval_status:z.string().nullable(),code:z.string().nullable(),released:z.boolean()});
export const roomReservationSchema=z.object({id:uuid,organization_id:uuid,building_id:uuid,room_id:uuid,customer_id:uuid,customer_name:z.string(),customer_phone:z.string(),building_name:z.string(),room_name:z.string(),status:z.enum(['HOLD','CONVERTED','CANCELLED']),claim_status:z.enum(['LIVE','CONSUMED','CANCELLED']),revision:z.number().int().positive(),hold_until:date.nullable(),intended_move_in_on:date.nullable(),topup_due_on:date.nullable(),deposit_target:z.number().nonnegative().nullable(),notes:z.string().nullable(),converted_contract_id:uuid.nullable(),overdue:z.boolean(),received_amount:z.number().nonnegative(),source_voucher_ids:z.array(uuid),receipts:z.array(receiptResultSchema),created_at:z.string(),updated_at:z.string(),history:z.array(z.object({revision:z.number().int().positive(),action:z.string(),changed_by:uuid,changed_at:z.string()}))});
export type RoomReservation=z.infer<typeof roomReservationSchema>;
export const roomReservationListSchema=z.object({server_today:date,reservations:z.array(roomReservationSchema)});
export type RoomReservationList=z.infer<typeof roomReservationListSchema>;
export type ReservationRpcName='create_room_reservation_v1'|'update_room_reservation_v1'|'list_room_reservations_v1';
export type ReservationRpcInvoker=(name:ReservationRpcName,args:Record<string,Json>)=>PromiseLike<{data:unknown;error:{code?:string;message?:string}|null}>;
export function buildReservationReceiptPayload(input:ReservationReceiptInput):Json {const r=receiptSchema.parse(input);return{amount:r.amount,account_id:r.accountId??null,voucher_date:r.voucherDate,name:r.name??null,description:r.description??null,attachments:r.attachments??[]};}
export function buildCreateRoomReservationArgs(organizationId:string,input:CreateRoomReservationInput){
  const v=z.object({roomId:uuid,customerId:uuid,holdUntil:date.nullable().optional(),intendedMoveInOn:date.nullable().optional(),topupDueOn:date.nullable().optional(),depositTarget:z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER).nullable().optional(),notes:z.string().nullable().optional(),receipt:receiptSchema.optional(),existingVoucherIds:z.array(uuid).optional(),idempotencyKey:key}).strict().parse(input);
  if(!v.receipt&&!v.existingVoucherIds?.length&&!v.holdUntil)throw new Error('Giữ chỗ chưa nhận tiền phải chọn hạn giữ chỗ');
  const p_payload:Record<string,Json>={room_id:v.roomId,customer_id:v.customerId,hold_until:v.holdUntil??null,intended_move_in_on:v.intendedMoveInOn??null,topup_due_on:v.topupDueOn??null,deposit_target:v.depositTarget??null,notes:v.notes??null,existing_voucher_ids:v.existingVoucherIds??[]};if(v.receipt)p_payload.receipt=buildReservationReceiptPayload(v.receipt);
  return{p_organization_id:uuid.parse(organizationId),p_idempotency_key:v.idempotencyKey,p_payload};
}
export function buildUpdateRoomReservationArgs(organizationId:string,input:UpdateRoomReservationInput){
  const v=z.object({reservationId:uuid,expectedRevision:z.number().int().positive(),idempotencyKey:key,action:z.enum(['UPDATE','TOPUP','CANCEL']),changes:z.object({holdUntil:date.nullable().optional(),intendedMoveInOn:date.nullable().optional(),topupDueOn:date.nullable().optional(),depositTarget:z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER).nullable().optional(),notes:z.string().nullable().optional()}).strict().optional(),receipt:receiptSchema.optional()}).strict().parse(input);
  if((v.action==='TOPUP')!==!!v.receipt||(v.action!=='UPDATE'&&v.changes&&Object.keys(v.changes).length))throw new Error('Thao tác giữ chỗ không khớp dữ liệu');
  const changes:Record<string,Json>={};for(const [k,value]of Object.entries(v.changes??{})){const names:Record<string,string>={holdUntil:'hold_until',intendedMoveInOn:'intended_move_in_on',topupDueOn:'topup_due_on',depositTarget:'deposit_target',notes:'notes'};changes[names[k]]=value??null;}
  return{p_organization_id:uuid.parse(organizationId),p_reservation_id:v.reservationId,p_expected_revision:v.expectedRevision,p_idempotency_key:v.idempotencyKey,p_action:v.action,p_changes:changes,p_receipt:v.receipt?buildReservationReceiptPayload(v.receipt):null};
}
async function invoke(rpc:ReservationRpcInvoker,name:ReservationRpcName,args:Record<string,Json>){const r=await rpc(name,args);if(r.error)throw r.error;return r.data;}
export async function createRoomReservation(rpc:ReservationRpcInvoker,organizationId:string,input:CreateRoomReservationInput):Promise<RoomReservation>{return roomReservationSchema.parse(await invoke(rpc,'create_room_reservation_v1',buildCreateRoomReservationArgs(organizationId,input)));}
export async function updateRoomReservation(rpc:ReservationRpcInvoker,organizationId:string,input:UpdateRoomReservationInput):Promise<RoomReservation>{return roomReservationSchema.parse(await invoke(rpc,'update_room_reservation_v1',buildUpdateRoomReservationArgs(organizationId,input)));}
export async function listRoomReservations(rpc:ReservationRpcInvoker,organizationId:string,filters:RoomReservationFilters={}):Promise<RoomReservationList>{return roomReservationListSchema.parse(await invoke(rpc,'list_room_reservations_v1',{p_organization_id:uuid.parse(organizationId),p_room_id:filters.roomId?uuid.parse(filters.roomId):null,p_customer_id:filters.customerId?uuid.parse(filters.customerId):null,p_status:filters.status??null,p_limit:z.number().int().min(1).max(200).parse(filters.limit??100)}));}
export function reservationErrorMessage(error:unknown):string{const e=error as {code?:string;message?:string};if(e?.code==='PT409'||e?.code==='40001')return'Hồ sơ giữ chỗ đã thay đổi. Tải lại trước khi tiếp tục.';if(e?.code==='42501')return e.message||'Bạn không có quyền thao tác giữ chỗ trong tổ chức này.';return e?.message||'Không thể lưu hồ sơ giữ chỗ.';}
