// Byte-safe builder for t3_03_writer_with_claim.sql.
// Extracts the exact function body from the BLOCKED artifact (UTF-8 safe,
// unlike PowerShell Get-Content default codepage) and inserts the T3 claim
// at the A.2 integration point plus the actor-name delegate swap.
import { readFileSync, writeFileSync } from 'node:fs';

const src = readFileSync(
  'supabase/migrations/20260716180000_t5_income_expense_create_draft_writer.sql', 'utf8');
const lines = src.split('\n');
const startIdx = lines.findIndex(l =>
  l.startsWith('CREATE OR REPLACE FUNCTION public.create_income_expense_v1('));
const endIdx = lines.findIndex((l, i) => i > startIdx && l.trim() === '$function$;');
if (startIdx < 0 || endIdx < 0) throw new Error('function boundaries not found');
let body = lines.slice(startIdx, endIdx + 1).join('\n');

// 0. auth.uid() → DEFINER delegate + declare the capability-nonce local. The
//    wrapper is postgres-owned SECURITY DEFINER, so app_private.current_uid_v1()
//    (a DEFINER delegate) provides auth.uid() and v_claim_cap carries the token.
const uidAnchor = `  v_actor uuid := auth.uid();`;
const uidRepl = `  v_actor uuid := app_private.current_uid_v1();
  v_claim_cap text;`;
if (!body.includes(uidAnchor)) throw new Error('uid anchor not found');
body = body.replace(uidAnchor, uidRepl);

// 1. Actor display-name via delegate (A.9 smallest shape).
const nameAnchor = `  SELECT COALESCE(NULLIF(btrim(p.full_name), ''), NULLIF(btrim(p.email), ''), u.email, 'Người dùng')
    INTO v_actor_name
    FROM auth.users u
    LEFT JOIN public.profiles p ON p.id = u.id
   WHERE u.id = v_actor;
  IF NOT FOUND THEN`;
const nameRepl = `  -- A.9 smallest-shape: actor display name via postgres-owned DEFINER delegate
  -- (auth.users/profiles RLS is not part of the writer role's capability set).
  v_actor_name := app_private.ie_actor_display_name_v1(v_actor);
  IF v_actor_name IS NULL THEN`;
if (!body.includes(nameAnchor)) throw new Error('name anchor not found');
body = body.replace(nameAnchor, nameRepl);

// 2. T3 claim at the A.2 integration point + audit via the A.5 chain
//    primitive (direct audit INSERT is rejected by the writer-monopoly guard).
const auditAnchor = `  INSERT INTO public.income_expense_audit_log (
    income_expense_id, action, actor_id, actor_name,
    old_status, new_status, note, organization_id
  ) VALUES (
    v_row.id, 'CREATED_DRAFT', v_actor, v_actor_name,
    NULL, 'UNAPPROVED', 'Tạo phiếu nháp qua create_income_expense_v1', v_org
  );`;
const claimAndAudit = `  -- =========================================================================
  -- T3 CLAIM (A.2 integration point): after construction + invariants +
  -- canary time recheck; before audit append and operation completion.
  -- A.9 smallest-shape: this wrapper is SECURITY DEFINER owned by postgres (so
  -- auth access + INVOKER triggers resolve on Supabase). Capability is proven by
  -- a transaction-local token stamped by a postgres-owned DEFINER setter that no
  -- app role can call, then echoed to the claim. (Replaces the unreachable
  -- current_user='ie_canonical_writer' gate — see t3_12.)
  -- =========================================================================
  v_claim_cap := app_private.grant_ie_claim_capability_v1();
  PERFORM app_private.claim_canonical_income_expense_draft_v1(
    v_row.id, v_idempotency_key, v_claim_cap);
  SELECT * INTO v_row FROM public.income_expenses WHERE id = v_row.id;

  -- A.5: canonical audit goes through the single hash-chain primitive; the
  -- audit-log writer-monopoly guard rejects any direct unchained INSERT.
  PERFORM app_private.append_income_expense_event_v1(
    v_org, v_row.id, 'CREATED_DRAFT', v_actor, v_actor_name,
    NULL, 'UNAPPROVED', 'Tạo phiếu nháp qua create_income_expense_v1');`;
if (!body.includes(auditAnchor)) throw new Error('audit anchor not found');
body = body.replace(auditAnchor, claimAndAudit);

const header = `-- ============================================================================
-- T3 PREPARED SQL 03 — create_income_expense_v1 WITH the T3 canonical claim.
-- STATUS: PREPARED (compile+behavior tested on disposable PG17 exact-source
-- restore). NOT a migration; never apply to production without owner gate.
-- GENERATED by build-t3-03.mjs from the BLOCKED artifact 20260716180000 —
-- do not hand-edit; edit the builder or the artifact and regenerate.
-- Diff vs the artifact function body:
--   + actor display name via app_private.ie_actor_display_name_v1 delegate
--   + PERFORM app_private.claim_canonical_income_expense_draft_v1(...) at the
--     exact A.2 integration point + stability reread
-- Prerequisites: t3_01 (role/sidecar/claim/freeze), t3_02 (re-own + grants).
-- ============================================================================

`;
writeFileSync('scripts/authz-prepared/t3_03_writer_with_claim.sql', header + body + '\n');
console.log('written', body.length, 'bytes body');
