// Byte-safe builder for t3_03_writer_with_claim.sql.
// Extracts the exact function body from the BLOCKED artifact (UTF-8 safe,
// unlike PowerShell Get-Content default codepage) and inserts the T3 claim
// at the A.2 integration point plus the actor-name delegate swap.
import { readFileSync, writeFileSync } from 'node:fs';

const src = readFileSync(
  'supabase/migrations/20260716180000_t5_income_expense_create_draft_writer.sql', 'utf8');
const lines = src.split('\n');
const startIdx = lines.findIndex(l =>
  l.startsWith('CREATE OR REPLACE FUNCTION public.create_income_expense_v1('));
const endIdx = lines.findIndex((l, i) => i > startIdx && l.trim() === '$function$;');
if (startIdx < 0 || endIdx < 0) throw new Error('function boundaries not found');
let body = lines.slice(startIdx, endIdx + 1).join('\n');

// 1. Actor display-name via delegate (A.9 smallest shape).
const nameAnchor = `  SELECT COALESCE(NULLIF(btrim(p.full_name), ''), NULLIF(btrim(p.email), ''), u.email, 'Người dùng')
    INTO v_actor_name
    FROM auth.users u
    LEFT JOIN public.profiles p ON p.id = u.id
   WHERE u.id = v_actor;
  IF NOT FOUND THEN`;
const nameRepl = `  -- A.9 smallest-shape: actor display name via postgres-owned DEFINER delegate
  -- (auth.users/profiles RLS is not part of the writer role's capability set).
  v_actor_name := app_private.ie_actor_display_name_v1(v_actor);
  IF v_actor_name IS NULL THEN`;
if (!body.includes(nameAnchor)) throw new Error('name anchor not found');
body = body.replace(nameAnchor, nameRepl);

// 2. T3 claim at the A.2 integration point (before audit append).
const claimAnchor = `  INSERT INTO public.income_expense_audit_log (`;
const claimRepl = `  -- =========================================================================
  -- T3 CLAIM (A.2 integration point): after construction + invariants +
  -- canary time recheck; before audit append and operation completion.
  -- Runs as current_user = ie_canonical_writer (this wrapper's owner).
  -- =========================================================================
  PERFORM app_private.claim_canonical_income_expense_draft_v1(
    v_row.id, v_idempotency_key);
  SELECT * INTO v_row FROM public.income_expenses WHERE id = v_row.id;

  INSERT INTO public.income_expense_audit_log (`;
if (!body.includes(claimAnchor)) throw new Error('claim anchor not found');
body = body.replace(claimAnchor, claimRepl);

const header = `-- ============================================================================
-- T3 PREPARED SQL 03 — create_income_expense_v1 WITH the T3 canonical claim.
-- STATUS: PREPARED (compile+behavior tested on disposable PG17 exact-source
-- restore). NOT a migration; never apply to production without owner gate.
-- GENERATED by build-t3-03.mjs from the BLOCKED artifact 20260716180000 —
-- do not hand-edit; edit the builder or the artifact and regenerate.
-- Diff vs the artifact function body:
--   + actor display name via app_private.ie_actor_display_name_v1 delegate
--   + PERFORM app_private.claim_canonical_income_expense_draft_v1(...) at the
--     exact A.2 integration point + stability reread
-- Prerequisites: t3_01 (role/sidecar/claim/freeze), t3_02 (re-own + grants).
-- ============================================================================

`;
writeFileSync('scripts/authz-prepared/t3_03_writer_with_claim.sql', header + body + '\n');
console.log('written', body.length, 'bytes body');
