-- ============================================================================
-- T0 PREPARED SQL — server_feature_flags storage-level hardening ONLY
-- STATUS: PREPARED. NOT a migration; production apply gated by owner (runbook
-- RUNBOOK-CUTOVER-PAYMENT.md). GENERATED by build-t0-ledger.mjs from the BLOCKED
-- artifact 20260716180000 — do not hand-edit; edit the artifact and regenerate.
-- Prerequisites: app_private schema + server_feature_flags (T5-infra
-- 20260716120200, APPLIED on production 2026-07-16). Idempotent by construction
-- (IF NOT EXISTS / OR REPLACE / DROP TRIGGER IF EXISTS) — safe on targets where
-- the objects already exist (e.g. staging installed via the full artifact).
-- ============================================================================

begin;

-- Close malformed rollout configurations at storage level as well as in the
-- evaluator. The prerequisite migration intentionally allowed OFF/zero-cap rows;
-- only active CANARY rows require a complete finite window and positive caps.
DO $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1
      FROM pg_catalog.pg_constraint c
     WHERE c.conrelid = 'app_private.server_feature_flags'::regclass
       AND c.conname = 'server_feature_flags_finite_values_check'
  ) THEN
    ALTER TABLE app_private.server_feature_flags
      ADD CONSTRAINT server_feature_flags_finite_values_check
      CHECK (
        (starts_at IS NULL OR isfinite(starts_at))
        AND (ends_at IS NULL OR isfinite(ends_at))
        AND max_single_amount_vnd::text NOT IN ('NaN', 'Infinity', '-Infinity')
        AND max_total_amount_vnd::text NOT IN ('NaN', 'Infinity', '-Infinity')
      ) NOT VALID;
  END IF;

  IF NOT EXISTS (
    SELECT 1
      FROM pg_catalog.pg_constraint c
     WHERE c.conrelid = 'app_private.server_feature_flags'::regclass
       AND c.conname = 'server_feature_flags_canary_limits_check'
  ) THEN
    ALTER TABLE app_private.server_feature_flags
      ADD CONSTRAINT server_feature_flags_canary_limits_check
      CHECK (
        mode <> 'CANARY'
        OR (
          starts_at IS NOT NULL
          AND ends_at IS NOT NULL
          AND isfinite(starts_at)
          AND isfinite(ends_at)
          AND starts_at < ends_at
          AND max_operation_count > 0
          AND max_single_amount_vnd > 0
          AND max_total_amount_vnd > 0
        )
      ) NOT VALID;
  END IF;

  ALTER TABLE app_private.server_feature_flags
    VALIDATE CONSTRAINT server_feature_flags_finite_values_check;
  ALTER TABLE app_private.server_feature_flags
    VALIDATE CONSTRAINT server_feature_flags_canary_limits_check;
END;
$function$;

commit;
