-- ============================================================================
-- T0 PREPARED SQL — canonical_write_operations ledger ONLY (+ append-only guard)
-- STATUS: PREPARED. NOT a migration; production apply gated by owner (runbook
-- RUNBOOK-CUTOVER-PAYMENT.md). GENERATED by build-t0-ledger.mjs from the BLOCKED
-- artifact 20260716180000 — do not hand-edit; edit the artifact and regenerate.
-- Prerequisites: app_private schema + server_feature_flags (T5-infra
-- 20260716120200, APPLIED on production 2026-07-16). Idempotent by construction
-- (IF NOT EXISTS / OR REPLACE / DROP TRIGGER IF EXISTS) — safe on targets where
-- the objects already exist (e.g. staging installed via the full artifact).
-- ============================================================================

begin;

CREATE TABLE IF NOT EXISTS app_private.canonical_write_operations (
  organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  operation text NOT NULL,
  subject_scope text NOT NULL,
  actor_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  idempotency_key text NOT NULL,
  payload_hash text NOT NULL,
  subject_id uuid,
  response_payload jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  PRIMARY KEY (organization_id, operation, subject_scope, actor_id, idempotency_key),
  CONSTRAINT canonical_write_operations_idempotency_key_check CHECK (
    char_length(idempotency_key) BETWEEN 8 AND 200
    AND idempotency_key ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{7,199}$'
  ),
  CONSTRAINT canonical_write_operations_payload_hash_check
    CHECK (char_length(payload_hash) = 32)
);

-- CREATE TABLE IF NOT EXISTS does not retrofit checks onto an existing ledger. Add
-- the named ASCII contract forward-only, validate existing data, and fail rather than
-- silently running TypeScript/PostgreSQL with different idempotency semantics.
DO $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1
      FROM pg_catalog.pg_constraint c
     WHERE c.conrelid = 'app_private.canonical_write_operations'::regclass
       AND c.conname = 'canonical_write_operations_idempotency_key_check'
  ) THEN
    ALTER TABLE app_private.canonical_write_operations
      ADD CONSTRAINT canonical_write_operations_idempotency_key_check
      CHECK (
        char_length(idempotency_key) BETWEEN 8 AND 200
        AND idempotency_key ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{7,199}$'
      ) NOT VALID;
  END IF;

  ALTER TABLE app_private.canonical_write_operations
    VALIDATE CONSTRAINT canonical_write_operations_idempotency_key_check;
END;
$function$;

CREATE INDEX IF NOT EXISTS canonical_write_operations_subject_idx
  ON app_private.canonical_write_operations (organization_id, operation, subject_id)
  WHERE subject_id IS NOT NULL;

DO $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1
      FROM pg_catalog.pg_constraint c
     WHERE c.conrelid = 'app_private.canonical_write_operations'::regclass
       AND c.conname = 'canonical_write_operations_completion_check'
  ) THEN
    ALTER TABLE app_private.canonical_write_operations
      ADD CONSTRAINT canonical_write_operations_completion_check
      CHECK (
        (completed_at IS NULL) = (response_payload IS NULL)
        AND (completed_at IS NULL) = (subject_id IS NULL)
      ) NOT VALID;
  END IF;
  IF EXISTS (
    SELECT 1
      FROM app_private.canonical_write_operations o
     WHERE (o.completed_at IS NULL) IS DISTINCT FROM (o.response_payload IS NULL)
        OR (o.completed_at IS NULL) IS DISTINCT FROM (o.subject_id IS NULL)
  ) THEN
    RAISE EXCEPTION 'Canonical operation ledger contains partial completion rows';
  END IF;
  ALTER TABLE app_private.canonical_write_operations
    VALIDATE CONSTRAINT canonical_write_operations_completion_check;
END;
$function$;

REVOKE ALL ON app_private.canonical_write_operations
  FROM PUBLIC, anon, authenticated, service_role;

CREATE OR REPLACE FUNCTION app_private.guard_canonical_write_operation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'pg_catalog', 'app_private'
AS $function$
BEGIN
  IF TG_OP IN ('DELETE', 'TRUNCATE') THEN
    RAISE EXCEPTION 'Canonical operation ledger is append-only'
      USING ERRCODE = '55000';
  END IF;

  IF OLD.subject_id IS NOT NULL
     OR OLD.response_payload IS NOT NULL
     OR OLD.completed_at IS NOT NULL THEN
    RAISE EXCEPTION 'Completed canonical operation is immutable'
      USING ERRCODE = '55000';
  END IF;
  IF NEW.organization_id IS DISTINCT FROM OLD.organization_id
     OR NEW.operation IS DISTINCT FROM OLD.operation
     OR NEW.subject_scope IS DISTINCT FROM OLD.subject_scope
     OR NEW.actor_id IS DISTINCT FROM OLD.actor_id
     OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
     OR NEW.payload_hash IS DISTINCT FROM OLD.payload_hash
     OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION 'Canonical operation identity is immutable'
      USING ERRCODE = '55000';
  END IF;
  IF NEW.subject_id IS NULL
     OR NEW.response_payload IS NULL
     OR NEW.completed_at IS NULL THEN
    RAISE EXCEPTION 'Canonical operation can only transition once to completed'
      USING ERRCODE = '55000';
  END IF;

  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION app_private.guard_canonical_write_operation()
  FROM PUBLIC, anon, authenticated, service_role;

DROP TRIGGER IF EXISTS canonical_write_operations_immutable
  ON app_private.canonical_write_operations;
CREATE TRIGGER canonical_write_operations_immutable
BEFORE UPDATE OR DELETE ON app_private.canonical_write_operations
FOR EACH ROW EXECUTE FUNCTION app_private.guard_canonical_write_operation();

DROP TRIGGER IF EXISTS canonical_write_operations_no_truncate
  ON app_private.canonical_write_operations;
CREATE TRIGGER canonical_write_operations_no_truncate
BEFORE TRUNCATE ON app_private.canonical_write_operations
FOR EACH STATEMENT EXECUTE FUNCTION app_private.guard_canonical_write_operation();

commit;
