// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
const io=vi.hoisted(()=>({save:vi.fn(),sourceError:false,retry:vi.fn(),meters:[{meter_id:'m1',meter_code:'M1',meter_name:'Điện P1',room_name:'P1',meter_type_value:'ELECTRICITY',last_reading:5,last_reading_date:null}]}));
vi.mock('@/hooks/useMeterReadings',()=>({useBulkCreateMeterReadings:()=>({mutateAsync:io.save,isPending:false}),useUpdateMeterReading:()=>({mutateAsync:io.save,isPending:false}),MeterReadingBatchPartialError:class extends Error{}}));
vi.mock('@/hooks/useMeters',()=>({useUnrecordedMeters:()=>({data:io.meters,isLoading:false,isError:false,refetch:io.retry})}));
vi.mock('@/hooks/useBuildings',()=>({useBuildings:()=>({data:[{id:'b1',name:'Tòa A'}],isLoading:false,isError:io.sourceError,refetch:io.retry})}));
vi.mock('@/hooks/useRooms',()=>({useRooms:()=>({data:[{id:'r1',name:'P1'}],isLoading:false,isError:false,refetch:io.retry})}));
vi.mock('@/hooks/useAuth',()=>({useAuth:()=>({data:{id:'actor'}})}));
vi.mock('@/lib/storage',()=>({uploadFile:vi.fn(),sanitizeStorageFileName:(v:string)=>v}));
vi.mock('sonner',()=>({toast:{error:vi.fn(),info:vi.fn()}}));
vi.mock('@/components/ui/select',()=>({Select:(p:{children:React.ReactNode;value:string;onValueChange:(value:string)=>void;disabled?:boolean})=><select disabled={p.disabled} value={p.value ?? ''} onChange={e=>p.onValueChange(e.target.value)}><option value=""/>{p.children}</select>,SelectTrigger:()=>null,SelectValue:()=>null,SelectContent:(p:{children:React.ReactNode})=><>{p.children}</>,SelectItem:(p:{value:string;children:React.ReactNode})=><option value={p.value}>{p.children}</option>}));
import MeterReadingForm from '../MeterReadingForm';
import {FinancialWorkflowError} from '@/lib/financialWorkflow';
vi.stubGlobal('ResizeObserver',class {observe(){}unobserve(){}disconnect(){}});
afterEach(()=>{cleanup();vi.resetAllMocks();io.sourceError=false;});
const reading={id:'r1',meter_id:'m1',building_id:'b1',room_id:'r1',meter_type:'ELECTRICITY',current_reading:10,previous_reading:5,reading_date:'2026-09-30',settlement_month:'2026-09'} as never;
it('required building source error blocks meter reading save with retry',()=>{io.sourceError=true;render(<MeterReadingForm open onOpenChange={vi.fn()} reading={reading}/>);expect(screen.getByRole('alert').textContent).toContain('Chưa tải đủ');fireEvent.click(screen.getByRole('button',{name:'Lưu'}));expect(io.save).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Tải lại dữ liệu'}));expect(io.retry).toHaveBeenCalled();});
it('unknown editing receipt keeps ID and draft through close and refresh',async()=>{io.save.mockRejectedValue(new FinancialWorkflowError('Chưa xác nhận chỉ số.','unknown',[{id:'r1',label:'Chỉ số cần đối chiếu'}]));const props={open:true,onOpenChange:vi.fn(),reading};const view=render(<MeterReadingForm {...props}/>);fireEvent.change(screen.getByDisplayValue('10'),{target:{value:'12'}});fireEvent.click(screen.getByRole('button',{name:'Lưu'}));await waitFor(()=>expect(screen.getByRole('alert').textContent).toContain('r1'));view.rerender(<MeterReadingForm {...props} open={false}/>);view.rerender(<MeterReadingForm {...props} reading={{...reading as object,current_reading:99} as never}/>);expect(screen.getByDisplayValue('12')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Lưu'}));expect(io.save).toHaveBeenCalledTimes(1);});

it('partial batch keeps edited rows across source refresh and closing, without replay',async()=>{io.save.mockRejectedValue(new FinancialWorkflowError('Chỉ số mới lưu một phần.','partial',[{id:'r-new',label:'Chỉ số đã nhận mã'}]));const props={open:true,onOpenChange:vi.fn(),reading:null};const view=render(<MeterReadingForm {...props}/>);fireEvent.change(screen.getAllByRole('combobox')[0],{target:{value:'b1'}});fireEvent.change(screen.getAllByRole('combobox')[1],{target:{value:'r1'}});const field=await screen.findByLabelText(/Chỉ số mới/);fireEvent.change(field,{target:{value:'12'}});fireEvent.click(screen.getByRole('button',{name:'Lưu'}));await waitFor(()=>expect(screen.getByRole('alert').textContent).toContain('r-new'));io.meters=io.meters.map(row=>({...row,last_reading:99}));view.rerender(<MeterReadingForm {...props} open={false}/>);view.rerender(<MeterReadingForm {...props}/>);expect((screen.getByLabelText(/Chỉ số mới/) as HTMLInputElement).value).toBe('12');fireEvent.click(screen.getByRole('button',{name:'Lưu'}));expect(io.save).toHaveBeenCalledTimes(1);});
