export const OPENCLAW_RUNTIME_TOKEN_TTL_SECONDS = 300;
export const OPENCLAW_REQUEST_CLOCK_SKEW_SECONDS = 60;
export const OPENCLAW_CLOCK_DRIFT_BREAKER_SECONDS = 2;
export const OPENCLAW_CLOCK_DRIFT_BREAKER_WINDOW_SECONDS = 120;
export const OPENCLAW_DEFAULT_JSON_LIMIT_BYTES = 256 * 1024;
export const OPENCLAW_MAX_INBOUND_BATCH_COUNT = 100;
