// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
const io = vi.hoisted(() => ({ create: vi.fn(), update: vi.fn(), services: vi.fn(), save: vi.fn(), load: vi.fn() }));
vi.mock('@/hooks/useBuildings', () => ({useCreateBuilding:()=>({mutateAsync:io.create,isPending:false}),useUpdateBuilding:()=>({mutateAsync:io.update,isPending:false})}));
vi.mock('@/hooks/useBuildingServices',()=>({useBuildingServices:()=>({}),useUpsertBuildingServices:()=>({mutateAsync:io.services,isPending:false})}));
vi.mock('@/hooks/useServices',()=>({useServices:()=>({})}));
vi.mock('@/hooks/useDocumentTemplates',()=>({useDocumentTemplatesByType:()=>({})}));
vi.mock('@/hooks/useAccounts',()=>({useAccounts:()=>({})}));
vi.mock('@/hooks/useMyContext',()=>({useMyContext:()=>({})}));
vi.mock('../BuildingAddressSection',()=>({default:({setValue}:{setValue:(key:string,value:string)=>void})=><button type="button" onClick={()=>{for(const key of ['province','district','ward','street_address'])setValue(key,'Fixture');}}>Địa chỉ thử</button>}));
vi.mock('../BuildingGeoSection',()=>({default:()=>null}));
vi.mock('../BuildingServicesSection',()=>({default:()=>null}));
vi.mock('../CommissionTiersField',()=>({CommissionTiersField:()=>null}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{}}));
vi.mock('@/lib/buildingLegalOwner',async importOriginal=>({...await importOriginal<typeof import('@/lib/buildingLegalOwner')>(),loadBuildingLegalOwner:io.load,saveBuildingLegalOwner:io.save}));
import BuildingFormDialog from '../BuildingFormDialog';
vi.stubGlobal('ResizeObserver',class { observe() {} unobserve() {} disconnect() {} });
afterEach(()=>{cleanup();vi.resetAllMocks();});
it('retries a failed owner save against the created building without creating a duplicate',async()=>{
 io.create.mockResolvedValue({id:'created-once'});io.services.mockResolvedValue(undefined);
 io.save.mockRejectedValueOnce(new Error('offline')).mockResolvedValue(undefined);
 const close=vi.fn();render(<BuildingFormDialog open onOpenChange={close}/>);
 fireEvent.change(screen.getByPlaceholderText('Nhập tên toà nhà'),{target:{value:'Fixture'}});
 fireEvent.click(screen.getByText('Địa chỉ thử'));
 fireEvent.change(screen.getByLabelText('Họ tên chủ sở hữu'),{target:{value:'Chủ đúng'}});
 fireEvent.click(screen.getByRole('button',{name:'Lưu'}));
 await screen.findByText(/Tòa nhà đã được tạo. Lần lưu tiếp theo/);
 await waitFor(()=>expect(io.save).toHaveBeenCalledTimes(1));
 expect(close).not.toHaveBeenCalled();
 fireEvent.click(screen.getByRole('button',{name:'Lưu'}));
 await waitFor(()=>expect(close).toHaveBeenCalledWith(false));
 expect(io.create).toHaveBeenCalledTimes(1);
 expect(io.save).toHaveBeenLastCalledWith('created-once',expect.objectContaining({full_name:'Chủ đúng'}));
});
