// @vitest-environment jsdom
import {cleanup,renderHook,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import type {ReactNode} from 'react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({reply:vi.fn(),filters:[] as unknown[]}));
vi.mock('@/lib/authSession',()=>({getSessionUser:async()=>({id:'actor-a'})}));vi.mock('@/hooks/useAuth',()=>({useAuth:()=>({data:{id:'actor-a'}})}));vi.mock('@/contexts/OrganizationContext',()=>({useOrganization:()=>({selectedOrganizationId:'org-a'})}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{from:(table:string)=>{const b={select:()=>b,eq:(key:string,value:unknown)=>{m.filters.push([table,key,value]);return b;},in:()=>b,order:()=>b,limit:()=>b,or:()=>b,range:()=>b,maybeSingle:()=>m.reply(table),then:(resolve:(v:unknown)=>unknown,reject:(v:unknown)=>unknown)=>Promise.resolve().then(()=>m.reply(table)).then(resolve,reject)};return b;}}}));
import {useSubscriptionPlans,useUserSubscription} from '../useSubscription';
import {useJobTypes,useDepartments} from '../useJobTypes';import {useJobGroups} from '../useJobGroups';import {useJobs} from '../useJobs';import {useCompanyInfo,useIndividualSetting,useGeneralSettings} from '../useSettings';
const variants=[{name:'plans',useHook:()=>useSubscriptionPlans()},{name:'job types',useHook:()=>useJobTypes()},{name:'departments',useHook:()=>useDepartments()},{name:'job groups',useHook:()=>useJobGroups()},{name:'jobs',useHook:()=>useJobs()},{name:'general settings',useHook:()=>useGeneralSettings()}];
const wrapper=({children}:{children:ReactNode})=><QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}>{children}</QueryClientProvider>;
beforeEach(()=>{vi.clearAllMocks();m.filters=[];m.reply.mockResolvedValue({data:null,error:null});});afterEach(cleanup);
for(const v of variants){const useHook=()=>{const q=v.useHook();return {isError:q.isError,isSuccess:q.isSuccess,data:q.data};};it.each([null,{},[{id:'row-a'}]])(v.name+' rejects missing/malformed list %j',async data=>{m.reply.mockResolvedValue({data:[],error:null}).mockResolvedValueOnce({data,error:null});const h=renderHook(useHook,{wrapper});await waitFor(()=>expect(h.result.current.isError).toBe(true));expect(h.result.current.data).toBeUndefined();});it(v.name+' genuine [] stays successful',async()=>{m.reply.mockResolvedValue({data:[],error:null});const h=renderHook(useHook,{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));});}
it.each([{}, {value:null},{value:[]},{value:{company_name:5,company_address:'',company_phone:'',company_email:''}}])('company config malformed cannot be default %j',async data=>{m.reply.mockResolvedValue({data:[],error:null}).mockResolvedValueOnce({data,error:null});const h=renderHook(useCompanyInfo,{wrapper});await waitFor(()=>expect(h.result.current.isError).toBe(true));});
it.each([{}, {value:null},{value:[]},{value:'false'}])('individual boolean malformed cannot be default %j',async data=>{m.reply.mockResolvedValue({data:[],error:null}).mockResolvedValueOnce({data,error:null});const h=renderHook(()=>useIndividualSetting('test-key',false),{wrapper});await waitFor(()=>expect(h.result.current.isError).toBe(true));});
it('company and general settings explicitly filter actual actor',async()=>{m.reply.mockResolvedValue({data:null,error:null});const company=renderHook(useCompanyInfo,{wrapper});await waitFor(()=>expect(company.result.current.isSuccess).toBe(true));expect(m.filters).toContainEqual(['settings','user_id','actor-a']);m.filters=[];m.reply.mockResolvedValue({data:[],error:null});const general=renderHook(useGeneralSettings,{wrapper});await waitFor(()=>expect(general.result.current.isSuccess).toBe(true));expect(m.filters).toContainEqual(['settings','user_id','actor-a']);});
it.each([{}, {id:'sub-a',user_id:'other'},{id:'sub-a',user_id:'actor-a',plan:null}])('subscription row rejects malformed/other actor %j',async data=>{m.reply.mockResolvedValue({data:[],error:null}).mockResolvedValueOnce({data,error:null});const h=renderHook(useUserSubscription,{wrapper});await waitFor(()=>expect(h.result.current.isError).toBe(true));});
it('confirmed absent subscription is legitimate null',async()=>{const h=renderHook(useUserSubscription,{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data).toBeNull();});

const date='2026-09-30T00:00:00Z';
const plan={id:'plan-a',name:'Gói A',description:null,price:0,duration_months:1,max_rooms:null,max_buildings:null,features:[],is_active:true,created_at:date,updated_at:date,organization_id:null};
const type={id:'type-a',user_id:'actor-a',name:'Loại A',organization_id:null,description:null,bonus_amount:0,counts_for_salary:false,is_contract:false,is_repair:false,is_active:true,auto_assign:null,business_hours_only:null,job_group_id:null,default_department_id:null,default_priority:null,acceptance_deadline:null,completion_deadline:null,customer_contact_deadline:null,created_at:date,updated_at:date,job_groups:null,departments:null};
const job={id:'job-a',code:'JOB01',title:'Việc A',description:null,building_id:null,room_id:null,job_type_id:null,priority:'NORMAL',assignee_id:null,assignee_name:null,deadline:null,status:'IN_PROGRESS',attachments:[],completion_time:null,completion_description:null,created_at:date,buildings:null,rooms:null,job_types:null,profiles:null};
const positives=[{name:'plan',useHook:()=>useSubscriptionPlans(),data:[plan]},{name:'job type',useHook:()=>useJobTypes(),data:[type]},{name:'department',useHook:()=>useDepartments(),data:[{id:'dep-a',name:'Đội A',code:'D1'}]},{name:'job group',useHook:()=>useJobGroups(),data:[{id:'group-a',user_id:'actor-a',name:'Nhóm A',color:null,description:null,icon:null,organization_id:null,created_at:date,updated_at:date}]},{name:'job',useHook:()=>useJobs(),data:[job]}];
for(const v of positives) it(v.name+' full generated source stays valid with zero/nullable fields',async()=>{m.reply.mockResolvedValue({data:[],error:null}).mockResolvedValueOnce({data:v.data,error:null});const h=renderHook(()=>{const q=v.useHook();return {isSuccess:q.isSuccess,data:q.data};},{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data).toEqual(v.data);});
it('full subscription verifies actor and related plan ID',async()=>{const data={id:'sub-a',user_id:'actor-a',plan_id:plan.id,start_date:'2026-09-01',end_date:'2026-10-01',status:'active',organization_id:null,created_at:date,updated_at:date,plan};m.reply.mockResolvedValue({data:[],error:null}).mockResolvedValueOnce({data,error:null});const h=renderHook(useUserSubscription,{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data).toEqual(data);});
it('full company config preserves optional bank and logo fields',async()=>{const value={company_name:'A',company_address:'',company_phone:'',company_email:'',company_logo_url:'https://example.com/logo.webp',bank_name:'B'};m.reply.mockResolvedValue({data:{id:'setting-a',key:'company_info',user_id:'actor-a',value},error:null});const h=renderHook(useCompanyInfo,{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data).toEqual(value);});
it.each([false,0,''])('individual valid primitive %j is preserved',async value=>{m.reply.mockResolvedValue({data:{value},error:null});const h=renderHook(()=>useIndividualSetting('test-key',value),{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data).toBe(value);});
it('general settings keeps actual typed values and defaults only missing keys',async()=>{m.reply.mockResolvedValue({data:[{key:'invoice_payment_deadline_days',value:0},{key:'payment_auto_approve',value:false}],error:null});const h=renderHook(useGeneralSettings,{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data).toMatchObject({invoice_payment_deadline_days:0,payment_auto_approve:false,contract_payment_date_setting:false});});
// Công tắc "Cài đặt ngày thanh toán" lưu boolean; trước đây gạt một lần là cả bộ cài đặt chung không đọc được nữa.
it.each([[true,true],[false,false],['1',false],['true',true]])('general settings reads payment-date toggle stored as %j',async(stored,expected)=>{m.reply.mockResolvedValue({data:[{key:'contract_payment_date_setting',value:stored}],error:null});const h=renderHook(useGeneralSettings,{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data).toMatchObject({contract_payment_date_setting:expected});});
it('joined profile may have a legitimately nullable full name',async()=>{const data=[{...job,profiles:{id:'actor-a',full_name:null}}];m.reply.mockResolvedValue({data:[],error:null}).mockResolvedValueOnce({data,error:null});const h=renderHook(useJobs,{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data).toEqual(data);});
