// @vitest-environment jsdom
import {beforeEach,it,expect,vi} from 'vitest';
const h=vi.hoisted(()=>({rpc:vi.fn(),error:vi.fn(),create:vi.fn(),args:vi.fn()}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc:h.rpc}}));vi.mock('@/lib/authSession',()=>({getSessionUser:async()=>({id:'u1'})}));
vi.mock('@tanstack/react-query',()=>({useMutation:(options:unknown)=>options,useQuery:vi.fn(),useQueryClient:()=>({invalidateQueries:vi.fn()})}));
vi.mock('@/lib/contractCreateRpc',()=>({buildCreateContractRpcArgs:h.args,createContractV2:h.create}));vi.mock('sonner',()=>({toast:{success:vi.fn(),error:h.error}}));
import {useCreateContract} from '../useContracts';
type Mutation={mutationFn:(input:unknown)=>Promise<unknown>;onError:(error:unknown,vars:unknown)=>void};
const input={payload:{contract:{room_id:'r1',rent_price:200,total_deposit:0}},idempotencyKey:'old-generated-key'};
beforeEach(()=>{localStorage.clear();localStorage.setItem('ihomecrm.selectedOrganizationId','o1');vi.clearAllMocks();h.args.mockReturnValue({});h.create.mockImplementation(async(rpc:(name:string,args:{p_idempotency_key:string})=>Promise<{data:unknown;error:unknown}>,request:{idempotencyKey:string})=>{const {data,error}=await rpc('create_contract_v2',{p_idempotency_key:request.idempotencyKey});if(error)throw error;return data;});});
it('unknown creation giữ durable room key sau remount/thay payload và không writer thứ hai',async()=>{h.rpc.mockRejectedValueOnce(new TypeError('Failed to fetch'));await expect((useCreateContract() as unknown as Mutation).mutationFn(input)).rejects.toThrow();await expect((useCreateContract() as unknown as Mutation).mutationFn({...input,idempotencyKey:'new-key',payload:{contract:{room_id:'r1',rent_price:999}}})).rejects.toThrow(/đối chiếu/);expect(h.rpc).toHaveBeenCalledOnce();});
it('key gửi RPC khớp marker persisted trước writer, không dùng random key chuẩn bị lại mỗi submit',async()=>{h.rpc.mockImplementation(async(_fn,args)=>{const key=localStorage.key(1)!;const records=Array.from({length:localStorage.length},(_,i)=>localStorage.key(i)!).filter(key=>key.includes('financial-pending'));expect(JSON.parse(localStorage.getItem(records[0])!).requestKey).toBe(args.p_idempotency_key);return {data:{contract:{id:'c1',room_id:'r1',status:'ACTIVE',rent_price:200,total_deposit:0}},error:null};});await expect((useCreateContract() as unknown as Mutation).mutationFn(input)).resolves.toMatchObject({id:'c1'});expect(h.rpc.mock.calls[0][1].p_idempotency_key).not.toBe(input.idempotencyKey);});
it('positive ID nhưng room/state receipt sai giữ ID marker và không gọi lại',async()=>{h.rpc.mockResolvedValue({data:{contract:{id:'c1',room_id:'other',status:'ACTIVE',rent_price:200,total_deposit:0}},error:null});await expect((useCreateContract() as unknown as Mutation).mutationFn(input)).rejects.toThrow();const key=Array.from({length:localStorage.length},(_,i)=>localStorage.key(i)!).find(key=>key.includes('financial-pending'))!;expect(JSON.parse(localStorage.getItem(key)!).completedIds).toContain('c1');await expect((useCreateContract() as unknown as Mutation).mutationFn(input)).rejects.toThrow();expect(h.rpc).toHaveBeenCalledOnce();});
it('caller sở hữu lỗi chỉ hiện một toast thay hook + stale-deposit toast',()=>{const hook=useCreateContract() as unknown as Mutation;hook.onError({code:'55000',message:'Phiếu cọc được chọn không hợp lệ hoặc đã được dùng'},{...input,suppressErrorToast:true});expect(h.error).not.toHaveBeenCalled();});
it('known rollback zero-write cho correction retry',async()=>{h.rpc.mockResolvedValueOnce({data:null,error:{code:'22023'}}).mockResolvedValueOnce({data:{contract:{id:'c1',room_id:'r1',status:'ACTIVE',rent_price:200,total_deposit:0}},error:null});await expect((useCreateContract() as unknown as Mutation).mutationFn(input)).rejects.toMatchObject({code:'22023'});await expect((useCreateContract() as unknown as Mutation).mutationFn(input)).resolves.toMatchObject({id:'c1'});});

it('unknown room create không bypass marker bằng đổi selected organization',async()=>{h.rpc.mockRejectedValueOnce(new TypeError('Failed to fetch'));await expect((useCreateContract() as unknown as Mutation).mutationFn(input)).rejects.toThrow();localStorage.setItem('ihomecrm.selectedOrganizationId','other-org');await expect((useCreateContract() as unknown as Mutation).mutationFn(input)).rejects.toThrow(/đối chiếu/);expect(h.rpc).toHaveBeenCalledOnce();});

it.each([{rent_price:201,total_deposit:0},{rent_price:200,total_deposit:10}])('create receipt has wrong money %j and retains the contract ID',async money=>{
 h.rpc.mockResolvedValue({data:{contract:{id:'c1',room_id:'r1',status:'ACTIVE',...money}},error:null});
 await expect((useCreateContract() as unknown as Mutation).mutationFn(input)).rejects.toMatchObject({outcome:'partial'});
 const key=Array.from({length:localStorage.length},(_,i)=>localStorage.key(i)!).find(key=>key.includes('financial-pending'))!;expect(JSON.parse(localStorage.getItem(key)!).completedIds).toContain('c1');
});
