// @vitest-environment jsdom
import {act,cleanup,renderHook,waitFor} from '@testing-library/react';import {afterEach,beforeEach,it,expect,vi} from 'vitest';
const h=vi.hoisted(()=>({sign:vi.fn(),read:vi.fn(),download:vi.fn(),selected:'11111111-1111-4111-8111-111111111111'}));
vi.mock('@/lib/authSession',()=>({getSessionUser:async()=>({id:'actor1'})}));
vi.mock('@/contexts/OrganizationContext',()=>({useOrganization:()=>({selectedOrganizationId:h.selected})}));
vi.mock('@tanstack/react-query',()=>({useMutation:(options:unknown)=>options,useQuery:vi.fn(),useQueryClient:()=>({setQueryData:vi.fn(),invalidateQueries:vi.fn()})}));
vi.mock('@/lib/contractSigningApi',()=>({signAndCheckinDraft:h.sign,readContractDraftSigning:h.read,getOrCreateSignedContractDocument:h.download}));vi.mock('sonner',()=>({toast:{error:vi.fn(),success:vi.fn()}}));
import {useContractSigning} from '../contracts/useContractSigning';import {signingErrorMessage,type ContractSigningInput} from '@/lib/contractSigning';
const id='11111111-1111-4111-8111-111111111111';
const input:ContractSigningInput={source:{draftId:id,revision:1,documentId:id,documentSha256:'a'.repeat(64)},requestId:id,receivedOn:'2026-09-28',roomReady:true,termsConfirmed:true,boundary:{state:'VERIFIED',readings:[]},creationOptions:{}};
const row={id,organization_id:id,building_id:id,room_id:id,draft_id:id,revision:1,document_id:id,document_sha256:'a'.repeat(64),template_sha256:'b'.repeat(64),template_path:'template',template_snapshot:{id,name:'Mẫu',updated_at:'2026-09-28'},document_data:{},terms:{},party_snapshot:[],creation_options:{},received_on:'2026-09-28',contract_id:id,contract_number:'HD-01',request_id:id,signed_by:id,signed_at:'2026-09-28',official_document_path:'signed',official_document_sha256:null};
type Mutation={mutationFn:(input?:ContractSigningInput)=>Promise<unknown>;pendingRequestId?:string|null};
const hook=()=>renderHook(()=>useContractSigning(id,id) as unknown as Mutation);
beforeEach(()=>{localStorage.clear();h.selected=id;localStorage.setItem('ihomecrm.selectedOrganizationId',id);vi.clearAllMocks();h.read.mockResolvedValue({server_today:'2026-09-28',signing:null});});afterEach(cleanup);
it('signing unknown remount + input đổi không ghi lại, read null không proof rollback',async()=>{h.sign.mockRejectedValueOnce(new TypeError('Failed to fetch'));const first=hook();await expect(first.result.current.mutationFn(input)).rejects.toThrow();first.unmount();const reopened=hook();await expect(reopened.result.current.mutationFn({...input,source:{...input.source,revision:2}})).rejects.toThrow(/đối chiếu/);expect(h.sign).toHaveBeenCalledOnce();expect(h.read).toHaveBeenCalled();});
it('request ID gửi sign RPC khớp marker persisted trước writer',async()=>{h.sign.mockImplementation(async(_org,args)=>{const key=Array.from({length:localStorage.length},(_,i)=>localStorage.key(i)!).find(key=>key.includes('financial-pending'))!;expect(JSON.parse(localStorage.getItem(key)!).requestKey).toBe(args.requestId);return {...row,request_id:args.requestId};});await expect(hook().result.current.mutationFn(input)).resolves.toMatchObject({contract_id:id});expect(h.sign.mock.calls[0][1].requestId).not.toBe(input.requestId);});
it('readonly exact requestKey signing clears after reload without sign RPC again',async()=>{h.sign.mockRejectedValueOnce(new TypeError('Failed to fetch'));await expect(hook().result.current.mutationFn(input)).rejects.toThrow();const key=Array.from({length:localStorage.length},(_,i)=>localStorage.key(i)!).find(key=>key.includes('financial-pending'))!;const pending=JSON.parse(localStorage.getItem(key)!);h.read.mockResolvedValue({server_today:'2026-09-28',signing:{...row,request_id:pending.requestKey}});await expect(hook().result.current.mutationFn()).resolves.toMatchObject({request_id:pending.requestKey});expect(h.sign).toHaveBeenCalledOnce();expect(localStorage.getItem(key)).toBeNull();});
it('readonly wrong requestKey or wrong draft cannot clear/replay',async()=>{h.sign.mockRejectedValueOnce(new TypeError('Failed to fetch'));await expect(hook().result.current.mutationFn(input)).rejects.toThrow();h.read.mockResolvedValue({server_today:'2026-09-28',signing:row});await expect(hook().result.current.mutationFn()).rejects.toThrow();expect(h.sign).toHaveBeenCalledOnce();});
it('wrong source receipt giữ contract ID partial và không sign lại',async()=>{h.sign.mockResolvedValue({...row,draft_id:'22222222-2222-4222-8222-222222222222'});await expect(hook().result.current.mutationFn(input)).rejects.toMatchObject({completed:[expect.objectContaining({id})]});await expect(hook().result.current.mutationFn(input)).rejects.toThrow();expect(h.sign).toHaveBeenCalledOnce();});
it('raw technical Error và network message không hiện cho người dùng/không mời gửi lại mù',()=>{expect(signingErrorMessage(new Error('private sql relation canonical.atomic'))).not.toMatch(/private|canonical|atomic|thử lại/i);expect(signingErrorMessage(new TypeError('Failed to fetch'))).toMatch(/đối chiếu|kiểm tra/);});

it('positive same-intent signing may return the prior request ID exactly as SQL already-signed replay does',async()=>{h.sign.mockResolvedValue(row);await expect(hook().result.current.mutationFn(input)).resolves.toMatchObject({request_id:id,contract_id:id});expect(h.sign.mock.calls[0][1].requestId).not.toBe(id);expect(Array.from({length:localStorage.length},(_,i)=>localStorage.key(i)!).filter(key=>key.includes('financial-pending'))).toEqual([]);});
