// @vitest-environment jsdom
import {beforeEach,expect,it,vi} from 'vitest';
const io=vi.hoisted(()=>({from:vi.fn(),success:vi.fn(),info:vi.fn()}));vi.mock('@tanstack/react-query',()=>({useMutation:(v:unknown)=>v,useQueryClient:()=>({invalidateQueries:vi.fn()})}));vi.mock('@/integrations/supabase/client',()=>({supabase:{from:io.from}}));vi.mock('@/lib/authSession',()=>({getSessionUser:async()=>({id:'actor'})}));vi.mock('@/contexts/OrganizationContext',()=>({useOrganization:()=>({selectedOrganizationId:'o1'})}));vi.mock('sonner',()=>({toast:{success:io.success,info:io.info,error:vi.fn()}}));
import {useCreateIncomeExpenseType,useUpdateIncomeExpenseType,useDeleteIncomeExpenseType} from '../useIncomeExpenseTypes';import {useCreateIncomeExpenseTemplate,useUpdateIncomeExpenseTemplate,useDeleteIncomeExpenseTemplate,useToggleDefaultTemplate} from '../useIncomeExpenseTemplates';
type NamedRecordQuery={insert:()=>NamedRecordQuery;update:()=>NamedRecordQuery;delete:()=>NamedRecordQuery;select:()=>NamedRecordQuery;eq:()=>NamedRecordQuery;is:()=>NamedRecordQuery;in:()=>NamedRecordQuery;limit:()=>NamedRecordQuery;single:()=>NamedRecordQuery;then:(resolve:(response:{data:unknown;error:null})=>void)=>void};
function chain(data:unknown){const q:NamedRecordQuery={insert:()=>q,update:()=>q,delete:()=>q,select:()=>q,eq:()=>q,is:()=>q,in:()=>q,limit:()=>q,single:()=>q,then:resolve=>resolve({data,error:null})};return q;}
beforeEach(()=>{vi.resetAllMocks();localStorage.clear();localStorage.setItem('ihomecrm.selectedOrganizationId','o1');});
it.each([[useCreateIncomeExpenseType,{name:'Vệ sinh',type:'expense'}],[useUpdateIncomeExpenseType,{id:'r1',updates:{name:'Vệ sinh'}}],[useDeleteIncomeExpenseType,'r1'],[useCreateIncomeExpenseTemplate,{name:'Vệ sinh'}],[useUpdateIncomeExpenseTemplate,{id:'r1',updates:{name:'Vệ sinh'}}],[useDeleteIncomeExpenseTemplate,'r1']])('CRUD feedback names the actual confirmed record',async(hook,input)=>{io.from.mockImplementation(table=>chain(table==='income_expense_items'?[]:{id:'r1',name:'Vệ sinh'}));const config=hook() as unknown as {mutationFn:(v:unknown)=>Promise<unknown>;onSuccess:(d:unknown,v:unknown)=>void};const saved=await config.mutationFn(input);config.onSuccess(saved,input);expect(io.success.mock.lastCall?.[0]).toContain('Vệ sinh');});
it('default feedback names the confirmed template',()=>{const config=useToggleDefaultTemplate() as unknown as {onSuccess:(d:unknown)=>void};config.onSuccess({id:'r1',name:'Mẫu nhà trọ',is_default:true,unchanged:false});expect(io.success.mock.lastCall?.[0]).toContain('Mẫu nhà trọ');});
it('missing delete name uses the confirmed ID without inventing a name',()=>{const config=useDeleteIncomeExpenseTemplate() as unknown as {onSuccess:(d:unknown,v:unknown)=>void};config.onSuccess({id:'r1'},'r1');expect(io.success.mock.lastCall?.[0]).toContain('r1');});
