// @vitest-environment jsdom
import {beforeEach,expect,it,vi} from 'vitest';
const io=vi.hoisted(()=>({from:vi.fn()}));
vi.mock('@tanstack/react-query',()=>({useQuery:(config:unknown)=>config,useMutation:(config:unknown)=>config,useQueryClient:()=>({invalidateQueries:vi.fn()})}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{from:io.from}}));
vi.mock('@/contexts/OrganizationContext',()=>({useOrganization:()=>({selectedOrganizationId:'org-a'})}));
vi.mock('@/lib/authSession',()=>({getSessionUser:async()=>({id:'actor'})}));
vi.mock('sonner',()=>({toast:{success:vi.fn(),error:vi.fn(),info:vi.fn()}}));
import {useIncomeExpenseTemplates,useCreateIncomeExpenseTemplate,useUpdateIncomeExpenseTemplate,useDeleteIncomeExpenseTemplate,useToggleDefaultTemplate} from '../useIncomeExpenseTemplates';
import {useCreateIncomeExpenseType} from '../useIncomeExpenseTypes';
type Mutation={mutationFn:(input:unknown)=>Promise<unknown>};
function chain(data:unknown,error:unknown=null){const writer={insert:vi.fn(),update:vi.fn(),delete:vi.fn(),select:vi.fn(),eq:vi.fn(),is:vi.fn(),in:vi.fn(),order:vi.fn(),single:vi.fn().mockResolvedValue({data,error}),then:(resolve:(v:unknown)=>void)=>resolve({data,error})};for(const m of ['insert','update','delete','select','eq','is','in','order'] as const)writer[m].mockReturnValue(writer);return writer;}
beforeEach(()=>{vi.resetAllMocks();localStorage.clear();localStorage.setItem('ihomecrm.selectedOrganizationId','org-a');});
it('template list null is a source error',async()=>{io.from.mockReturnValue(chain(null));await expect((useIncomeExpenseTemplates() as unknown as {queryFn:()=>Promise<unknown>}).queryFn()).rejects.toThrow();});
it.each([['template',useCreateIncomeExpenseTemplate,{name:'Mẫu A'}],['type',useCreateIncomeExpenseType,{name:'Vệ sinh',type:'expense'}]])('%s create requires receipt and holds across remount',async(_label,hook,input)=>{const writer=chain(null);io.from.mockReturnValue(writer);await expect((hook() as unknown as Mutation).mutationFn(input)).rejects.toMatchObject({outcome:'unknown'});await expect((hook() as unknown as Mutation).mutationFn(input)).rejects.toThrow();expect(writer.insert).toHaveBeenCalledTimes(1);});
it.each([['update',useUpdateIncomeExpenseTemplate,{id:'t1',updates:{name:'A'}}],['delete',useDeleteIncomeExpenseTemplate,'t1']])('template %s needs exact receipt',async(_label,hook,input)=>{io.from.mockReturnValue(chain(null));await expect((hook() as unknown as Mutation).mutationFn(input)).rejects.toMatchObject({outcome:'unknown'});});
it('default update needs the desired state, not just the ID',async()=>{const read=chain([]);const saved=chain({id:'t1',is_default:false});io.from.mockReturnValueOnce(read).mockReturnValue(saved);await expect((useToggleDefaultTemplate() as unknown as Mutation).mutationFn({id:'t1',is_default:true,is_income_template:true})).rejects.toThrow();});
it('partial default update cannot unset again across remount',async()=>{const read=chain([{id:'old'}]);const unset=chain([{id:'old',is_default:false}]);const save=chain(null,{code:'42501',message:'raw SQL'});io.from.mockReturnValueOnce(read).mockReturnValueOnce(unset).mockReturnValueOnce(save).mockReturnValueOnce(chain([])).mockReturnValueOnce(unset).mockReturnValue(save);const input={id:'t1',is_default:true,is_income_template:true};await expect((useToggleDefaultTemplate() as unknown as Mutation).mutationFn(input)).rejects.toThrow();await expect((useToggleDefaultTemplate() as unknown as Mutation).mutationFn(input)).rejects.toThrow();expect(unset.update).toHaveBeenCalledTimes(1);expect(save.update).toHaveBeenCalledTimes(1);});

it('default recovery cannot clear another target intent',async()=>{const read=chain([{id:'old'}]);const unset=chain([{id:'old',is_default:false}]);const save=chain(null,{code:'42501',message:'raw SQL'});const group=chain([{id:'other',is_default:true,is_income_template:true,user_id:'actor'}]);io.from.mockReturnValueOnce(read).mockReturnValueOnce(unset).mockReturnValueOnce(save).mockReturnValue(group);await expect((useToggleDefaultTemplate() as unknown as Mutation).mutationFn({id:'t1',is_default:true,is_income_template:true})).rejects.toThrow();await expect((useToggleDefaultTemplate() as unknown as Mutation).mutationFn({id:'other',is_default:true,is_income_template:true})).rejects.toThrow();expect(group.update).not.toHaveBeenCalled();});

it('default recovery confirms original target state without another write',async()=>{const read=chain([{id:'old'}]);const unset=chain([{id:'old',is_default:false}]);const save=chain(null,{code:'42501',message:'raw SQL'});const group=chain([{id:'old',is_default:false,is_income_template:true,user_id:'actor'},{id:'t1',is_default:true,is_income_template:true,user_id:'actor'}]);io.from.mockReturnValueOnce(read).mockReturnValueOnce(unset).mockReturnValueOnce(save).mockReturnValue(group);const input={id:'t1',is_default:true,is_income_template:true};await expect((useToggleDefaultTemplate() as unknown as Mutation).mutationFn(input)).rejects.toThrow();await expect((useToggleDefaultTemplate() as unknown as Mutation).mutationFn(input)).resolves.toMatchObject({id:'t1',is_default:true});expect(group.update).not.toHaveBeenCalled();expect(unset.update).toHaveBeenCalledTimes(1);});
