// @vitest-environment jsdom
import {beforeEach,expect,it,vi} from 'vitest';
import {toast} from 'sonner';
import {FinancialWorkflowError} from '@/lib/financialWorkflow';
const io=vi.hoisted(()=>({from:vi.fn()}));
vi.mock('@tanstack/react-query',()=>({useQuery:(value:unknown)=>value,useMutation:(value:unknown)=>value,useQueryClient:()=>({invalidateQueries:vi.fn()})}));
vi.mock('@/integrations/supabase/client',()=>({supabase:io}));vi.mock('@/lib/authSession',()=>({getSessionUser:async()=>({id:'actor'})}));vi.mock('sonner',()=>({toast:{error:vi.fn(),success:vi.fn(),info:vi.fn()}}));
import {useCreateMaterialPurchase,useUpdateMaterialPurchase} from '../useMaterialPurchases';import {useCreateMaterialUsage,useUpsertJobMaterialUsage} from '../useMaterialUsages';import {useCreateMaterialAdjustment,useSetMaterialStock} from '../useMaterialAdjustments';
interface Write {table:string;verb:string;payload?:unknown;filters:Array<[string,unknown]>}
type Result={data:unknown;error:unknown};
let writes:Write[]=[];let existing=true;let insertError:unknown=null;let cleanupError:unknown=null;let cleanupMissing=false;let cleanupWrongId=false;let missingInsertReceipt=false;let missingDeleteReceipt=false;
function fixture(table:string){let verb='read';let active:Write|undefined;
 const result=():Result=>{
  if(verb==='read')return {data:table==='material_usages'?(existing?{id:'header-1'}:null):[{id:'old-1',material_id:'m-1'}],error:null};
  if(table.endsWith('_items'))return {data:verb==='delete'?(missingDeleteReceipt?null:[{id:'old-1'}]):(missingInsertReceipt?[]:[{id:'new-1'}]),error:verb==='insert'?insertError:null};
  return {data:verb==='delete'&&cleanupMissing?null:{id:verb==='delete'&&cleanupWrongId?'other-header':'header-1'},error:verb==='delete'?cleanupError:null};
 };
 const q={insert:vi.fn(),update:vi.fn(),delete:vi.fn(),upsert:vi.fn(),eq:vi.fn(),in:vi.fn(),select:vi.fn(),single:vi.fn(),maybeSingle:vi.fn(),then:(resolve:(value:Result)=>unknown)=>resolve(result())};
 for(const name of ['insert','update','delete','upsert'] as const)q[name].mockImplementation((payload?:unknown)=>{verb=name;active={table,verb,payload,filters:[]};writes.push(active);return q;});
 q.eq.mockImplementation((column:string,value:unknown)=>{active?.filters.push([column,value]);return q;});q.in.mockImplementation(()=>q);q.select.mockImplementation(()=>q);q.single.mockImplementation(async()=>result());q.maybeSingle.mockImplementation(async()=>result());return q;
}
const run=(hook:()=>unknown,input:unknown)=>(hook() as {mutationFn:(value:unknown)=>Promise<unknown>}).mutationFn(input);
const purchase={purchase_date:'2026-09-30',supplier_id:null,notes:null,items:[{material_id:'m-1',quantity:2,unit_price:100}]};const usage={usage_date:'2026-09-30',notes:null,items:[{material_id:'m-1',quantity:2,unit_cost_at_usage:100}]};const adjustment={adjustment_date:'2026-09-30',type:'IN',reason:null,items:[{material_id:'m-1',quantity:2}]};
beforeEach(()=>{vi.clearAllMocks();localStorage.clear();localStorage.setItem('ihomecrm.selectedOrganizationId','org-a');writes=[];existing=true;insertError=null;cleanupError=null;cleanupMissing=false;cleanupWrongId=false;missingInsertReceipt=false;missingDeleteReceipt=false;io.from.mockImplementation(fixture);});
it('purchase UPDATE then DELETE-all then INSERT preserves main projection and default server line ID',async()=>{await run(useUpdateMaterialPurchase,{id:'header-1',input:{...purchase,items:[{...purchase.items[0],id:'caller-id',extra:'ignored'}]}});expect(writes.map(w=>w.table+':'+w.verb)).toEqual(['material_purchases:update','material_purchase_items:delete','material_purchase_items:insert']);expect(writes[0].payload).toEqual({purchase_date:purchase.purchase_date,supplier_id:null,notes:null});expect(writes[1].filters).toEqual([['purchase_id','header-1']]);expect(writes[2].payload).toEqual([{purchase_id:'header-1',material_id:'m-1',quantity:2,unit_price:100}]);});
it('job UPDATE then DELETE-all then INSERT preserves main projection/default line identity',async()=>{await run(useUpsertJobMaterialUsage,{...usage,job_id:'job-1',items:[{...usage.items[0],id:'caller-id',extra:'ignored'}]});expect(writes.map(w=>w.table+':'+w.verb)).toEqual(['material_usages:update','material_usage_items:delete','material_usage_items:insert']);expect(writes[1].filters).toEqual([['usage_id','header-1']]);expect(writes[2].payload).toEqual([{usage_id:'header-1',material_id:'m-1',quantity:2,unit_cost_at_usage:100}]);});
it('empty existing job keeps main UPDATE-header DELETE-items DELETE-header order',async()=>{await expect(run(useUpsertJobMaterialUsage,{...usage,job_id:'job-1',items:[]})).resolves.toBe('header-1');expect(writes.map(w=>w.table+':'+w.verb)).toEqual(['material_usages:update','material_usage_items:delete','material_usages:delete']);});
it('empty purchase update keeps main UPDATE-header DELETE-all and no insert',async()=>{await run(useUpdateMaterialPurchase,{id:'header-1',input:{...purchase,items:[]}});expect(writes.map(w=>w.verb)).toEqual(['update','delete']);});
it.each([[useCreateMaterialPurchase,purchase,'material_purchases','purchase_id'],[useCreateMaterialUsage,usage,'material_usages','usage_id'],[useCreateMaterialAdjustment,adjustment,'material_adjustments','adjustment_id']])('create preserves main explicit projection and server default ID',async(hook,input,table,foreignKey)=>{await run(hook,{...input,items:[{...input.items[0],id:'caller-id',extra:'ignored'}]});expect(writes.map(w=>w.verb)).toEqual(['insert','insert']);const row={...input.items[0],[foreignKey]:'header-1'};expect(writes[1].payload).toEqual([row]);expect(writes[0].table).toBe(table);});
it.each([[useCreateMaterialPurchase,purchase],[useCreateMaterialAdjustment,adjustment]])('create empty remains delegated to main writer rather than new hook constraint',async(hook,input)=>{await run(hook,{...input,items:[]});expect(writes).toHaveLength(1);expect(writes[0].verb).toBe('insert');});
it('SET retains main signed delta/Math.abs and object line payload without client ID',async()=>{await run(useSetMaterialStock,{material_id:'m-1',current_quantity:1,target_quantity:-2});expect(writes[0].payload).toMatchObject({type:'OUT',reason:'Kiểm kê — đặt lại tồn'});expect(writes[1].payload).toEqual({adjustment_id:'header-1',material_id:'m-1',quantity:3});});
it.each([[useCreateMaterialPurchase,purchase,'material_purchases'],[useCreateMaterialUsage,usage,'material_usages'],[useCreateMaterialAdjustment,adjustment,'material_adjustments'],[useSetMaterialStock,{material_id:'m-1',current_quantity:1,target_quantity:2},'material_adjustments']])('confirmed main cleanup after known rejection releases retry truthfully',async(hook,input,table)=>{insertError={code:'42501',message:'SQL secret'};const error=await run(hook,input).catch(e=>e);expect(writes.map(w=>w.verb)).toEqual(['insert','insert','delete']);expect(writes[2].table).toBe(table);expect(writes[2].filters).toEqual([['id','header-1']]);expect(error).toMatchObject({outcome:'failure',completed:[]});if(!(error instanceof FinancialWorkflowError))throw new Error('Expected workflow feedback');expect(error.message).toContain('phiếu tạm đã gỡ');expect(error.message).not.toContain('SQL secret');(hook() as unknown as {onError:(error:unknown)=>void}).onError(error);expect(JSON.stringify(vi.mocked(toast.error).mock.calls)).toContain('phiếu tạm đã gỡ');expect(JSON.stringify(vi.mocked(toast.error).mock.calls)).not.toContain('SQL secret');await expect(run(hook,input)).rejects.toMatchObject({outcome:'failure'});expect(writes).toHaveLength(6);});
it.each(['missing','error','wrong-ID'])('cleanup uncertainty keeps header ID and blocks remount replay',async(mode)=>{insertError={code:'42501',message:'SQL secret'};cleanupMissing=mode==='missing';cleanupWrongId=mode==='wrong-ID';cleanupError=mode==='error'?{code:'42501',message:'cleanup SQL'}:null;await expect(run(useCreateMaterialPurchase,purchase)).rejects.toMatchObject({outcome:'partial',completed:expect.arrayContaining([expect.objectContaining({id:'header-1'})])});await expect(run(useCreateMaterialPurchase,purchase)).rejects.toMatchObject({outcome:'partial'});expect(writes).toHaveLength(3);});
it('unknown original line result stays blocked even when main header cleanup is confirmed',async()=>{insertError=new Error('offline');const error=await run(useCreateMaterialPurchase,purchase).catch(error=>error);expect(error).toMatchObject({outcome:'partial',completed:expect.arrayContaining([expect.objectContaining({id:'header-1'})])});if(!(error instanceof FinancialWorkflowError))throw new Error('Expected workflow feedback');expect(error.message).toContain('đã gỡ');expect(error.message).not.toContain('đã tạo');await expect(run(useCreateMaterialPurchase,purchase)).rejects.toMatchObject({outcome:'partial'});expect(writes).toHaveLength(3);});
it('missing insert receipt does not add cleanup beyond main and retains IDs/no-replay',async()=>{missingInsertReceipt=true;await expect(run(useCreateMaterialPurchase,purchase)).rejects.toMatchObject({outcome:'partial'});expect(writes.map(w=>w.verb)).toEqual(['insert','insert']);await expect(run(useCreateMaterialPurchase,purchase)).rejects.toMatchObject({outcome:'partial'});expect(writes).toHaveLength(2);});
it('unknown deletion receipt stops replacement and preserves header/guard',async()=>{missingDeleteReceipt=true;await expect(run(useUpdateMaterialPurchase,{id:'header-1',input:purchase})).rejects.toMatchObject({outcome:'partial'});expect(writes.map(w=>w.verb)).toEqual(['update','delete']);await expect(run(useUpdateMaterialPurchase,{id:'header-1',input:purchase})).rejects.toMatchObject({outcome:'partial'});expect(writes).toHaveLength(2);});

it('new job preserves main header/line projection with server default ID',async()=>{existing=false;await run(useUpsertJobMaterialUsage,{...usage,job_id:'job-1',items:[{...usage.items[0],id:'caller-id',extra:'ignored'}]});expect(writes.map(w=>w.table+':'+w.verb)).toEqual(['material_usages:insert','material_usage_items:insert']);expect(writes[0].payload).toEqual({job_id:'job-1',usage_date:usage.usage_date,notes:null});expect(writes[1].payload).toEqual([{usage_id:'header-1',material_id:'m-1',quantity:2,unit_cost_at_usage:100}]);});
it('new job line rejection does not add cleanup beyond main, empty retry cannot release prior',async()=>{existing=false;insertError={code:'42501',message:'SQL secret'};await expect(run(useUpsertJobMaterialUsage,{...usage,job_id:'job-1'})).rejects.toMatchObject({outcome:'partial',completed:expect.arrayContaining([expect.objectContaining({id:'header-1'})])});expect(writes.map(w=>w.verb)).toEqual(['insert','insert']);await expect(run(useUpsertJobMaterialUsage,{...usage,job_id:'job-1',items:[]})).rejects.toMatchObject({outcome:'partial'});expect(writes).toHaveLength(2);});
