// @vitest-environment jsdom
import {cleanup,renderHook,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import type {ReactNode} from 'react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({rpc:vi.fn()}));vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc:m.rpc}}));
import {useOrganizationMembers,useMemberAuthorization,useOrganizationRoles,useAuthorizationCatalog,useOrganizationProfile} from '../useOrganizationAuthorization';
const core={membershipId:'member-a',userId:'actor-a',email:null,fullName:null,memberType:'STAFF',status:'ACTIVE',version:1,isSelf:false};
const member={...core,roles:[],overrideAllow:0,overrideDeny:0,cashbooksHeld:0,permissionCount:0};
const auth={...core,roleBindings:[],overrides:[],cashbooksHeld:[],effectiveKeys:[]};
const role={roleId:'role-a',name:'Vai trò A',isSystem:false,status:'ACTIVE',version:1,memberCount:0,allowKeys:[],denyKeys:[]};
const catalog={scopes:[],permissions:[]};
const profile={organizationId:'org-a',name:'Tổ chức A',slug:'org-a',status:'ACTIVE',isDemo:false,createdAt:'2026-09-30T00:00:00Z',authorizationVersion:1,canEdit:false,counts:{members:0,owners:0,roles:0,buildings:0,areas:0,cashbooks:0,pendingInvitations:0,activeOverrides:0},invitations:[],auditTrail:[]};
const variants=[{name:'members',useHook:()=>useOrganizationMembers(),valid:{organizationId:'org-a',members:[member]},bad:{organizationId:'org-a',members:[{...member,roles:null}]}},{name:'member',useHook:()=>useMemberAuthorization('member-a'),valid:auth,bad:{...auth,membershipId:'another-member'}},{name:'roles',useHook:()=>useOrganizationRoles(),valid:[role],bad:[{...role,isSystem:'false'}]},{name:'catalog',useHook:()=>useAuthorizationCatalog(),valid:catalog,bad:{scopes:[],permissions:[{}]}},{name:'profile',useHook:()=>useOrganizationProfile(),valid:profile,bad:{...profile,counts:{...profile.counts,members:'0'}}}];
const wrapper=({children}:{children:ReactNode})=><QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}>{children}</QueryClientProvider>;
beforeEach(()=>vi.clearAllMocks());afterEach(cleanup);
for(const v of variants){const useHook=()=>{const q=v.useHook();return {isError:q.isError,isSuccess:q.isSuccess,data:q.data,error:q.error};};it.each([null,{},v.bad])(v.name+' rejects invalid authorization source %j',async data=>{m.rpc.mockResolvedValue({data,error:null});const h=renderHook(useHook,{wrapper});await waitFor(()=>expect(h.result.current.isError).toBe(true));expect(h.result.current.data).toBeUndefined();});it(v.name+' valid empty collections/zero counts and false permissions stay valid',async()=>{m.rpc.mockResolvedValue({data:v.valid,error:null});const h=renderHook(useHook,{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data).toEqual(v.valid);});}
it.each([{...auth,roleBindings:[{bindingId:'binding-a',roleId:'role-a',roleName:'A',scopeIds:[null]}]},{...auth,overrides:[{overrideId:'override-a',permissionKey:'jobs.view',effect:'BAD',scopeMode:'ORGANIZATION',reason:null,expiresAt:null,createdAt:'2026-09-30T00:00:00Z',scopeIds:[]}]},{...auth,effectiveKeys:[null]}])('nested authorization fields reject malformed values %j',async data=>{m.rpc.mockResolvedValue({data,error:null});const h=renderHook(()=>useMemberAuthorization('member-a'),{wrapper});await waitFor(()=>expect(h.result.current.isError).toBe(true));});
it('raw permission code remains in query error',async()=>{const error={code:'42501',message:'SQL_PRIVATE'};m.rpc.mockResolvedValue({data:null,error});const h=renderHook(()=>useOrganizationRoles(),{wrapper});await waitFor(()=>expect(h.result.current.isError).toBe(true));expect(h.result.current.error).toBe(error);});

const scope={scopeId:'scope-a',scopeType:'BUILDING',label:'Nhà A',buildingId:'building-a',areaId:null,cashbookId:null};
const nested=[{name:'members roles/scopes',useHook:()=>useOrganizationMembers(),data:{organizationId:'org-a',members:[{...member,roles:[{bindingId:'bind-a',roleId:'role-a',roleName:'A',isSystem:false,scopes:[{scopeId:scope.scopeId,scopeType:scope.scopeType,label:scope.label}]}]}]}},{name:'member bindings/overrides/possession',useHook:()=>useMemberAuthorization('member-a'),data:{...auth,roleBindings:[{bindingId:'bind-a',roleId:'role-a',roleName:'A',scopeIds:[scope.scopeId]}],overrides:[{overrideId:'override-a',permissionKey:'jobs.view',effect:'ALLOW',scopeMode:'SCOPED',reason:null,expiresAt:null,createdAt:profile.createdAt,scopeIds:[scope.scopeId]}],cashbooksHeld:[{cashbookId:'book-a',name:null,kind:'PRIMARY'}],effectiveKeys:['jobs.view']}},{name:'catalog scopes/permission definitions',useHook:()=>useAuthorizationCatalog(),data:{scopes:[scope],permissions:[{key:'jobs.view',resource:'jobs',action:'view',sensitivity:null,scopeKinds:['BUILDING'],requiredDimensions:[],requiresCashbookPossession:false}]}},{name:'profile invitations/audit nullable actor',useHook:()=>useOrganizationProfile(),data:{...profile,invitations:[{invitationId:'invite-a',email:'a@example.com',memberType:'STAFF',status:'PENDING',expiresAt:profile.createdAt,createdAt:profile.createdAt,roleName:null,isExpired:true}],auditTrail:[{eventId:'event-a',occurredAt:profile.createdAt,eventType:'MEMBER_UPDATED',resourceType:null,resourceId:null,reason:null,actorEmail:null,actorName:null,newState:{status:'ACTIVE'}}]}}];
for(const v of nested) it(v.name+' preserves valid nonempty SQL read payload',async()=>{m.rpc.mockResolvedValue({data:v.data,error:null});const h=renderHook(()=>{const q=v.useHook();return {isSuccess:q.isSuccess,data:q.data};},{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data).toEqual(v.data);});
