// @vitest-environment jsdom
import {cleanup,renderHook,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import type {ReactNode} from 'react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({reply:vi.fn(),rpc:vi.fn(),buildings:{} as Record<string,unknown>}));
vi.mock('@/hooks/useBuildings',()=>({useBuildings:()=>m.buildings}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc:m.rpc,from:()=>{const b={select:()=>b,eq:()=>b,not:()=>b,is:()=>b,order:()=>b,range:()=>b,then:(resolve:(v:unknown)=>unknown,reject:(v:unknown)=>unknown)=>Promise.resolve().then(()=>m.reply()).then(resolve,reject)};return b;}}}));
import {useMonthlyBuildingProfit,useProfitMonthly,useProfitAllocations,useShareholderDistributions,useProfitManagerAllocations,useManagerSalaryPayouts,useProfitCloseOrganizations,useProfitTotalGroupPeers,useProfitCloseState,useProfitClosePreview} from '../useShareholderProfit';
const org='org-a',month='2026-09-01',hash='a'.repeat(32);
const state={organization_id:org,period_month:month,can_lock:true,can_unlock:false,state_hash:hash,snapshot_ids:[],snapshot_count:0,locked_count:0,draft_count:0,real_building_count:1,active_real_snapshot_count:0,has_out_of_scope_snapshots:false,rows:[]};
const previewRow={building_id:'b-a',building_name:'Nhà A',building_source_hash:hash,source_revenue:'0',source_expense:0,computed_profit:-500,adjustment_amount:0,management_salary:0,distributable_profit:-500,shareholder_percent_total:100,shareholder_allocated_amount:0,unallocated_profit:-500,unallocated_disposition:null,unallocated_disposition_reason:null,shareholder_allocations:[],manager_allocations:[],current_status:null,current_is_stale:false,current_stale_reason:null,current_snapshot:null};
const preview={organization_id:org,period_month:month,source_hash:hash,buildings:[previewRow]};
const wrapper=({children}:{children:ReactNode})=><QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}>{children}</QueryClientProvider>;
const basic=[{name:'monthly',useHook:()=>useProfitMonthly()},{name:'share allocations',useHook:()=>useProfitAllocations()},{name:'share distributions',useHook:()=>useShareholderDistributions()},{name:'manager allocations',useHook:()=>useProfitManagerAllocations()},{name:'manager payouts',useHook:()=>useManagerSalaryPayouts()}];
beforeEach(()=>{vi.clearAllMocks();m.reply.mockResolvedValue({data:[],error:null});m.rpc.mockResolvedValue({data:null,error:null});m.buildings={data:[{id:'b-a',name:'Nhà A'}],status:'success',isLoading:false,isError:false,error:null,fetchStatus:'idle',refetch:vi.fn()};});afterEach(cleanup);
for(const v of basic){const useHook=()=>{const q=v.useHook();return {isError:q.isError,isSuccess:q.isSuccess,data:q.data};};it.each([null,[{}]])(v.name+' rejects missing/malformed source %j',async data=>{m.reply.mockResolvedValue({data:[],error:null}).mockResolvedValueOnce({data,error:null});const h=renderHook(useHook,{wrapper});await waitFor(()=>expect(h.result.current.isError).toBe(true));expect(h.result.current.data).toBeUndefined();});it(v.name+' confirmed empty remains empty',async()=>{const h=renderHook(useHook,{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data).toEqual([]);});}
it.each([null,{},[{}],[{building_id:'b-a',building_name:'Nhà A',is_virtual:false,revenue:'BAD',expense:0,net:0}]])('accrual malformed cannot pad buildings with false zero %j',async data=>{m.rpc.mockResolvedValue({data,error:null});const h=renderHook(()=>useMonthlyBuildingProfit(month,'2026-09-30'),{wrapper});await waitFor(()=>expect(h.result.current.isError).toBe(true));expect(h.result.current.data).toBeUndefined();});
it('accrual confirmed [] and valid buildings can pad actual zero',async()=>{m.rpc.mockResolvedValue({data:[],error:null});const h=renderHook(()=>useMonthlyBuildingProfit(month,'2026-09-30'),{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data).toEqual([{building_id:'b-a',building_name:'Nhà A',total_income:0,total_expense:0,net_profit:0}]);});
it('buildings source error participates in accrual query state',async()=>{const error={code:'42501',message:'SQL_PRIVATE'};m.buildings={...m.buildings,data:undefined,status:'error',isError:true,error};m.rpc.mockResolvedValue({data:[],error:null});const h=renderHook(()=>useMonthlyBuildingProfit(month,'2026-09-30'),{wrapper});await waitFor(()=>expect(h.result.current.isError).toBe(true));expect(h.result.current.error).toBe(error);expect(h.result.current.data).toBeUndefined();});
it.each([null,{}, {organizations:null},{organizations:[{}]},{organizations:[{organization_id:org,organization_name:'A',organization_slug:'a',can_lock:'false',can_unlock:false}]}])('organization scopes reject malformed envelope %j',async data=>{m.rpc.mockResolvedValue({data,error:null});const h=renderHook(useProfitCloseOrganizations,{wrapper});await waitFor(()=>expect(h.result.current.isError).toBe(true));});
it.each([null,[],{b:{peer_ids:null,peer_names:'A',rule_labels:'Rule'}},{b:{peer_ids:[null],peer_names:'A',rule_labels:'Rule'}}])('peers reject malformed map %j',async data=>{m.rpc.mockResolvedValue({data,error:null});const h=renderHook(()=>useProfitTotalGroupPeers(org),{wrapper});await waitFor(()=>expect(h.result.current.isError).toBe(true));});
it('empty peers is a confirmed empty object',async()=>{m.rpc.mockResolvedValue({data:{},error:null});const h=renderHook(()=>useProfitTotalGroupPeers(org),{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data).toEqual({});});
it.each([{...state,organization_id:'other'},{...state,period_month:'2026-08-01'},{...state,state_hash:''},{...state,snapshot_count:1},{...state,can_lock:'false'},{...state,rows:[{}]}])('state verifies hash/scope/counts/read fields %j',async data=>{m.rpc.mockResolvedValue({data,error:null});const h=renderHook(()=>useProfitCloseState(org,month),{wrapper});await waitFor(()=>expect(h.result.current.isError).toBe(true));});
it.each([{...preview,organization_id:'other'},{...preview,period_month:'2026-08-01'},{...preview,source_hash:''},{...preview,buildings:null},{...preview,buildings:[{...previewRow,computed_profit:null}]},{...preview,buildings:[{...previewRow,management_salary:'BAD'}]},{...preview,buildings:[{...previewRow,shareholder_allocations:null}]},{...preview,buildings:[{...previewRow,manager_allocations:[{}]}]},{...preview,buildings:[{...previewRow,current_snapshot:{}}]},{...preview,buildings:[{...previewRow,unallocated_disposition:'BAD'}]}])('preview refuses malformed financial truth %j',async data=>{m.rpc.mockResolvedValue({data,error:null});const h=renderHook(()=>useProfitClosePreview(org,month),{wrapper});await waitFor(()=>expect(h.result.current.isError).toBe(true));expect(h.result.current.data).toBeUndefined();});
it('preview valid V3 SQL shape preserves real negative profit and numeric strings',async()=>{m.rpc.mockResolvedValue({data:preview,error:null});const h=renderHook(()=>useProfitClosePreview(org,month),{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data?.rows[0]).toMatchObject({computed_profit:-500,revenue:0,unallocated_profit:-500,current_snapshot:null});});

const monthly={id:'snapshot-a',user_id:'actor-a',building_id:'b-a',period_month:month,computed_profit:-500,adjusted_profit:-500,management_salary:0,shareholder_percent_total:100,shareholder_allocated_amount:0,unallocated_profit:-500,unallocated_disposition:null,unallocated_disposition_reason:null,status:'LOCKED',note:null,locked_at:null,locked_by:null};
const pm={period_month:month,building_id:'b-a',status:'LOCKED'};
const populated=[{name:'monthly',useHook:()=>useProfitMonthly(),data:[monthly]},{name:'share allocation',useHook:()=>useProfitAllocations(),data:[{id:'alloc-a',user_id:'actor-a',profit_monthly_id:'snapshot-a',shareholder_id:'share-a',percent:100,amount:0,pm}]},{name:'manager allocation',useHook:()=>useProfitManagerAllocations(),data:[{id:'alloc-a',user_id:'actor-a',profit_monthly_id:'snapshot-a',manager_id:'manager-a',amount:0,pm}]},{name:'share payout',useHook:()=>useShareholderDistributions(),data:[{id:'payout-a',shareholder_id:'share-a',total_amount:50,voucher_date:'2026-09-30',name:'Chi A',account_id:null,building_id:'b-a'}]},{name:'manager payout',useHook:()=>useManagerSalaryPayouts(),data:[{id:'payout-a',profit_manager_id:'manager-a',total_amount:50,voucher_date:'2026-09-30',name:'Chi A',account_id:null,building_id:'b-a'}]}];
for(const v of populated)it(v.name+' full actual list source remains successful',async()=>{m.reply.mockResolvedValue({data:[],error:null}).mockResolvedValueOnce({data:v.data,error:null});const h=renderHook(()=>{const q=v.useHook();return {isSuccess:q.isSuccess,data:q.data};},{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data?.[0]).toHaveProperty('id',v.data[0].id);});
it('state nonempty rows verify actual snapshot IDs/counts and preserve loss',async()=>{const row={...monthly,building_name:'Nhà A',is_virtual:false,building_deleted:false,adjustment_amount:0,adjustment_reason:null,distributable_profit:-500,source_revenue:0,source_expense:500,source_hash:hash,is_stale:false,stale_reason:null,revision_number:1};const data={...state,snapshot_ids:[row.id],snapshot_count:1,locked_count:1,active_real_snapshot_count:1,rows:[row]};m.rpc.mockResolvedValue({data,error:null});const h=renderHook(()=>useProfitCloseState(org,month),{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data?.rows[0]).toMatchObject({id:row.id,computed_profit:-500,source_expense:500});});
it('preview existing locked snapshot derives only SQL-omitted distributable value',async()=>{const current={...monthly,adjustment_amount:0,adjustment_reason:null,source_hash:hash};m.rpc.mockResolvedValue({data:{...preview,buildings:[{...previewRow,current_status:'LOCKED',current_snapshot:current}]},error:null});const h=renderHook(()=>useProfitClosePreview(org,month),{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data?.is_locked).toBe(true);expect(h.result.current.data?.rows[0].current_snapshot?.distributable_profit).toBe(-500);});
it('scopes and peers nonempty canonical RPC source stay valid',async()=>{m.rpc.mockImplementation(async(name:string)=>({data:name.includes('scopes')?{organizations:[{organization_id:org,organization_name:'A',organization_slug:'a',can_lock:true,can_unlock:false}]}:{'b-a':{peer_ids:['b-b'],peer_names:'Nhà B',rule_labels:'Lương nhóm'}},error:null}));const peers=renderHook(()=>useProfitTotalGroupPeers(org),{wrapper});await waitFor(()=>expect(peers.result.current.isSuccess).toBe(true));expect(peers.result.current.data).toEqual({'b-a':{peerIds:['b-b'],peerNames:'Nhà B',ruleLabels:'Lương nhóm'}});});
