// @vitest-environment jsdom
import {act,cleanup,renderHook,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import type {ReactNode} from 'react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({rpc:vi.fn(),profile:vi.fn(),error:vi.fn()}));
vi.mock('@/lib/authSession',()=>({getSessionUserId:async()=>'actor-a'}));
vi.mock('sonner',()=>({toast:{error:m.error}}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc:m.rpc,from:()=>{const b={select:()=>b,eq:()=>b,single:m.profile};return b;}}}));
import {useSetUiPreference,useUiPreferences} from '../useUiPreferences';
let qc:QueryClient;const wrapper=({children}:{children:ReactNode})=><QueryClientProvider client={qc}>{children}</QueryClientProvider>;
beforeEach(()=>{vi.clearAllMocks();qc=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});qc.setQueryData(['ui-preferences'],{pd_hideStatCards:false,other:'kept'});m.profile.mockResolvedValue({data:{ui_preferences:{}},error:null});m.rpc.mockResolvedValue({data:{pd_hideStatCards:true,other:'kept'},error:null});});afterEach(()=>{cleanup();qc.clear();});
it('default owner emits one safe failure and rolls back optimistic key',async()=>{m.rpc.mockResolvedValue({data:null,error:{code:'42501',message:'PRIVATE_SQL'}});const h=renderHook(useSetUiPreference,{wrapper});await act(async()=>{await expect(h.result.current.mutateAsync({key:'pd_hideStatCards',value:true})).rejects.toBeDefined();});expect(m.error).toHaveBeenCalledOnce();expect(JSON.stringify(m.error.mock.calls)).not.toContain('PRIVATE_SQL');expect(qc.getQueryData(['ui-preferences'])).toMatchObject({pd_hideStatCards:false,other:'kept'});});
it('inline caller owns error once while hook still rolls back',async()=>{m.rpc.mockResolvedValue({data:null,error:{code:'42501',message:'PRIVATE_SQL'}});const h=renderHook(()=>useSetUiPreference({inlineError:true}),{wrapper});await act(async()=>{await expect(h.result.current.mutateAsync({key:'pd_hideStatCards',value:true})).rejects.toBeDefined();});expect(m.error).not.toHaveBeenCalled();expect(qc.getQueryData(['ui-preferences'])).toMatchObject({pd_hideStatCards:false,other:'kept'});});
it.each([null,[],true,{}, {pd_hideStatCards:false}])('missing/wrong returned preference is not success %j',async data=>{m.rpc.mockResolvedValue({data,error:null});const h=renderHook(useSetUiPreference,{wrapper});await act(async()=>{await expect(h.result.current.mutateAsync({key:'pd_hideStatCards',value:true})).rejects.toBeDefined();});expect(m.error).toHaveBeenCalledOnce();expect(qc.getQueryData(['ui-preferences'])).toMatchObject({pd_hideStatCards:false});});
it('JSONB object key order may change without failing exact nested receipt',async()=>{m.rpc.mockResolvedValue({data:{route:{mode:'manual',ids:['b1']}},error:null});const h=renderHook(useSetUiPreference,{wrapper});await act(async()=>{await expect(h.result.current.mutateAsync({key:'route',value:{ids:['b1'],mode:'manual'}})).resolves.toEqual({route:{mode:'manual',ids:['b1']}});});expect(m.error).not.toHaveBeenCalled();});
it.each([null,{}, {ui_preferences:null}, {ui_preferences:[]}, {ui_preferences:true}])('required preference source cannot become default object %j',async data=>{qc.removeQueries({queryKey:['ui-preferences']});m.profile.mockResolvedValue({data,error:null});const h=renderHook(useUiPreferences,{wrapper});await waitFor(()=>expect(h.result.current.isError).toBe(true));expect(h.result.current.data).toBeUndefined();});
it('true empty JSON object from SQL is legitimate source',async()=>{qc.removeQueries({queryKey:['ui-preferences']});const h=renderHook(useUiPreferences,{wrapper});await waitFor(()=>expect(h.result.current.isSuccess).toBe(true));expect(h.result.current.data).toEqual({});});
