// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
type QueryFixture = { data: unknown; status: string; fetchStatus: string; isLoading: boolean; isError: boolean; error: unknown; refetch: ReturnType<typeof vi.fn> };
const h=vi.hoisted(()=>({invoices:{} as QueryFixture,buildings:{} as QueryFixture,collectors:{} as QueryFixture}));
vi.mock('react-router-dom',()=>({useNavigate:()=>vi.fn(),useSearchParams:()=>[new URLSearchParams(),vi.fn()]}));
vi.mock('@/hooks/useBuildings',()=>({useBuildings:()=>h.buildings}));
vi.mock('@/hooks/useCollectionReport',()=>({useThuTienInvoices:()=>h.invoices}));
vi.mock('@/hooks/useInvoiceCollectors',()=>({useInvoiceCollectors:()=>h.collectors}));
vi.mock('@/hooks/useMyPermissions',()=>({useMyPermissions:()=>({data:{}})}));
vi.mock('@/lib/permissionPages',()=>({canUse:()=>true}));
vi.mock('@/hooks/useCashHandovers',()=>({useCashHandoverList:()=>({actionCount:0})}));
vi.mock('@/hooks/useCopilotPageContext',()=>({useCopilotPageContext:()=>{}}));
vi.mock('@/hooks/usePersistedState',async()=>{const {useState}=await import('react');return {usePersistedState:(_key:string,value:unknown)=>useState(value)};});
vi.mock('@/components/thu-tien/BuildingPills',()=>({BuildingPills:()=>null}));
vi.mock('@/components/thu-tien/CollectSummaryBar',()=>({CollectSummaryBar:()=> <div>Tổng tiền theo dữ liệu</div>}));
vi.mock('@/components/thu-tien/TimeFilter',()=>({TimeFilter:()=>null}));
vi.mock('@/components/thu-tien/DatePanel',()=>({DatePanel:()=>null}));
vi.mock('@/components/thu-tien/StatusFilter',()=>({StatusFilter:()=>null}));
vi.mock('@/components/thu-tien/RoomCellGrid',()=>({RoomCellGrid:()=> <div>Danh sách thu tiền</div>}));
vi.mock('@/components/thu-tien/CollectDrawer',()=>({CollectDrawer:()=>null}));
vi.mock('@/components/thu-tien/CollectionReport',()=>({CollectionReport:()=>null}));
vi.mock('@/components/thu-tien/HandoverSheet',()=>({HandoverSheet:()=>null}));
vi.mock('@/components/thu-tien/ManagePanel',()=>({ManagePanel:()=>null}));
vi.mock('@/components/thu-tien/room-lifecycle/RoomLifecycleSheet',()=>({RoomLifecycleSheet:()=>null}));
vi.mock('@/components/invoices/InvoiceRoundingReportButton',()=>({default:()=>null}));
import ThuTien from '../ThuTien';
const ready=(data:unknown)=>({data,isError:false,isLoading:false,status:'success',fetchStatus:'idle',error:null,refetch:vi.fn()});
beforeEach(()=>{h.invoices=ready([]);h.buildings=ready([]);h.collectors=ready({});});
afterEach(cleanup);
it.each(['invoices','buildings','collectors'] as const)('blocks incomplete totals when %s cannot load',async key=>{
 h.invoices=ready([{id:'invoice',building_id:'b',status:'APPROVED',payments:[],total_amount:100,paid_amount:0,remaining_amount:100}]);
 h[key]={...ready(undefined),isError:true,status:'error',error:new Error('Failed to fetch')};
 render(<ThuTien/>);
 expect(screen.queryByText('Tổng tiền theo dữ liệu')).toBeNull();
 expect(screen.queryByText('Danh sách thu tiền')).toBeNull();
 fireEvent.click(screen.getAllByRole('button',{name:'Tải lại'})[0]);
 await waitFor(()=>expect(h[key].refetch).toHaveBeenCalled());
});
it('renders a genuinely empty month without requiring the disabled collectors query',()=>{h.collectors={...ready(undefined),status:'pending'};render(<ThuTien/>);expect(screen.getByText('Danh sách thu tiền')).toBeTruthy();expect(screen.queryByRole('alert')).toBeNull();});
