// @vitest-environment jsdom
import {todayISO} from '@/lib/collect';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
const io=vi.hoisted(()=>({tenant:vi.fn(),deposit:vi.fn(),mark:vi.fn(),sourceError:false,retry:vi.fn(),from:vi.fn()}));
vi.mock('@/hooks/useLeads',()=>({useConvertLeadToDeposit:()=>({mutateAsync:io.mark,isPending:false})}));
vi.mock('@/hooks/useDeposits',()=>({useCreateDeposit:()=>({mutateAsync:io.deposit,isPending:false})}));
vi.mock('@/hooks/useTenants',()=>({useCreateTenant:()=>({mutateAsync:io.tenant,isPending:false}),useTenantsLegacy:()=>({data:[{id:'t1',full_name:'An',phone:'0900'}],isLoading:false,isError:io.sourceError,refetch:io.retry})}));
vi.mock('@/hooks/useRooms',()=>({useRooms:()=>({data:[{id:'r1',name:'P1'}],isLoading:false,isError:false,refetch:io.retry})}));
vi.mock('@/contexts/OrganizationContext',()=>({useOrganization:()=>({selectedOrganizationId:'org-a'})}));
vi.mock('@/lib/authSession',()=>({getSessionUser:async()=>({id:'actor'})}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{from:io.from}}));
vi.mock('sonner',()=>({toast:{error:vi.fn(),success:vi.fn()}}));
vi.mock('@/components/ui/select',()=>({Select:(p:{children:React.ReactNode;value:string;onValueChange:(value:string)=>void})=><select value={p.value ?? ''} onChange={e=>p.onValueChange(e.target.value)}><option value=""/>{p.children}</select>,SelectTrigger:()=>null,SelectValue:()=>null,SelectContent:(p:{children:React.ReactNode})=><>{p.children}</>,SelectItem:(p:{value:string;children:React.ReactNode})=><option value={p.value}>{p.children}</option>}));
vi.mock('@/components/ui/date-input',()=>({DateInput:(p:{value:string;onChange:(value:string)=>void;id?:string;name?:string})=><input id={p.id} name={p.name} value={p.value} onChange={e=>p.onChange(e.target.value)}/>}));
import {ConvertLeadDialog} from '../ConvertLeadDialog';
vi.stubGlobal('ResizeObserver',class {observe(){}unobserve(){}disconnect(){}});
beforeEach(()=>{vi.resetAllMocks();localStorage.clear();localStorage.setItem('ihomecrm.selectedOrganizationId','org-a');io.sourceError=false;io.from.mockImplementation((table:string)=>{const data=table==='tenants'?{id:'t1',organization_id:'org-a',deleted_at:null}:table==='leads'?{id:'l1',organization_id:'org-a',deleted_at:null,status:'B1_LEAD'}:null;const chain={select:vi.fn(),eq:vi.fn(),is:vi.fn(),maybeSingle:vi.fn().mockResolvedValue({data,error:null})};chain.select.mockReturnValue(chain);chain.eq.mockReturnValue(chain);chain.is.mockReturnValue(chain);return chain;});});
afterEach(()=>cleanup());
const lead={id:'l1',organization_id:'org-a',customer_name:'An',phone:'0900',room_id:'r1'} as never;
it('tenant source failure has an explicit retry and prevents conversion',()=>{io.sourceError=true;render(<ConvertLeadDialog open onOpenChange={vi.fn()} lead={lead}/>);expect(screen.getByRole('alert').textContent).toContain('Chưa tải đủ');fireEvent.click(screen.getByRole('button',{name:'Tạo đặt cọc'}));expect(io.deposit).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Tải lại dữ liệu'}));expect(io.retry).toHaveBeenCalled();});
it('unknown deposit keeps the tenant ID across full DOM remount and blocks another insert',async()=>{io.deposit.mockRejectedValue(new TypeError('Network request failed'));const props={open:true,onOpenChange:vi.fn(),lead};const view=render(<ConvertLeadDialog {...props}/>);await waitFor(()=>expect((screen.getByRole('button',{name:'Tạo đặt cọc'}) as HTMLButtonElement).disabled).toBe(false));fireEvent.change(screen.getAllByRole('combobox')[0],{target:{value:'t1'}});fireEvent.change(screen.getByLabelText('Giữ căn hộ đến *'),{target:{value:'2026-10-15'}});fireEvent.click(screen.getByRole('button',{name:'Tạo đặt cọc'}));await waitFor(()=>expect(io.deposit).toHaveBeenCalledTimes(1));view.unmount();render(<ConvertLeadDialog {...props}/>);await waitFor(()=>expect(screen.getByRole('alert').textContent).toContain('t1'));fireEvent.click(screen.getByRole('button',{name:'Tạo đặt cọc'}));expect(io.deposit).toHaveBeenCalledTimes(1);expect(io.tenant).not.toHaveBeenCalled();});

it('confirmed deposit reload hydrates its values and resumes only the rejected lead update',async()=>{
 const deposit={id:'d1',tenant_id:'t1',organization_id:'org-a',deleted_at:null,room_id:'r1',amount:0,deposit_date:todayISO(),hold_until:'2026-10-15',notes:null};
 const base=io.from.getMockImplementation()!;io.from.mockImplementation(table=>{if(table!=='deposits')return base(table);const chain={select:vi.fn(),eq:vi.fn(),is:vi.fn(),maybeSingle:vi.fn().mockResolvedValue({data:deposit,error:null})};chain.select.mockReturnValue(chain);chain.eq.mockReturnValue(chain);chain.is.mockReturnValue(chain);return chain;});
 io.deposit.mockResolvedValue(deposit);io.mark.mockRejectedValueOnce({code:'42501',message:'raw SQL'}).mockResolvedValue({lead:{id:'l1',organization_id:'org-a',deleted_at:null,status:'CONVERTED'}});const props={open:true,onOpenChange:vi.fn(),lead};const view=render(<ConvertLeadDialog {...props}/>);await waitFor(()=>expect((screen.getByRole('button',{name:'Tạo đặt cọc'}) as HTMLButtonElement).disabled).toBe(false));fireEvent.change(screen.getAllByRole('combobox')[0],{target:{value:'t1'}});fireEvent.change(screen.getByLabelText('Giữ căn hộ đến *'),{target:{value:'2026-10-15'}});fireEvent.click(screen.getByRole('button',{name:'Tạo đặt cọc'}));await waitFor(()=>expect(io.mark).toHaveBeenCalledTimes(1));await screen.findByRole('alert');view.unmount();render(<ConvertLeadDialog {...props}/>);await waitFor(()=>expect((screen.getByLabelText('Giữ căn hộ đến *') as HTMLInputElement).value).toBe('2026-10-15'));fireEvent.click(screen.getByRole('button',{name:'Hoàn tất chuyển đổi'}));await waitFor(()=>expect(io.mark).toHaveBeenCalledTimes(2));expect(io.deposit).toHaveBeenCalledTimes(1);expect(io.tenant).not.toHaveBeenCalled();expect(props.onOpenChange).toHaveBeenCalledWith(false);
});
