import {requireReadRows,requireReadRow,readRecord,readString,readNullableString,readNumber} from '@/lib/accountProfitReadModels';
import {PRICING_MODES} from './providerPolicy';
export interface ProviderCatalogRow {provider:string;enabled:boolean;label:string;models:Record<string,unknown>[];default_model:string|null;data_class:string;}
const models=(value:unknown)=>Array.isArray(value)&&value.every(model=>readRecord(model)&&readString(model.id)&&(model.label===undefined||typeof model.label==='string')&&(model.pricing_mode===undefined||PRICING_MODES.includes(model.pricing_mode as never))&&['input_price','output_price'].every(key=>model[key]===undefined||readNumber(model[key])&&model[key]>=0))&&new Set(value.map(model=>model.id)).size===value.length;
export const readProviders=(data:unknown)=>requireReadRows<ProviderCatalogRow>(data,row=>readString(row.provider)&&typeof row.enabled==='boolean'&&readString(row.label)&&models(row.models)&&readNullableString(row.default_model)&&['cloud','local_only'].includes(row.data_class as string));
export const readProviderPrices=(data:unknown)=>requireReadRows<{provider:string;models:Record<string,unknown>[]}>(data,row=>readString(row.provider)&&models(row.models));
export const readEntitlement=(data:unknown):{chat_enabled:boolean;ui_control_enabled:boolean}|null=>data===null?null:requireReadRow(data,row=>typeof row.chat_enabled==='boolean'&&typeof row.ui_control_enabled==='boolean');
export const readAdminEntitlements=(data:unknown)=>requireReadRows<{user_id:string;chat_enabled:boolean;ui_control_enabled:boolean}>(data,row=>readString(row.user_id)&&typeof row.chat_enabled==='boolean'&&typeof row.ui_control_enabled==='boolean');
export const readProfileBrief=(data:unknown)=>requireReadRows<{id:string;email:string|null;full_name:string|null}>(data,row=>readString(row.id)&&readNullableString(row.email)&&readNullableString(row.full_name));
export function readAdminSettings<T>(data:unknown):T|null {if(data===null)return null;return requireReadRow<T>(data,row=>['chat_enabled','ui_control_enabled'].every(key=>typeof row[key]==='boolean')&&['rate_per_min','daily_usd_cap_user','daily_usd_cap_tenant','daily_usd_cap_global','daily_tokens_cap_user','daily_tokens_cap_tenant'].every(key=>readNumber(row[key])&&row[key]>=0)&&['rate_per_min','daily_tokens_cap_user','daily_tokens_cap_tenant'].every(key=>Number.isSafeInteger(row[key])));}
