// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({queries:{} as Record<string,Record<string,unknown>>,retry:vi.fn()}));
vi.mock('@/hooks/usePublicRoomTokens',()=>({usePublicRoomTokens:()=>m.queries.tokens}));
vi.mock('@/hooks/usePublicRoomsAnalytics',()=>({usePraSummary:()=>m.queries.summary,usePraTimeseries:(_f:unknown,bucket:string)=>m.queries[bucket==='hour'?'hour':'day'],usePraTopRooms:()=>m.queries.rooms,usePraFunnel:()=>m.queries.funnel,usePraByToken:()=>m.queries.links,usePraErrors:()=>m.queries.timeline,usePraErrorGroups:()=>m.queries.errors}));
vi.mock('@/hooks/usePersistedState',()=>({usePersistedState:(_key:string,initial:unknown)=>[initial,vi.fn()],usePersistedDateRange:()=>[{from:new Date(2026,8,1),to:new Date(2026,8,30)},vi.fn()]}));
vi.mock('@/components/buildings/BuildingFilterSelect',()=>({default:()=>null}));
vi.mock('@/components/reports/ExportButtons',()=>({ExportButtons:()=> <button>Xuất file</button>}));
vi.mock('@/components/reports/DateRangePicker',()=>({DateRangePicker:()=> <button>Khoảng ngày</button>}));
vi.mock('@/components/ui/searchable-select',()=>({SearchableSelect:()=> <button>Bộ lọc link</button>}));
vi.mock('recharts',()=>Object.fromEntries(['Bar','BarChart','CartesianGrid','Cell','Legend','Line','LineChart','ResponsiveContainer','Tooltip','XAxis','YAxis'].map(name=>[name,({children}:{children:React.ReactNode})=><div>{children}</div>])));
vi.mock('@/components/finance-analysis/ChartCard',()=>({ChartCard:({title,children,empty}:{title:string;children:React.ReactNode;empty:boolean})=><div><h3>{title}</h3>{empty?<p>Không có dữ liệu thống kê.</p>:children}</div>}));
import AnalyticsTab from '../AnalyticsTab';
import MobileAnalytics from '../mobile/MobileAnalytics';
const query=(data:unknown)=>({data,status:'success',fetchStatus:'idle',isLoading:false,isError:false,error:null,refetch:m.retry,dataUpdatedAt:Date.now()});
const zeroSummary={total_sessions:0,total_views:0,room_opens:0,impressions:0,contact_clicks:0,favorites:0,deposit_dialogs:0,errors:0,avg_session_ms:0,unique_rooms_seen:0,errors_external:0,error_hits:0,error_groups:0,error_groups_external:0};
beforeEach(()=>{vi.clearAllMocks();m.queries={tokens:query([]),summary:query(zeroSummary),funnel:query({sessions:0,sessions_impression:0,sessions_opened_room:0,sessions_contacted:0})};for(const key of ['hour','day','rooms','links','timeline','errors'])m.queries[key]=query([]);});afterEach(cleanup);
function fail(key:string){m.queries[key]={...query(undefined),status:'error',isError:true,error:{code:'42501',message:'SQL_PRIVATE'}};}
it('desktop token-source failure hides all-link fallback and export',async()=>{fail('tokens');render(<AnalyticsTab/>);expect(screen.getByText('Chưa tải được danh sách link thống kê.')).toBeTruthy();expect(screen.queryByRole('button',{name:'Bộ lọc link'})).toBeNull();expect(screen.queryByText('Lượt xem trang')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Tải lại'}));await waitFor(()=>expect(m.retry).toHaveBeenCalled());});
it.each(['summary','day','funnel'])('desktop overview source %s fails without zero KPI',key=>{fail(key);render(<AnalyticsTab/>);expect(screen.getByText('Chưa tải được tổng quan thống kê.')).toBeTruthy();expect(screen.queryByText('Lượt xem trang')).toBeNull();expect(document.body.textContent).not.toContain('SQL_PRIVATE');});
it.each([{tab:'Phòng được xem nhiều',key:'rooms',label:'phòng được xem nhiều'},{tab:'Theo thời gian',key:'hour',label:'lưu lượng thống kê'},{tab:'Theo link',key:'links',label:'thống kê theo link'},{tab:'Lỗi',key:'errors',label:'nhóm lỗi thống kê'}])('desktop section $tab owns retry without empty data',({tab,key,label})=>{fail(key);render(<AnalyticsTab/>);fireEvent.mouseDown(screen.getByRole('tab',{name:tab}),{button:0,ctrlKey:false});expect(screen.getByText('Chưa tải được '+label+'.')).toBeTruthy();expect(screen.queryByText('Không có dữ liệu thống kê.')).toBeNull();});
it.each([{tab:'Tổng quan',key:'summary'},{tab:'Tổng quan',key:'funnel'},{tab:'Tổng quan',key:'day'},{tab:'Phòng xem nhiều',key:'rooms'},{tab:'Theo giờ',key:'hour'},{tab:'Theo link',key:'links'},{tab:'Lỗi',key:'errors'},{tab:'Lỗi',key:'summary'}])('mobile $tab source $key cannot become zero/empty',({tab,key})=>{fail(key);render(<MobileAnalytics/>);fireEvent.click(screen.getByRole('button',{name:tab}));expect(screen.getByText('Chưa tải được thống kê phòng.')).toBeTruthy();expect(screen.queryByText('Lượt xem trang')).toBeNull();expect(screen.queryByText(/Không có lỗi nào trong kỳ/)).toBeNull();expect(screen.queryByText('Chưa có dữ liệu.')).toBeNull();expect(screen.queryByText('Chưa đủ dữ liệu trong kỳ.')).toBeNull();});
it('mobile genuine zero summary still displays actual KPI',()=>{render(<MobileAnalytics/>);expect(screen.getByText('Lượt xem trang')).toBeTruthy();expect(screen.queryByText(/Chưa tải được/)).toBeNull();});
it('mobile cached network failure is visibly stale, not advertised fresh',()=>{m.queries.summary={...query(zeroSummary),status:'error',isError:true,error:new TypeError('Failed to fetch')};render(<MobileAnalytics/>);expect(screen.getByText(/Chưa cập nhật được thống kê phòng/)).toBeTruthy();expect(screen.getByText('Lượt xem trang')).toBeTruthy();});
