import type { DefaultTheme } from 'vitepress'

// Sidebar viết tay — tiêu đề có dấu không suy được từ tên file kebab-case.
// Quy tắc: mỗi trang .md mới trong docs/huong-dan-su-dung PHẢI thêm 1 dòng ở đây
// (script images:check sẽ cảnh báo trang mồ côi).
export const sidebar: DefaultTheme.Sidebar = [
  {
    text: '1. Bắt đầu',
    collapsed: false,
    items: [
      { text: 'Giới thiệu hệ thống', link: '/01-bat-dau/gioi-thieu/' },
      { text: 'Sandbox — Môi trường thực hành', link: '/01-bat-dau/sandbox/' },
      { text: 'Đăng nhập & khôi phục mật khẩu', link: '/01-bat-dau/dang-nhap/' },
      { text: 'Làm quen giao diện', link: '/01-bat-dau/lam-quen-giao-dien/' },
      { text: 'Khởi tạo dữ liệu — thứ tự chuẩn', link: '/01-bat-dau/khoi-tao-du-lieu/' },
      { text: 'Bước 1: Tạo khu vực & toà nhà', link: '/01-bat-dau/tao-toa-nha/' },
      { text: 'Bước 2: Tạo tầng & phòng', link: '/01-bat-dau/tao-tang-phong/' },
      { text: 'Bước 3: Dịch vụ & định mức', link: '/01-bat-dau/dich-vu-dinh-muc/' },
      { text: 'Bước 4: Công tơ điện nước', link: '/01-bat-dau/cong-to/' },
      { text: 'Bước 5: Sổ quỹ & loại thu chi', link: '/01-bat-dau/so-quy-loai-thu-chi/' },
      { text: 'Bước 6: Thêm nhân viên & phân quyền', link: '/01-bat-dau/them-nhan-vien/' },
      { text: 'Quy trình: Vòng đời khách thuê', link: '/01-bat-dau/quy-trinh-khach-thue/' },
      { text: 'Quy trình: Chu kỳ thu tiền hàng tháng', link: '/01-bat-dau/quy-trinh-thu-tien/' },
      { text: 'Quy trình: Bàn giao & đối soát', link: '/01-bat-dau/quy-trinh-ban-giao/' },
      { text: 'Quy trình: Thanh lý hợp đồng', link: '/01-bat-dau/quy-trinh-thanh-ly/' },
      { text: 'Quy trình: Chốt tháng tài chính', link: '/01-bat-dau/quy-trinh-chot-thang/' },
    ],
  },
  {
    text: '2. Theo dõi nhanh',
    collapsed: false,
    items: [
      { text: 'Bảng tin', link: '/02-theo-doi-nhanh/bang-tin/' },
      { text: 'Sơ đồ toà nhà', link: '/02-theo-doi-nhanh/so-do-toa-nha/' },
      { text: 'Thông báo', link: '/02-theo-doi-nhanh/thong-bao/' },
      { text: 'Việc của tôi', link: '/02-theo-doi-nhanh/viec-cua-toi/' },
    ],
  },
  {
    text: '3. Quản lý & Vận hành',
    collapsed: false,
    items: [
      {
        text: 'Danh mục dữ liệu',
        collapsed: true,
        items: [
          { text: 'Toà nhà', link: '/03-quan-ly-van-hanh/toa-nha/' },
          { text: 'Căn hộ / Phòng', link: '/03-quan-ly-van-hanh/can-ho-phong/' },
          { text: 'Dịch vụ', link: '/03-quan-ly-van-hanh/dich-vu/' },
          { text: 'Sale Phòng', link: '/03-quan-ly-van-hanh/sale-phong/' },
          { text: 'Trang phòng trống công khai', link: '/03-quan-ly-van-hanh/trang-phong-trong/' },
        ],
      },
      {
        text: 'Khách hàng',
        collapsed: true,
        items: [
          { text: 'Khách hẹn (Lead)', link: '/03-quan-ly-van-hanh/khach-hen/' },
          { text: 'Đặt cọc giữ chỗ', link: '/03-quan-ly-van-hanh/dat-coc/' },
          { text: 'Hoàn cọc, bỏ cọc', link: '/03-quan-ly-van-hanh/hoan-bo-coc/' },
          { text: 'Hợp đồng — danh sách & ký mới', link: '/03-quan-ly-van-hanh/hop-dong/' },
          { text: 'Chi tiết hợp đồng', link: '/03-quan-ly-van-hanh/hop-dong-chi-tiet/' },
          { text: 'Gia hạn & chuyển phòng', link: '/03-quan-ly-van-hanh/gia-han-chuyen-phong/' },
          { text: 'Thanh lý — Khách rời phòng', link: '/03-quan-ly-van-hanh/thanh-ly-move-out/' },
          { text: 'Thanh lý — Khách bỏ cọc', link: '/03-quan-ly-van-hanh/thanh-ly-forfeit/' },
          { text: 'Cư dân', link: '/03-quan-ly-van-hanh/cu-dan/' },
          { text: 'Hồ sơ & CT01', link: '/03-quan-ly-van-hanh/ho-so-ct01/' },
          { text: 'Phương tiện', link: '/03-quan-ly-van-hanh/phuong-tien/' },
        ],
      },
      {
        text: 'Tài chính',
        collapsed: true,
        items: [
          { text: 'Ghi chỉ số điện nước', link: '/03-quan-ly-van-hanh/ghi-chi-so/' },
          { text: 'Sinh hoá đơn hàng loạt', link: '/03-quan-ly-van-hanh/sinh-hoa-don/' },
          { text: 'Hoá đơn — danh sách & tạo lẻ', link: '/03-quan-ly-van-hanh/hoa-don/' },
          { text: 'Chi tiết & in hoá đơn', link: '/03-quan-ly-van-hanh/hoa-don-chi-tiet/' },
          { text: 'Thu tiền tại hoá đơn', link: '/03-quan-ly-van-hanh/thu-tien-hoa-don/' },
          { text: 'Thu tiền tại phòng (điện thoại)', link: '/03-quan-ly-van-hanh/thu-tien-mobile/' },
          { text: 'Thu chi — tạo phiếu', link: '/03-quan-ly-van-hanh/thu-chi/' },
          { text: 'Sổ quỹ', link: '/03-quan-ly-van-hanh/so-quy/' },
          { text: 'Bàn giao & đối soát', link: '/03-quan-ly-van-hanh/ban-giao-doi-soat/' },
          { text: 'Tiền thừa', link: '/03-quan-ly-van-hanh/tien-thua/' },
          { text: 'Chia lợi nhuận cổ đông', link: '/03-quan-ly-van-hanh/chia-loi-nhuan/' },
          { text: 'Bảng lương quản lý', link: '/03-quan-ly-van-hanh/bang-luong/' },
          { text: 'Lương của tôi', link: '/03-quan-ly-van-hanh/luong-cua-toi/' },
          { text: 'Ví thu chi cá nhân', link: '/03-quan-ly-van-hanh/vi-ca-nhan/' },
          { text: 'Chờ duyệt', link: '/03-quan-ly-van-hanh/cho-duyet/' },
        ],
      },
      {
        text: 'Vận hành',
        collapsed: true,
        items: [
          { text: 'Công việc & sự cố', link: '/03-quan-ly-van-hanh/cong-viec/' },
          { text: 'Kho vật tư', link: '/03-quan-ly-van-hanh/kho-vat-tu/' },
          { text: 'Tài sản', link: '/03-quan-ly-van-hanh/tai-san/' },
          { text: 'Chat Zalo — hội thoại', link: '/03-quan-ly-van-hanh/chat-zalo/' },
          { text: 'Chat Zalo — mẫu tin', link: '/03-quan-ly-van-hanh/zalo-mau-tin/' },
        ],
      },
    ],
  },
  {
    text: '4. Báo cáo',
    collapsed: true,
    items: [
      {
        text: 'Báo cáo bất động sản',
        collapsed: true,
        items: [
          { text: 'Tổng quan', link: '/04-bao-cao/hub-bds/' },
          { text: 'Phòng trống', link: '/04-bao-cao/phong-trong/' },
          { text: 'Hợp đồng sắp hết hạn', link: '/04-bao-cao/hd-sap-het-han/' },
          { text: 'Gia hạn & chuyển nhượng', link: '/04-bao-cao/gia-han-chuyen-nhuong/' },
          { text: 'Tỷ lệ lấp đầy', link: '/04-bao-cao/lap-day/' },
          { text: 'Khuyến mãi', link: '/04-bao-cao/khuyen-mai/' },
          { text: 'Cho thuê mới', link: '/04-bao-cao/cho-thue-moi/' },
          { text: 'Thanh lý / bỏ trả', link: '/04-bao-cao/thanh-ly/' },
          { text: 'Tỷ lệ chi phí', link: '/04-bao-cao/ty-le-chi-phi/' },
        ],
      },
      {
        text: 'Báo cáo tài chính',
        collapsed: true,
        items: [
          { text: 'Tổng quan', link: '/04-bao-cao/hub-tai-chinh/' },
          { text: 'Phân tích tài chính', link: '/04-bao-cao/phan-tich-tai-chinh/' },
          { text: 'Sổ quỹ theo ngày', link: '/04-bao-cao/so-quy-ngay/' },
          { text: 'Dòng tiền', link: '/04-bao-cao/dong-tien/' },
          { text: 'Lịch thanh toán', link: '/04-bao-cao/lich-thanh-toan/' },
          { text: 'Danh sách tiền cọc', link: '/04-bao-cao/danh-sach-coc/' },
          { text: 'Chu kỳ Thu → Bàn giao', link: '/04-bao-cao/thu-ban-giao/' },
        ],
      },
    ],
  },
  {
    text: '5. Cài đặt hệ thống',
    collapsed: true,
    items: [
      { text: 'Cài đặt chung', link: '/05-cai-dat/cai-dat-chung/' },
      {
        text: 'Danh mục khác',
        collapsed: true,
        items: [
          { text: 'Tổng quan', link: '/05-cai-dat/danh-muc-khac/' },
          { text: 'Tài khoản ngân hàng / sổ quỹ', link: '/05-cai-dat/tai-khoan-ngan-hang/' },
          { text: 'Gạch nợ tự động', link: '/05-cai-dat/gach-no-tu-dong/' },
          { text: 'Định mức dịch vụ', link: '/05-cai-dat/dinh-muc-dich-vu/' },
          { text: 'Nhà cung cấp', link: '/05-cai-dat/nha-cung-cap/' },
          { text: 'Kho (địa điểm lưu)', link: '/05-cai-dat/kho-cai-dat/' },
          { text: 'Loại tài sản', link: '/05-cai-dat/loai-tai-san/' },
          { text: 'Hotline', link: '/05-cai-dat/hotline/' },
          { text: 'Danh mục chung', link: '/05-cai-dat/danh-muc-chung/' },
          { text: 'Danh sách tầng', link: '/05-cai-dat/danh-sach-tang/' },
          { text: 'Loại công việc', link: '/05-cai-dat/loai-cong-viec/' },
        ],
      },
      { text: 'Mẫu biểu', link: '/05-cai-dat/mau-bieu/' },
      { text: 'Chữ ký', link: '/05-cai-dat/chu-ky/' },
      { text: 'Nhân viên & Đội ngũ', link: '/05-cai-dat/nhan-vien-doi-ngu/' },
      { text: 'Phân quyền theo trang', link: '/05-cai-dat/phan-quyen/' },
      { text: 'Quản trị người dùng', link: '/05-cai-dat/admin-users/' },
      { text: 'Trợ lý AI', link: '/05-cai-dat/tro-ly-ai/' },
    ],
  },
  {
    text: '6. Tài khoản',
    collapsed: true,
    items: [
      { text: 'Thông tin cá nhân', link: '/06-tai-khoan/thong-tin-ca-nhan/' },
      { text: 'Gói cước', link: '/06-tai-khoan/goi-cuoc/' },
    ],
  },
  {
    text: '7. Thông tin khác',
    collapsed: true,
    items: [
      { text: 'Thuật ngữ & bảng trạng thái', link: '/07-thong-tin-khac/thuat-ngu/' },
      { text: 'Bảng tra quyền nhanh', link: '/07-thong-tin-khac/tra-quyen-nhanh/' },
      { text: 'Câu hỏi thường gặp (FAQ)', link: '/07-thong-tin-khac/faq/' },
      { text: 'Ghi chú phiên bản', link: '/07-thong-tin-khac/ghi-chu-phien-ban/' },
      { text: 'Kênh hỗ trợ', link: '/07-thong-tin-khac/kenh-ho-tro/' },
    ],
  },
  {
    text: '8. Demo kế hoạch phát triển',
    collapsed: false,
    items: [
      { text: 'Phòng trình bày kế hoạch', link: '/08-ke-hoach-phat-trien/' },
      { text: 'Kế hoạch AI Copilot', link: '/08-ke-hoach-phat-trien/ai-copilot/' },
      { text: 'Mẫu kế hoạch dự án mới', link: '/08-ke-hoach-phat-trien/mau-plan/' },
    ],
  },
]
