// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
const io=vi.hoisted(()=>({save:vi.fn(),remove:vi.fn(),sourceError:false,retry:vi.fn()}));
vi.mock('@/hooks/useIncomeExpenseTypes',()=>({useCreateIncomeExpenseType:()=>({mutateAsync:io.save,isPending:false}),useUpdateIncomeExpenseType:()=>({mutateAsync:io.save,isPending:false}),useDeleteIncomeExpenseType:()=>({mutateAsync:io.remove,isPending:false}),useIncomeExpenseTypeCategories:()=>({data:[],isLoading:false,isError:io.sourceError,refetch:io.retry}),useIncomeExpenseTypes:()=>({data:[]})}));
vi.mock('@/hooks/useMyPermissions',()=>({useMyPermissions:()=>({data:{}})}));
vi.mock('@/lib/permissionPages',()=>({canUse:()=>false}));
vi.mock('../CategoryCombobox',()=>({default:(props:{value:string;onChange:(value:string)=>void})=><input aria-label="Nhóm" value={props.value} onChange={e=>props.onChange(e.target.value)}/>}));
import IncomeExpenseTypeForm from '../IncomeExpenseTypeForm';
import EditIncomeExpenseTypeDialog from '../EditIncomeExpenseTypeDialog';
import {FinancialWorkflowError} from '@/lib/financialWorkflow';
vi.stubGlobal('ResizeObserver',class {observe(){}unobserve(){}disconnect(){}});
afterEach(()=>{cleanup();vi.resetAllMocks();io.sourceError=false;});
it('create type unknown receipt keeps ID and prevents another save',async()=>{io.save.mockRejectedValue(new FinancialWorkflowError('Chưa xác nhận loại.','unknown',[{id:'type1',label:'Loại cần đối chiếu'}]));render(<IncomeExpenseTypeForm defaultType="expense"/>);fireEvent.change(screen.getByPlaceholderText('VD: Vệ sinh máy lạnh'),{target:{value:'Vệ sinh'}});fireEvent.change(screen.getByLabelText('Nhóm'),{target:{value:'Dịch vụ'}});fireEvent.click(screen.getByRole('button',{name:'Lưu'}));await waitFor(()=>expect(screen.getByRole('alert').textContent).toContain('type1'));fireEvent.click(screen.getByRole('button',{name:'Lưu'}));expect(io.save).toHaveBeenCalledTimes(1);});
it('delete failure keeps type confirmation open with ID and prevents replay',async()=>{io.remove.mockRejectedValue(new FinancialWorkflowError('Chưa xác nhận xoá.','unknown',[{id:'type1',label:'Loại cần đối chiếu'}]));render(<EditIncomeExpenseTypeDialog open onOpenChange={vi.fn()} type={{id:'type1',name:'Vệ sinh',type:'expense',category:'Dịch vụ'} as never}/>);fireEvent.click(screen.getByRole('button',{name:'Xoá'}));fireEvent.click(within(screen.getByRole('alertdialog')).getByRole('button',{name:'Xoá'}));await waitFor(()=>expect(within(screen.getByRole('alertdialog')).getByRole('alert').textContent).toContain('type1'));fireEvent.click(within(screen.getByRole('alertdialog')).getByRole('button',{name:'Xoá'}));expect(io.remove).toHaveBeenCalledTimes(1);});

const CATALOG_KEYS=['keywords','sort_order','quick_entry_hidden','archived_at','merged_into_id'];
it('edit without touching catalog fields sends no catalog columns (env without migration keeps working)',async()=>{io.save.mockResolvedValue({id:'type1'});render(<EditIncomeExpenseTypeDialog open onOpenChange={vi.fn()} type={{id:'type1',name:'Vệ sinh',type:'expense',category:'Dịch vụ'} as never}/>);fireEvent.change(screen.getByPlaceholderText('VD: Vệ sinh máy lạnh'),{target:{value:'Vệ sinh tòa'}});fireEvent.click(screen.getByRole('button',{name:'Lưu'}));await waitFor(()=>expect(io.save).toHaveBeenCalledTimes(1));const updates=(io.save.mock.calls[0]?.[0] as {updates:Record<string,unknown>}).updates;expect(updates.name).toBe('Vệ sinh tòa');for(const key of CATALOG_KEYS)expect(updates).not.toHaveProperty(key);});
it('archive switch on edit sends archived_at only',async()=>{io.save.mockResolvedValue({id:'type1'});render(<EditIncomeExpenseTypeDialog open onOpenChange={vi.fn()} type={{id:'type1',name:'Vệ sinh',type:'expense',category:'Dịch vụ'} as never}/>);fireEvent.click(screen.getByRole('switch',{name:'Lưu trữ hạng mục'}));fireEvent.click(screen.getByRole('button',{name:'Lưu'}));await waitFor(()=>expect(io.save).toHaveBeenCalledTimes(1));const updates=(io.save.mock.calls[0]?.[0] as {updates:Record<string,unknown>}).updates;expect(typeof updates.archived_at).toBe('string');expect(updates).not.toHaveProperty('merged_into_id');expect(updates).not.toHaveProperty('keywords');});
it('create form sends typed keywords as a trimmed list',async()=>{io.save.mockResolvedValue({id:'type2',name:'Điện lạnh'});render(<IncomeExpenseTypeForm defaultType="expense"/>);fireEvent.change(screen.getByPlaceholderText('VD: Vệ sinh máy lạnh'),{target:{value:'Điện lạnh'}});fireEvent.change(screen.getByLabelText('Nhóm'),{target:{value:'Sửa chữa'}});fireEvent.change(screen.getByLabelText('Cụm từ hay nói'),{target:{value:' bơm gas, ,xả giàn '}});fireEvent.click(screen.getByRole('button',{name:'Lưu'}));await waitFor(()=>expect(io.save).toHaveBeenCalledTimes(1));expect(io.save.mock.calls[0]?.[0]).toMatchObject({name:'Điện lạnh',keywords:['bơm gas','xả giàn']});expect(io.save.mock.calls[0]?.[0]).not.toHaveProperty('archived_at');});

it('category source failure stops type creation with a retry action',async()=>{io.sourceError=true;render(<IncomeExpenseTypeForm defaultType="expense"/>);expect(screen.getByRole('alert').textContent).toContain('Chưa tải đủ');fireEvent.click(screen.getByRole('button',{name:'Lưu'}));expect(io.save).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Tải lại dữ liệu'}));expect(io.retry).toHaveBeenCalledTimes(1);});
