// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({save:vi.fn(),data:{organizationId:'org-a',events:{E1:{enabled:true,min_amount:null as number|null}},quiet_start:21,quiet_end:7,available:true}}));
vi.mock('@/hooks/useMyPermissions',()=>({useMyPermissions:()=>({data:{}})}));vi.mock('@/lib/permissionPages',()=>({canUse:()=>true}));
vi.mock('@/hooks/useNotificationSettings',()=>({NotificationSettingsReceiptError:class extends Error{},NOTIFICATION_EVENT_KEYS:['E1'],NOTIFICATION_EVENT_LABELS:{E1:{title:'Phiếu chờ duyệt',desc:'Thử'}},useNotificationOrgConfig:()=>({data:m.data,isLoading:false,isError:false,refetch:vi.fn()}),useSetNotificationOrgConfig:()=>({mutate:m.save,isPending:false,error:null})}));
import NotificationOrgConfigCard from './NotificationOrgConfigCard';
beforeEach(()=>{vi.clearAllMocks();m.data={organizationId:'org-a',events:{E1:{enabled:true,min_amount:null}},quiet_start:21,quiet_end:7,available:true};});afterEach(cleanup);
it.each(['24','1.5','abc2'])('quiet hour raw invalid %s stays inline and focuses before manual writer',async value=>{render(<NotificationOrgConfigCard/>);const inputs=screen.getAllByRole('textbox') as HTMLInputElement[];const field=inputs[1];fireEvent.change(field,{target:{value}});fireEvent.click(screen.getByRole('button',{name:'Lưu cấu hình'}));await waitFor(()=>expect(document.activeElement).toBe(field));expect(field.value).toBe(value);expect(field.getAttribute('aria-invalid')).toBe('true');expect(m.save).not.toHaveBeenCalled();});
it('currency invalid raw cannot turn into null then save',async()=>{render(<NotificationOrgConfigCard/>);const field=screen.getAllByRole('textbox')[0] as HTMLInputElement;fireEvent.change(field,{target:{value:'abc2'}});fireEvent.click(screen.getByRole('button',{name:'Lưu cấu hình'}));await waitFor(()=>expect(document.activeElement).toBe(field));expect(field.value).toBe('abc2');expect(m.save).not.toHaveBeenCalled();});
it('refetched valid source keeps user draft and save sends actual source org ID',async()=>{const h=render(<NotificationOrgConfigCard/>);const field=screen.getAllByRole('textbox')[1] as HTMLInputElement;fireEvent.change(field,{target:{value:'5'}});m.data={...m.data,quiet_start:22};h.rerender(<NotificationOrgConfigCard/>);expect(field.value).toBe('5');fireEvent.click(screen.getByRole('button',{name:'Lưu cấu hình'}));expect(m.save).toHaveBeenCalledWith(expect.objectContaining({organizationId:'org-a',quiet_start:5}),expect.any(Object));});
