import { describe, expect, it, vi } from "vitest";

import {
  FORWARD_CORRECTIVE_INSTRUCTION,
  OPENCLAW_MIGRATIONS,
  computeOpenClawMigrationManifest,
  runSchemaDrift,
} from "../test-openclaw-migrations.mjs";
import { EXPECTED_PROJECT_REF } from "../test-openclaw-sql.mjs";

const REVIEWED_SHA = "e".repeat(40);
const REVIEWED_TYPES = [
  "// This file is automatically generated. Do not edit it directly.",
  "export type Json = string",
  "export type Database = {}",
  "",
].join("\n");

function buildFixture() {
  const manifest = computeOpenClawMigrationManifest(
    OPENCLAW_MIGRATIONS.map((file) => ({
      file,
      bytes: Buffer.from(`reviewed:${file}\n`),
    })),
  );
  const functions = [
    {
      signature: "app_private.openclaw_example()",
      owner: "openclaw_function_owner",
      securityDefiner: true,
      configuration: 'search_path=""',
      grantee: "openclaw_runtime_executor",
      privilegeType: "EXECUTE",
      isGrantable: false,
    },
  ];
  const snapshot = {
    migrations: manifest.entries.map((entry, index) => ({
      order: index + 1,
      version: entry.version,
      fileName: entry.file,
      migrationName: entry.name,
      recordedName: entry.name,
      statementCount: 1,
      recordedSha256: entry.sha256,
    })),
    unsafeViews: [],
    functions,
    activationColumns: [
      "feature_enabled",
      "first_contact_enabled",
      "limited_auto_reply_enabled",
      "proactive_enabled",
      "sales_groups_enabled",
    ].map((columnName) => ({
      columnName,
      columnDefault: "false",
      isNullable: "NO",
    })),
    enabledRowCount: 0,
  };
  return { manifest, functions, snapshot };
}

async function captureDriftFailure({
  mutateBefore,
  mutateAfter = mutateBefore,
  remoteTypes = REVIEWED_TYPES,
  reviewedTypes = REVIEWED_TYPES,
}) {
  const { manifest, functions, snapshot } = buildFixture();
  const before = structuredClone(snapshot);
  const after = structuredClone(snapshot);
  mutateBefore?.(before);
  mutateAfter?.(after);
  let thrown;
  try {
    await runSchemaDrift(
      { projectRef: EXPECTED_PROJECT_REF, reviewedSha: REVIEWED_SHA },
      {
        loadReviewedMigrationManifest: vi.fn(async () => manifest),
        buildExpectedFunctionSnapshot: vi.fn(async () => functions),
        requestRemoteSnapshot: vi
          .fn()
          .mockResolvedValueOnce(before)
          .mockResolvedValueOnce(after),
        generateRemoteTypes: vi.fn(async () => remoteTypes),
        readReviewedTypes: vi.fn(async () => reviewedTypes),
      },
    );
  } catch (error) {
    thrown = error;
  }
  expect(thrown).toBeInstanceOf(Error);
  expect(thrown.message).toContain(FORWARD_CORRECTIVE_INSTRUCTION);
  return thrown.message;
}

describe("OpenClaw schema-drift negative dimensions", () => {
  it.each([
    ["ledger cardinality", (snapshot) => snapshot.migrations.pop(), /cardinality/i],
    [
      "recorded migration name",
      (snapshot) => { snapshot.migrations[0].recordedName = "wrong_name"; },
      /migration identity mismatch/i,
    ],
    [
      "canonical migration version",
      (snapshot) => { snapshot.migrations[0].version = "20260727999999"; },
      /migration identity mismatch/i,
    ],
    [
      "canonical migration file name",
      (snapshot) => { snapshot.migrations[0].fileName = "wrong.sql"; },
      /migration identity mismatch/i,
    ],
    [
      "canonical migration logical name",
      (snapshot) => { snapshot.migrations[0].migrationName = "wrong_name"; },
      /migration identity mismatch/i,
    ],
    [
      "recorded migration hash",
      (snapshot) => { snapshot.migrations[0].recordedSha256 = "0".repeat(64); },
      /migration identity mismatch/i,
    ],
    [
      "recorded statement cardinality",
      (snapshot) => { snapshot.migrations[0].statementCount = 2; },
      /migration identity mismatch/i,
    ],
  ])("rejects %s drift", async (_name, mutate, expectedReason) => {
    const message = await captureDriftFailure({ mutateBefore: mutate });
    expect(message).toMatch(expectedReason);
  });

  it("rejects any public view without security_invoker=true", async () => {
    const message = await captureDriftFailure({
      mutateBefore: (snapshot) => snapshot.unsafeViews.push("openclaw_unsafe_view"),
    });
    expect(message).toMatch(/security_invoker/i);
  });

  it.each([
    ["owner", (row) => { row.owner = "postgres"; }],
    ["search_path", (row) => { row.configuration = ""; }],
    ["grant", (row) => { row.grantee = "PUBLIC"; }],
    ["grant option", (row) => { row.isGrantable = true; }],
  ])("rejects function %s drift", async (_name, mutate) => {
    const message = await captureDriftFailure({
      mutateBefore: (snapshot) => mutate(snapshot.functions[0]),
    });
    expect(message).toMatch(/function owner, search_path, or grant/i);
  });

  it.each([
    [
      "missing activation column",
      (snapshot) => snapshot.activationColumns.pop(),
      /activation-default column cardinality/i,
    ],
    [
      "nullable activation column",
      (snapshot) => { snapshot.activationColumns[0].isNullable = "YES"; },
      /activation default drifted/i,
    ],
    [
      "enabled-by-default activation column",
      (snapshot) => { snapshot.activationColumns[0].columnDefault = "true"; },
      /activation default drifted/i,
    ],
    [
      "enabled live row",
      (snapshot) => { snapshot.enabledRowCount = 1; },
      /activation flag is already enabled/i,
    ],
  ])("rejects %s", async (_name, mutate, expectedReason) => {
    const message = await captureDriftFailure({ mutateBefore: mutate });
    expect(message).toMatch(expectedReason);
  });

  it("rejects generated Supabase type drift", async () => {
    const message = await captureDriftFailure({
      remoteTypes: `${REVIEWED_TYPES}export type Drift = true\n`,
    });
    expect(message).toMatch(/generated Supabase type shape/i);
  });

  it("rejects catalog changes between the two read-only snapshots", async () => {
    const message = await captureDriftFailure({
      mutateBefore: undefined,
      mutateAfter: (snapshot) => { snapshot.enabledRowCount = 1; },
    });
    expect(message).toMatch(/changed while drift verification was running/i);
  });
});
