import { useState, useMemo, useCallback, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import MainLayout from '@/components/layout/MainLayout';
import { usePagination, calculatePaginationInfo } from '@/hooks/usePagination';
import { DataTablePagination } from '@/components/ui/data-table-pagination';
import { Receipt } from 'lucide-react';
import EmptyState from '@/components/ui/EmptyState';
import { useToast } from '@/hooks/use-toast';
import {
  useInvoices,
  useApproveInvoice,
  useDeleteInvoice,
  useBulkApproveInvoices,
  useBulkDeleteInvoices,
  useUnapproveInvoice,
  useCheckOverdueInvoices,
} from '@/hooks/useInvoices';
import type { InvoiceWithRelations, InvoiceFilters } from '@/types/invoice';

import InvoiceStatsSummary from '@/components/invoices/InvoiceStatsSummary';
import InvoiceListFilters from '@/components/invoices/InvoiceListFilters';
import InvoiceListToolbar from '@/components/invoices/InvoiceListToolbar';
import InvoiceListTable from '@/components/invoices/InvoiceListTable';
import GenerateInvoiceDialog from '@/components/invoices/GenerateInvoiceDialog';
import AutoGenerateInvoicesDialog from '@/components/invoices/AutoGenerateInvoicesDialog';
import RecordPaymentDialog from '@/components/invoices/RecordPaymentDialog';
import EditInvoiceDialog from '@/components/invoices/EditInvoiceDialog';
import ImportExcelDialog from '@/components/invoices/ImportExcelDialog';

const InvoicesPage = () => {
  const navigate = useNavigate();
  const { toast } = useToast();

  // Filters
  const [filters, setFilters] = useState<InvoiceFilters>({});

  // Search
  const [searchQuery, setSearchQuery] = useState('');

  // Pagination
  const { page, pageSize, setPage, setPageSize } = usePagination(20);

  // Selection
  const [selectedIds, setSelectedIds] = useState<string[]>([]);

  // Dialog states
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [autoGenerateDialogOpen, setAutoGenerateDialogOpen] = useState(false);
  const [importDialogOpen, setImportDialogOpen] = useState(false);
  const [paymentDialogOpen, setPaymentDialogOpen] = useState(false);
  const [editDialogOpen, setEditDialogOpen] = useState(false);
  const [selectedInvoice, setSelectedInvoice] = useState<InvoiceWithRelations | null>(null);

  // Merge search into filters
  const effectiveFilters = useMemo(
    () => ({ ...filters, search: searchQuery || undefined }),
    [filters, searchQuery],
  );

  // Data fetching
  const { data: invoicesData, isLoading } = useInvoices(effectiveFilters, { page, pageSize });
  const invoices = invoicesData?.data ?? [];
  const totalCount = invoicesData?.count ?? 0;

  // Mutations
  const approveMutation = useApproveInvoice();
  const deleteMutation = useDeleteInvoice();
  const unapproveInvoice = useUnapproveInvoice();
  const bulkApproveMutation = useBulkApproveInvoices();
  const bulkDeleteMutation = useBulkDeleteInvoices();

  // Check and update overdue invoices on mount
  const checkOverdueMutation = useCheckOverdueInvoices();
  const overdueCheckedRef = useRef(false);
  useEffect(() => {
    if (!overdueCheckedRef.current) {
      overdueCheckedRef.current = true;
      checkOverdueMutation.mutate();
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // Pagination info
  const paginationInfo = useMemo(
    () => calculatePaginationInfo(page, pageSize, totalCount),
    [page, pageSize, totalCount],
  );

  // Statistics filters (derived from invoice filters)
  const statsFilters = useMemo(
    () => ({
      building_id: filters.building_id,
      room_id: filters.room_id,
      status: filters.status,
      start_date: filters.date_range?.start,
      end_date: filters.date_range?.end,
    }),
    [filters],
  );

  // Handlers
  const handleFiltersChange = useCallback(
    (newFilters: InvoiceFilters) => {
      setFilters(newFilters);
      setPage(1);
      setSelectedIds([]);
    },
    [setPage],
  );

  const handleSearch = useCallback(
    (query: string) => {
      setSearchQuery(query);
      setPage(1);
    },
    [setPage],
  );

  const handleToggleSelect = useCallback((id: string) => {
    setSelectedIds((prev) =>
      prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id],
    );
  }, []);

  const handleToggleSelectAll = useCallback(() => {
    const draftIds = invoices.filter((inv) => inv.status === 'DRAFT').map((inv) => inv.id);
    setSelectedIds((prev) => (prev.length === draftIds.length ? [] : draftIds));
  }, [invoices]);

  const handleApprove = useCallback(
    (invoice: InvoiceWithRelations) => {
      if (confirm('Bạn đang thực hiện thao tác DUYỆT hoá đơn. Bạn có chắc chắn muốn xác nhận duyệt này không?')) {
        approveMutation.mutate(invoice.id);
      }
    },
    [approveMutation],
  );

  const handleEdit = useCallback((invoice: InvoiceWithRelations) => {
    setSelectedInvoice(invoice);
    setEditDialogOpen(true);
  }, []);

  const handleDelete = useCallback(
    (invoice: InvoiceWithRelations) => {
      if (confirm('Bạn có chắc chắn muốn xoá hoá đơn này?')) {
        deleteMutation.mutate(invoice.id);
      }
    },
    [deleteMutation],
  );

  const handleRecordPayment = useCallback((invoice: InvoiceWithRelations) => {
    setSelectedInvoice(invoice);
    setPaymentDialogOpen(true);
  }, []);

  const handleUnapprove = useCallback(
    (invoice: InvoiceWithRelations) => {
      if (confirm('Bạn có chắc chắn muốn bỏ duyệt hoá đơn này?')) {
        unapproveInvoice.mutate(invoice.id);
      }
    },
    [unapproveInvoice],
  );

  const handleViewDetail = useCallback(
    (invoice: InvoiceWithRelations) => {
      navigate(`/invoices/${invoice.id}`);
    },
    [navigate],
  );

  // TODO: Placeholder handlers for features to be implemented later
  const handlePublish = useCallback(
    (_invoice: InvoiceWithRelations) => {
      console.log('TODO: Phát hành hoá đơn');
      toast({ title: 'Tính năng đang phát triển', description: 'Phát hành hoá đơn' });
    },
    [toast],
  );

  const handleViewHistory = useCallback(
    (_invoice: InvoiceWithRelations) => {
      console.log('TODO: Lịch sử chỉnh sửa');
      toast({ title: 'Tính năng đang phát triển', description: 'Lịch sử chỉnh sửa' });
    },
    [toast],
  );

  const handleBulkApprove = useCallback(() => {
    if (selectedIds.length === 0) return;
    if (confirm(`Bạn có chắc chắn muốn duyệt ${selectedIds.length} hoá đơn đã chọn?`)) {
      bulkApproveMutation.mutate(selectedIds, {
        onSuccess: () => setSelectedIds([]),
      });
    }
  }, [selectedIds, bulkApproveMutation]);

  const handleBulkDelete = useCallback(() => {
    if (selectedIds.length === 0) return;
    if (confirm(`Bạn có chắc chắn muốn xoá ${selectedIds.length} hoá đơn đã chọn?`)) {
      bulkDeleteMutation.mutate(selectedIds, {
        onSuccess: () => setSelectedIds([]),
      });
    }
  }, [selectedIds, bulkDeleteMutation]);

  return (
    <MainLayout
      title="Quản lý Hoá đơn"
      subtitle="Quản lý hoá đơn và thanh toán"
      icon={Receipt}
    >
      {/* Statistics */}
      <InvoiceStatsSummary filters={statsFilters} />

      {/* Filters */}
      <InvoiceListFilters filters={filters} onFiltersChange={handleFiltersChange} />

      {/* Toolbar */}
      <InvoiceListToolbar
        selectedCount={selectedIds.length}
        searchQuery={searchQuery}
        onSearch={handleSearch}
        onAdd={() => setCreateDialogOpen(true)}
        onImport={() => setImportDialogOpen(true)}
        onAutoGenerate={() => setAutoGenerateDialogOpen(true)}
        onBulkApprove={handleBulkApprove}
        onBulkDelete={handleBulkDelete}
      />

      {/* Table */}
      <div className="bg-white rounded-lg border">
        {isLoading ? (
          <div className="p-8 text-center text-muted-foreground">Đang tải dữ liệu...</div>
        ) : invoices.length === 0 ? (
          <EmptyState
            icon={Receipt}
            title="Chưa có hoá đơn nào"
            description="Hãy tạo hoá đơn đầu tiên để bắt đầu quản lý"
          />
        ) : (
          <>
            <InvoiceListTable
              invoices={invoices}
              selectedIds={selectedIds}
              onToggleSelect={handleToggleSelect}
              onToggleSelectAll={handleToggleSelectAll}
              onApprove={handleApprove}
              onEdit={handleEdit}
              onDelete={handleDelete}
              onRecordPayment={handleRecordPayment}
              onUnapprove={handleUnapprove}
              onViewDetail={handleViewDetail}
              onPublish={handlePublish}
              onViewHistory={handleViewHistory}
            />
            <DataTablePagination
              paginationInfo={paginationInfo}
              onPageChange={setPage}
              onPageSizeChange={setPageSize}
              showPageSizeSelector
              showItemCount
            />
          </>
        )}
      </div>

      {/* Dialogs */}
      <GenerateInvoiceDialog
        open={createDialogOpen}
        onOpenChange={setCreateDialogOpen}
      />

      <AutoGenerateInvoicesDialog
        open={autoGenerateDialogOpen}
        onOpenChange={setAutoGenerateDialogOpen}
      />

      {selectedInvoice && (
        <RecordPaymentDialog
          open={paymentDialogOpen}
          onOpenChange={setPaymentDialogOpen}
          invoice={selectedInvoice}
        />
      )}

      {selectedInvoice && (
        <EditInvoiceDialog
          open={editDialogOpen}
          onOpenChange={setEditDialogOpen}
          invoice={selectedInvoice}
        />
      )}

      <ImportExcelDialog
        open={importDialogOpen}
        onOpenChange={setImportDialogOpen}
      />
    </MainLayout>
  );
};

export default InvoicesPage;
