// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
const io=vi.hoisted(()=>({save:vi.fn(),retry:vi.fn(),sourceError:false}));
vi.mock('@/hooks/useMaterials',()=>({useCreateMaterial:()=>({mutateAsync:io.save,isPending:false}),useUpdateMaterial:()=>({mutateAsync:io.save,isPending:false})}));
vi.mock('@/hooks/useMaterialCategories',()=>({useMaterialCategories:()=>({data:[],isError:io.sourceError,isLoading:false,refetch:io.retry}),useCreateMaterialCategory:()=>({mutateAsync:io.save,isPending:false}),useUpdateMaterialCategory:()=>({mutateAsync:io.save,isPending:false})}));
import MaterialFormDialog from '../MaterialFormDialog';import MaterialCategoryFormDialog from '../MaterialCategoryFormDialog';import {FinancialWorkflowError} from '@/lib/financialWorkflow';
afterEach(()=>{cleanup();vi.resetAllMocks();io.sourceError=false;});
it.each([[MaterialFormDialog,{id:'m1',name:'Đèn',unit:'cái',reorder_level:0}],[MaterialCategoryFormDialog,{id:'m1',name:'Đèn'}]])('unknown material/category preserves edited draft and target ID across reopening/refresh',async(Component,editing)=>{io.save.mockRejectedValue(new FinancialWorkflowError('Chưa xác nhận bản ghi.','unknown',[{id:'m1',label:'Bản ghi cần đối chiếu'}]));const props={open:true,onOpenChange:vi.fn(),editing:editing as never};const view=render(<Component {...props}/>);fireEvent.change(screen.getByDisplayValue('Đèn'),{target:{value:'Đèn mới'}});fireEvent.click(screen.getByRole('button',{name:'Cập nhật'}));await waitFor(()=>expect(screen.getByRole('alert').textContent).toContain('m1'));view.rerender(<Component {...props} open={false}/>);view.rerender(<Component {...props} editing={{...editing,name:'Server'} as never}/>);expect(screen.getByDisplayValue('Đèn mới')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Cập nhật'}));expect(io.save).toHaveBeenCalledTimes(1);});
it('material category source error blocks writing and offers source retry',()=>{io.sourceError=true;render(<MaterialFormDialog open onOpenChange={vi.fn()} editing={{id:'m1',name:'Đèn',unit:'cái',reorder_level:0} as never}/>);expect(screen.getByRole('alert').textContent).toContain('Chưa tải');fireEvent.click(screen.getByRole('button',{name:'Cập nhật'}));expect(io.save).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Tải lại danh mục'}));expect(io.retry).toHaveBeenCalled();});
