-- =============================================
-- Batch F: Drop legacy policies (giữ *_rbac, *_admin_all, *_super_admin_all, *_shared)
-- =============================================
-- Sau phase 1-5 + batch A, RBAC đã cover toàn bộ. PostgreSQL OR mọi policy match;
-- legacy policy chỉ "dư". Drop để gọn schema và rõ nguồn quyền.
--
-- GIỮ:
--   *_rbac           — chính sách RBAC mới (batch B-A của refactor)
--   *_admin_all      — admin bypass
--   *_super_admin_all — super_admin bypass
--   *_shared         — cơ chế shared_users của sổ quỹ (income_expenses_*_shared,
--                      account_shared_users_*)
--
-- DROP: tất cả policy còn lại trên 63 bảng đã có RBAC.
-- (Không động policies trên các bảng KHÔNG có RBAC như profiles, accounts,
-- account_shared_users, roles, super_admins, staff_assignments, user_roles,
-- user_subscriptions, notifications, settings, code_sequences, ai_*, departments.)
-- =============================================

DROP POLICY IF EXISTS "Users can delete own areas" ON public.areas;
DROP POLICY IF EXISTS "areas_staff_delete" ON public.areas;
DROP POLICY IF EXISTS "Users can insert own areas" ON public.areas;
DROP POLICY IF EXISTS "areas_staff_insert" ON public.areas;
DROP POLICY IF EXISTS "Users can view own areas" ON public.areas;
DROP POLICY IF EXISTS "areas_select_staff" ON public.areas;
DROP POLICY IF EXISTS "Users can update own areas" ON public.areas;
DROP POLICY IF EXISTS "areas_staff_update" ON public.areas;
DROP POLICY IF EXISTS "Users can manage own asset categories" ON public.asset_categories;
DROP POLICY IF EXISTS "asset_categories_staff_delete" ON public.asset_categories;
DROP POLICY IF EXISTS "asset_categories_staff_insert" ON public.asset_categories;
DROP POLICY IF EXISTS "asset_categories_select_staff" ON public.asset_categories;
DROP POLICY IF EXISTS "asset_categories_staff_update" ON public.asset_categories;
DROP POLICY IF EXISTS "Users can manage own asset handovers" ON public.asset_handovers;
DROP POLICY IF EXISTS "asset_handovers_staff_delete" ON public.asset_handovers;
DROP POLICY IF EXISTS "asset_handovers_staff_insert" ON public.asset_handovers;
DROP POLICY IF EXISTS "asset_handovers_select_staff" ON public.asset_handovers;
DROP POLICY IF EXISTS "asset_handovers_staff_update" ON public.asset_handovers;
DROP POLICY IF EXISTS "Users can manage own asset maintenance" ON public.asset_maintenance;
DROP POLICY IF EXISTS "asset_maintenance_staff_delete" ON public.asset_maintenance;
DROP POLICY IF EXISTS "asset_maintenance_staff_insert" ON public.asset_maintenance;
DROP POLICY IF EXISTS "asset_maintenance_select_staff" ON public.asset_maintenance;
DROP POLICY IF EXISTS "asset_maintenance_staff_update" ON public.asset_maintenance;
DROP POLICY IF EXISTS "Users can manage own asset movements" ON public.asset_movements;
DROP POLICY IF EXISTS "asset_movements_staff_delete" ON public.asset_movements;
DROP POLICY IF EXISTS "asset_movements_staff_insert" ON public.asset_movements;
DROP POLICY IF EXISTS "asset_movements_select_staff" ON public.asset_movements;
DROP POLICY IF EXISTS "asset_movements_staff_update" ON public.asset_movements;
DROP POLICY IF EXISTS "asset_warehouses_delete" ON public.asset_warehouses;
DROP POLICY IF EXISTS "asset_warehouses_staff_delete" ON public.asset_warehouses;
DROP POLICY IF EXISTS "asset_warehouses_insert" ON public.asset_warehouses;
DROP POLICY IF EXISTS "asset_warehouses_staff_insert" ON public.asset_warehouses;
DROP POLICY IF EXISTS "asset_warehouses_select" ON public.asset_warehouses;
DROP POLICY IF EXISTS "asset_warehouses_select_staff" ON public.asset_warehouses;
DROP POLICY IF EXISTS "asset_warehouses_staff_update" ON public.asset_warehouses;
DROP POLICY IF EXISTS "asset_warehouses_update" ON public.asset_warehouses;
DROP POLICY IF EXISTS "Users can manage own assets" ON public.assets;
DROP POLICY IF EXISTS "assets_staff_delete" ON public.assets;
DROP POLICY IF EXISTS "assets_staff_insert" ON public.assets;
DROP POLICY IF EXISTS "Users can view own assets" ON public.assets;
DROP POLICY IF EXISTS "assets_select_staff" ON public.assets;
DROP POLICY IF EXISTS "assets_staff_update" ON public.assets;
DROP POLICY IF EXISTS "auto_debt_config_delete" ON public.auto_debt_config;
DROP POLICY IF EXISTS "auto_debt_config_staff_delete" ON public.auto_debt_config;
DROP POLICY IF EXISTS "auto_debt_config_insert" ON public.auto_debt_config;
DROP POLICY IF EXISTS "auto_debt_config_staff_insert" ON public.auto_debt_config;
DROP POLICY IF EXISTS "auto_debt_config_select" ON public.auto_debt_config;
DROP POLICY IF EXISTS "auto_debt_config_staff_update" ON public.auto_debt_config;
DROP POLICY IF EXISTS "auto_debt_config_update" ON public.auto_debt_config;
DROP POLICY IF EXISTS "beds_staff_write" ON public.beds;
DROP POLICY IF EXISTS "Users can delete beds of own rooms" ON public.beds;
DROP POLICY IF EXISTS "Users can insert beds to own rooms" ON public.beds;
DROP POLICY IF EXISTS "Users can view beds of own rooms" ON public.beds;
DROP POLICY IF EXISTS "beds_select_staff" ON public.beds;
DROP POLICY IF EXISTS "Users can update beds of own rooms" ON public.beds;
DROP POLICY IF EXISTS "building_services_staff_write" ON public.building_services;
DROP POLICY IF EXISTS "Users can delete own building services" ON public.building_services;
DROP POLICY IF EXISTS "Users can insert own building services" ON public.building_services;
DROP POLICY IF EXISTS "Users can view own building services" ON public.building_services;
DROP POLICY IF EXISTS "Users can update own building services" ON public.building_services;
DROP POLICY IF EXISTS "Users can delete own buildings" ON public.buildings;
DROP POLICY IF EXISTS "buildings_staff_delete" ON public.buildings;
DROP POLICY IF EXISTS "Users can insert own buildings" ON public.buildings;
DROP POLICY IF EXISTS "buildings_staff_insert" ON public.buildings;
DROP POLICY IF EXISTS "Users can view own buildings" ON public.buildings;
DROP POLICY IF EXISTS "buildings_select_staff" ON public.buildings;
DROP POLICY IF EXISTS "Users can update own buildings" ON public.buildings;
DROP POLICY IF EXISTS "buildings_staff_update" ON public.buildings;
DROP POLICY IF EXISTS "contract_customers_staff_write" ON public.contract_customers;
DROP POLICY IF EXISTS "Users can delete own contract customers" ON public.contract_customers;
DROP POLICY IF EXISTS "Users can insert own contract customers" ON public.contract_customers;
DROP POLICY IF EXISTS "Users can view own contract customers" ON public.contract_customers;
DROP POLICY IF EXISTS "contract_customers_select_staff" ON public.contract_customers;
DROP POLICY IF EXISTS "Users can update own contract customers" ON public.contract_customers;
DROP POLICY IF EXISTS "Users can delete own extensions" ON public.contract_extensions;
DROP POLICY IF EXISTS "contract_extensions_staff_delete" ON public.contract_extensions;
DROP POLICY IF EXISTS "Users can insert own extensions" ON public.contract_extensions;
DROP POLICY IF EXISTS "contract_extensions_staff_insert" ON public.contract_extensions;
DROP POLICY IF EXISTS "Users can view own extensions" ON public.contract_extensions;
DROP POLICY IF EXISTS "contract_extensions_select_staff" ON public.contract_extensions;
DROP POLICY IF EXISTS "Users can update own extensions" ON public.contract_extensions;
DROP POLICY IF EXISTS "contract_extensions_staff_update" ON public.contract_extensions;
DROP POLICY IF EXISTS "contract_services_staff_write" ON public.contract_services;
DROP POLICY IF EXISTS "Users can delete contract services" ON public.contract_services;
DROP POLICY IF EXISTS "Users can insert contract services" ON public.contract_services;
DROP POLICY IF EXISTS "Users can view contract services" ON public.contract_services;
DROP POLICY IF EXISTS "contract_services_select_staff" ON public.contract_services;
DROP POLICY IF EXISTS "Users can update contract services" ON public.contract_services;
DROP POLICY IF EXISTS "contract_tenants_staff_write" ON public.contract_tenants;
DROP POLICY IF EXISTS "Users can delete contract tenants" ON public.contract_tenants;
DROP POLICY IF EXISTS "Users can insert contract tenants" ON public.contract_tenants;
DROP POLICY IF EXISTS "Users can view contract tenants" ON public.contract_tenants;
DROP POLICY IF EXISTS "Users can update contract tenants" ON public.contract_tenants;
DROP POLICY IF EXISTS "Users can delete own terminations" ON public.contract_terminations;
DROP POLICY IF EXISTS "contract_terminations_staff_delete" ON public.contract_terminations;
DROP POLICY IF EXISTS "Users can insert own terminations" ON public.contract_terminations;
DROP POLICY IF EXISTS "contract_terminations_staff_insert" ON public.contract_terminations;
DROP POLICY IF EXISTS "Users can view own terminations" ON public.contract_terminations;
DROP POLICY IF EXISTS "contract_terminations_select_staff" ON public.contract_terminations;
DROP POLICY IF EXISTS "Users can update own terminations" ON public.contract_terminations;
DROP POLICY IF EXISTS "contract_terminations_staff_update" ON public.contract_terminations;
DROP POLICY IF EXISTS "Users can delete own transfers" ON public.contract_transfers;
DROP POLICY IF EXISTS "contract_transfers_staff_delete" ON public.contract_transfers;
DROP POLICY IF EXISTS "Users can insert own transfers" ON public.contract_transfers;
DROP POLICY IF EXISTS "contract_transfers_staff_insert" ON public.contract_transfers;
DROP POLICY IF EXISTS "Users can view own transfers" ON public.contract_transfers;
DROP POLICY IF EXISTS "contract_transfers_select_staff" ON public.contract_transfers;
DROP POLICY IF EXISTS "Users can update own transfers" ON public.contract_transfers;
DROP POLICY IF EXISTS "contract_transfers_staff_update" ON public.contract_transfers;
DROP POLICY IF EXISTS "Users can delete own contracts" ON public.contracts;
DROP POLICY IF EXISTS "contracts_staff_delete" ON public.contracts;
DROP POLICY IF EXISTS "Users can insert own contracts" ON public.contracts;
DROP POLICY IF EXISTS "contracts_staff_insert" ON public.contracts;
DROP POLICY IF EXISTS "Users can view own contracts" ON public.contracts;
DROP POLICY IF EXISTS "contracts_select_staff" ON public.contracts;
DROP POLICY IF EXISTS "Users can update own contracts" ON public.contracts;
DROP POLICY IF EXISTS "contracts_staff_update" ON public.contracts;
DROP POLICY IF EXISTS "Users can delete own ct01" ON public.ct01_declarations;
DROP POLICY IF EXISTS "Users can insert own ct01" ON public.ct01_declarations;
DROP POLICY IF EXISTS "Users can view own ct01" ON public.ct01_declarations;
DROP POLICY IF EXISTS "ct01_declarations_select_staff" ON public.ct01_declarations;
DROP POLICY IF EXISTS "Users can update own ct01" ON public.ct01_declarations;
DROP POLICY IF EXISTS "Users can delete own customers" ON public.customers;
DROP POLICY IF EXISTS "customers_staff_delete" ON public.customers;
DROP POLICY IF EXISTS "Users can insert own customers" ON public.customers;
DROP POLICY IF EXISTS "customers_staff_insert" ON public.customers;
DROP POLICY IF EXISTS "Users can view own customers" ON public.customers;
DROP POLICY IF EXISTS "customers_select_staff" ON public.customers;
DROP POLICY IF EXISTS "Users can update own customers" ON public.customers;
DROP POLICY IF EXISTS "customers_staff_update" ON public.customers;
DROP POLICY IF EXISTS "Users can delete own deposits" ON public.deposits;
DROP POLICY IF EXISTS "deposits_staff_delete" ON public.deposits;
DROP POLICY IF EXISTS "Users can insert own deposits" ON public.deposits;
DROP POLICY IF EXISTS "deposits_staff_insert" ON public.deposits;
DROP POLICY IF EXISTS "Users can view own deposits" ON public.deposits;
DROP POLICY IF EXISTS "deposits_select_staff" ON public.deposits;
DROP POLICY IF EXISTS "Users can update own deposits" ON public.deposits;
DROP POLICY IF EXISTS "deposits_staff_update" ON public.deposits;
DROP POLICY IF EXISTS "Users can manage own templates" ON public.document_templates;
DROP POLICY IF EXISTS "document_templates_staff_delete" ON public.document_templates;
DROP POLICY IF EXISTS "document_templates_staff_insert" ON public.document_templates;
DROP POLICY IF EXISTS "document_templates_select_staff" ON public.document_templates;
DROP POLICY IF EXISTS "document_templates_staff_update" ON public.document_templates;
DROP POLICY IF EXISTS "excess_amounts_delete_own" ON public.excess_amounts;
DROP POLICY IF EXISTS "excess_amounts_staff_delete" ON public.excess_amounts;
DROP POLICY IF EXISTS "excess_amounts_insert_own" ON public.excess_amounts;
DROP POLICY IF EXISTS "excess_amounts_staff_insert" ON public.excess_amounts;
DROP POLICY IF EXISTS "excess_amounts_select_own" ON public.excess_amounts;
DROP POLICY IF EXISTS "excess_amounts_staff_update" ON public.excess_amounts;
DROP POLICY IF EXISTS "excess_amounts_update_own" ON public.excess_amounts;
DROP POLICY IF EXISTS "Users can delete own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can insert own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can view own expenses" ON public.expenses;
DROP POLICY IF EXISTS "Users can update own expenses" ON public.expenses;
DROP POLICY IF EXISTS "floors_delete" ON public.floors;
DROP POLICY IF EXISTS "floors_staff_delete" ON public.floors;
DROP POLICY IF EXISTS "floors_insert" ON public.floors;
DROP POLICY IF EXISTS "floors_staff_insert" ON public.floors;
DROP POLICY IF EXISTS "floors_select" ON public.floors;
DROP POLICY IF EXISTS "floors_staff_update" ON public.floors;
DROP POLICY IF EXISTS "floors_update" ON public.floors;
DROP POLICY IF EXISTS "hotlines_delete" ON public.hotlines;
DROP POLICY IF EXISTS "hotlines_staff_delete" ON public.hotlines;
DROP POLICY IF EXISTS "hotlines_insert" ON public.hotlines;
DROP POLICY IF EXISTS "hotlines_staff_insert" ON public.hotlines;
DROP POLICY IF EXISTS "hotlines_select" ON public.hotlines;
DROP POLICY IF EXISTS "hotlines_select_staff" ON public.hotlines;
DROP POLICY IF EXISTS "hotlines_staff_update" ON public.hotlines;
DROP POLICY IF EXISTS "hotlines_update" ON public.hotlines;
DROP POLICY IF EXISTS "ie_batch_items_all_own" ON public.income_expense_batch_items;
DROP POLICY IF EXISTS "ie_batches_delete_own" ON public.income_expense_batches;
DROP POLICY IF EXISTS "ie_batches_insert_own" ON public.income_expense_batches;
DROP POLICY IF EXISTS "ie_batches_select_own" ON public.income_expense_batches;
DROP POLICY IF EXISTS "ie_batches_update_own" ON public.income_expense_batches;
DROP POLICY IF EXISTS "income_expense_items_all" ON public.income_expense_items;
DROP POLICY IF EXISTS "income_expense_items_staff_write" ON public.income_expense_items;
DROP POLICY IF EXISTS "income_expense_items_select_staff" ON public.income_expense_items;
DROP POLICY IF EXISTS "income_expense_templates_delete" ON public.income_expense_templates;
DROP POLICY IF EXISTS "income_expense_templates_staff_delete" ON public.income_expense_templates;
DROP POLICY IF EXISTS "income_expense_templates_insert" ON public.income_expense_templates;
DROP POLICY IF EXISTS "income_expense_templates_staff_insert" ON public.income_expense_templates;
DROP POLICY IF EXISTS "income_expense_templates_select" ON public.income_expense_templates;
DROP POLICY IF EXISTS "income_expense_templates_select_staff" ON public.income_expense_templates;
DROP POLICY IF EXISTS "income_expense_templates_staff_update" ON public.income_expense_templates;
DROP POLICY IF EXISTS "income_expense_templates_update" ON public.income_expense_templates;
DROP POLICY IF EXISTS "income_expense_types_authenticated_all" ON public.income_expense_types;
DROP POLICY IF EXISTS "income_expenses_delete" ON public.income_expenses;
DROP POLICY IF EXISTS "income_expenses_staff_delete" ON public.income_expenses;
DROP POLICY IF EXISTS "income_expenses_insert" ON public.income_expenses;
DROP POLICY IF EXISTS "income_expenses_staff_insert" ON public.income_expenses;
DROP POLICY IF EXISTS "income_expenses_select" ON public.income_expenses;
DROP POLICY IF EXISTS "income_expenses_select_staff" ON public.income_expenses;
DROP POLICY IF EXISTS "income_expenses_staff_update" ON public.income_expenses;
DROP POLICY IF EXISTS "income_expenses_update" ON public.income_expenses;
DROP POLICY IF EXISTS "Users can manage their own invoice settings" ON public.invoice_generation_settings;
DROP POLICY IF EXISTS "invoice_items_staff_write" ON public.invoice_items;
DROP POLICY IF EXISTS "invoice_items_delete_own" ON public.invoice_items;
DROP POLICY IF EXISTS "invoice_items_insert_own" ON public.invoice_items;
DROP POLICY IF EXISTS "invoice_items_select_own" ON public.invoice_items;
DROP POLICY IF EXISTS "invoice_items_select_staff" ON public.invoice_items;
DROP POLICY IF EXISTS "invoice_items_update_own" ON public.invoice_items;
DROP POLICY IF EXISTS "invoices_delete_own" ON public.invoices;
DROP POLICY IF EXISTS "invoices_staff_delete" ON public.invoices;
DROP POLICY IF EXISTS "invoices_insert_own" ON public.invoices;
DROP POLICY IF EXISTS "invoices_staff_insert" ON public.invoices;
DROP POLICY IF EXISTS "invoices_select_own" ON public.invoices;
DROP POLICY IF EXISTS "invoices_select_staff" ON public.invoices;
DROP POLICY IF EXISTS "invoices_staff_update" ON public.invoices;
DROP POLICY IF EXISTS "invoices_update_own" ON public.invoices;
DROP POLICY IF EXISTS "Users can manage own issue categories" ON public.issue_categories;
DROP POLICY IF EXISTS "issue_comments_staff_delete" ON public.issue_comments;
DROP POLICY IF EXISTS "Users can create comments on own issues" ON public.issue_comments;
DROP POLICY IF EXISTS "issue_comments_staff_insert" ON public.issue_comments;
DROP POLICY IF EXISTS "Users can view comments on own issues" ON public.issue_comments;
DROP POLICY IF EXISTS "issue_comments_staff_update" ON public.issue_comments;
DROP POLICY IF EXISTS "Users can create phase history for own issues" ON public.issue_phase_history;
DROP POLICY IF EXISTS "Users can view phase history of own issues" ON public.issue_phase_history;
DROP POLICY IF EXISTS "Users can insert issue status history" ON public.issue_status_history;
DROP POLICY IF EXISTS "Users can view their own issue status history" ON public.issue_status_history;
DROP POLICY IF EXISTS "Users can manage own issues" ON public.issues;
DROP POLICY IF EXISTS "issues_staff_delete" ON public.issues;
DROP POLICY IF EXISTS "issues_staff_insert" ON public.issues;
DROP POLICY IF EXISTS "Users can view own issues" ON public.issues;
DROP POLICY IF EXISTS "issues_select_staff" ON public.issues;
DROP POLICY IF EXISTS "issues_staff_update" ON public.issues;
DROP POLICY IF EXISTS "Users can manage own job groups" ON public.job_groups;
DROP POLICY IF EXISTS "job_groups_staff_delete" ON public.job_groups;
DROP POLICY IF EXISTS "job_groups_staff_insert" ON public.job_groups;
DROP POLICY IF EXISTS "job_groups_staff_update" ON public.job_groups;
DROP POLICY IF EXISTS "Authenticated users can manage job types" ON public.job_types;
DROP POLICY IF EXISTS "job_types_staff_delete" ON public.job_types;
DROP POLICY IF EXISTS "job_types_staff_insert" ON public.job_types;
DROP POLICY IF EXISTS "job_types_staff_update" ON public.job_types;
DROP POLICY IF EXISTS "Users can delete own jobs" ON public.jobs;
DROP POLICY IF EXISTS "jobs_staff_delete" ON public.jobs;
DROP POLICY IF EXISTS "Users can create own jobs" ON public.jobs;
DROP POLICY IF EXISTS "jobs_staff_insert" ON public.jobs;
DROP POLICY IF EXISTS "jobs_select_owner_or_assignee" ON public.jobs;
DROP POLICY IF EXISTS "Users can update own jobs" ON public.jobs;
DROP POLICY IF EXISTS "jobs_staff_update" ON public.jobs;
DROP POLICY IF EXISTS "Users can delete their own lead activities" ON public.lead_activities;
DROP POLICY IF EXISTS "lead_activities_staff_delete" ON public.lead_activities;
DROP POLICY IF EXISTS "Users can insert their own lead activities" ON public.lead_activities;
DROP POLICY IF EXISTS "lead_activities_staff_insert" ON public.lead_activities;
DROP POLICY IF EXISTS "Users can view their own lead activities" ON public.lead_activities;
DROP POLICY IF EXISTS "lead_activities_select_staff" ON public.lead_activities;
DROP POLICY IF EXISTS "Users can update their own lead activities" ON public.lead_activities;
DROP POLICY IF EXISTS "lead_activities_staff_update" ON public.lead_activities;
DROP POLICY IF EXISTS "Users can manage own leads" ON public.leads;
DROP POLICY IF EXISTS "leads_staff_delete" ON public.leads;
DROP POLICY IF EXISTS "leads_staff_insert" ON public.leads;
DROP POLICY IF EXISTS "leads_select_staff" ON public.leads;
DROP POLICY IF EXISTS "leads_staff_update" ON public.leads;
DROP POLICY IF EXISTS "Users can delete own meter readings" ON public.meter_readings;
DROP POLICY IF EXISTS "meter_readings_staff_delete" ON public.meter_readings;
DROP POLICY IF EXISTS "Users can insert own meter readings" ON public.meter_readings;
DROP POLICY IF EXISTS "meter_readings_staff_insert" ON public.meter_readings;
DROP POLICY IF EXISTS "Users can view own meter readings" ON public.meter_readings;
DROP POLICY IF EXISTS "meter_readings_select_staff" ON public.meter_readings;
DROP POLICY IF EXISTS "Users can update own meter readings" ON public.meter_readings;
DROP POLICY IF EXISTS "meter_readings_staff_update" ON public.meter_readings;
DROP POLICY IF EXISTS "Users can delete own meters" ON public.meters;
DROP POLICY IF EXISTS "meters_staff_delete" ON public.meters;
DROP POLICY IF EXISTS "Users can insert own meters" ON public.meters;
DROP POLICY IF EXISTS "meters_staff_insert" ON public.meters;
DROP POLICY IF EXISTS "Users can view own active meters" ON public.meters;
DROP POLICY IF EXISTS "meters_select_staff" ON public.meters;
DROP POLICY IF EXISTS "Users can update own meters" ON public.meters;
DROP POLICY IF EXISTS "meters_staff_update" ON public.meters;
DROP POLICY IF EXISTS "Users can manage own notification templates" ON public.notification_templates;
DROP POLICY IF EXISTS "payments_delete_own" ON public.payments;
DROP POLICY IF EXISTS "payments_staff_delete" ON public.payments;
DROP POLICY IF EXISTS "payments_insert_own" ON public.payments;
DROP POLICY IF EXISTS "payments_staff_insert" ON public.payments;
DROP POLICY IF EXISTS "payments_select_own" ON public.payments;
DROP POLICY IF EXISTS "payments_select_staff" ON public.payments;
DROP POLICY IF EXISTS "payments_staff_update" ON public.payments;
DROP POLICY IF EXISTS "payments_update_own" ON public.payments;
DROP POLICY IF EXISTS "Users can manage transitions of own flows" ON public.phase_transitions;
DROP POLICY IF EXISTS "Users can view transitions of own flows" ON public.phase_transitions;
DROP POLICY IF EXISTS "rooms_staff_write" ON public.rooms;
DROP POLICY IF EXISTS "Users can delete rooms of own buildings" ON public.rooms;
DROP POLICY IF EXISTS "Users can insert rooms to own buildings" ON public.rooms;
DROP POLICY IF EXISTS "Users can view rooms of own buildings" ON public.rooms;
DROP POLICY IF EXISTS "rooms_select_staff" ON public.rooms;
DROP POLICY IF EXISTS "Users can update rooms of own buildings" ON public.rooms;
DROP POLICY IF EXISTS "Users can manage their own scheduled jobs" ON public.scheduled_jobs;
DROP POLICY IF EXISTS "quota_tiers_delete" ON public.service_quota_tiers;
DROP POLICY IF EXISTS "quota_tiers_insert" ON public.service_quota_tiers;
DROP POLICY IF EXISTS "quota_tiers_select" ON public.service_quota_tiers;
DROP POLICY IF EXISTS "quota_tiers_update" ON public.service_quota_tiers;
DROP POLICY IF EXISTS "service_quotas_delete" ON public.service_quotas;
DROP POLICY IF EXISTS "service_quotas_staff_delete" ON public.service_quotas;
DROP POLICY IF EXISTS "service_quotas_insert" ON public.service_quotas;
DROP POLICY IF EXISTS "service_quotas_staff_insert" ON public.service_quotas;
DROP POLICY IF EXISTS "service_quotas_select" ON public.service_quotas;
DROP POLICY IF EXISTS "service_quotas_staff_update" ON public.service_quotas;
DROP POLICY IF EXISTS "service_quotas_update" ON public.service_quotas;
DROP POLICY IF EXISTS "Users can delete own services" ON public.services;
DROP POLICY IF EXISTS "services_staff_delete" ON public.services;
DROP POLICY IF EXISTS "Users can insert own services" ON public.services;
DROP POLICY IF EXISTS "services_staff_insert" ON public.services;
DROP POLICY IF EXISTS "Users can view own services" ON public.services;
DROP POLICY IF EXISTS "services_select_staff" ON public.services;
DROP POLICY IF EXISTS "Users can update own services" ON public.services;
DROP POLICY IF EXISTS "services_staff_update" ON public.services;
DROP POLICY IF EXISTS "Users can manage own signature templates" ON public.signature_templates;
DROP POLICY IF EXISTS "Users can manage their own SLA configs" ON public.sla_configs;
DROP POLICY IF EXISTS "Users can manage own suppliers" ON public.suppliers;
DROP POLICY IF EXISTS "suppliers_staff_delete" ON public.suppliers;
DROP POLICY IF EXISTS "suppliers_staff_insert" ON public.suppliers;
DROP POLICY IF EXISTS "Users can view own suppliers" ON public.suppliers;
DROP POLICY IF EXISTS "suppliers_select_staff" ON public.suppliers;
DROP POLICY IF EXISTS "suppliers_staff_update" ON public.suppliers;
DROP POLICY IF EXISTS "Users can manage own task flows" ON public.task_flows;
DROP POLICY IF EXISTS "task_flows_staff_delete" ON public.task_flows;
DROP POLICY IF EXISTS "task_flows_staff_insert" ON public.task_flows;
DROP POLICY IF EXISTS "task_flows_staff_update" ON public.task_flows;
DROP POLICY IF EXISTS "Users can manage phases of own flows" ON public.task_phases;
DROP POLICY IF EXISTS "Users can view phases of own flows" ON public.task_phases;
DROP POLICY IF EXISTS "task_types_delete" ON public.task_types;
DROP POLICY IF EXISTS "task_types_staff_delete" ON public.task_types;
DROP POLICY IF EXISTS "task_types_insert" ON public.task_types;
DROP POLICY IF EXISTS "task_types_staff_insert" ON public.task_types;
DROP POLICY IF EXISTS "task_types_select" ON public.task_types;
DROP POLICY IF EXISTS "task_types_select_staff" ON public.task_types;
DROP POLICY IF EXISTS "task_types_staff_update" ON public.task_types;
DROP POLICY IF EXISTS "task_types_update" ON public.task_types;
DROP POLICY IF EXISTS "Users can delete own tenants" ON public.tenants;
DROP POLICY IF EXISTS "tenants_staff_delete" ON public.tenants;
DROP POLICY IF EXISTS "Users can insert own tenants" ON public.tenants;
DROP POLICY IF EXISTS "tenants_staff_insert" ON public.tenants;
DROP POLICY IF EXISTS "Users can view own tenants" ON public.tenants;
DROP POLICY IF EXISTS "tenants_select_staff" ON public.tenants;
DROP POLICY IF EXISTS "Users can update own tenants" ON public.tenants;
DROP POLICY IF EXISTS "tenants_staff_update" ON public.tenants;
DROP POLICY IF EXISTS "Users can delete own vehicles" ON public.vehicles;
DROP POLICY IF EXISTS "vehicles_staff_delete" ON public.vehicles;
DROP POLICY IF EXISTS "Users can insert own vehicles" ON public.vehicles;
DROP POLICY IF EXISTS "vehicles_staff_insert" ON public.vehicles;
DROP POLICY IF EXISTS "Users can view own vehicles" ON public.vehicles;
DROP POLICY IF EXISTS "vehicles_select_staff" ON public.vehicles;
DROP POLICY IF EXISTS "Users can update own vehicles" ON public.vehicles;
DROP POLICY IF EXISTS "vehicles_staff_update" ON public.vehicles;
