// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { processLock } from '@supabase/auth-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // localStorage không tồn tại trong môi trường node (vitest import chain)
    storage: typeof localStorage !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    // Upstream auth-js also moved to processLock: Android Chrome can orphan
    // navigator.locks, while GoTrue handles concurrent cross-tab refreshes.
    lock: processLock,
  }
});
