// @vitest-environment jsdom
import {beforeEach,it,expect,vi} from 'vitest';
import {runContractEdit,loadContractEditJob,type ContractEditRequest,type ContractEditSnapshot,type ContractEditPorts} from '../contractEditWorkflow';
vi.mock('@/lib/authSession',()=>({getSessionUser:async()=>({id:'u1'})}));
const request:ContractEditRequest={contractId:'c1',updates:{rent_price:200},fieldsFingerprint:'new-form',customers:[{customer_id:'customer1',is_representative:true,notes:null}],services:[{service_id:'s1',unit_price:50,initial_reading:null}]};
let actual:ContractEditSnapshot;let ports:ContractEditPorts;
beforeEach(()=>{localStorage.clear();actual={contract:{id:'c1',organization_id:'o1',rent_price:100},customers:[{customer_id:'old',is_representative:true,notes:null}],services:[]};ports={read:vi.fn(async()=>structuredClone(actual)),update:vi.fn(async input=>{Object.assign(actual.contract,input.updates);return actual.contract;}),customers:vi.fn(async(input)=>{input.onPhase?.('deleting');actual.customers=[];input.onPhase?.('deleted');input.onPhase?.('inserting');actual.customers=input.customers;input.onPhase?.('done');}),services:vi.fn(async(input)=>{input.onPhase?.('deleting');actual.services=[];input.onPhase?.('deleted');input.onPhase?.('inserting');actual.services=input.services;input.onPhase?.('done');})};});
it('lưu marker trước writer, exact core và relations xong mới xóa snapshot',async()=>{const update=ports.update;ports.update=vi.fn(async input=>{expect(await loadContractEditJob('c1')).toMatchObject({contractId:'c1',corePhase:'sending'});return update(input);});await expect(runContractEdit(request,ports)).resolves.toMatchObject({contractId:'c1'});expect(await loadContractEditJob('c1')).toBeNull();expect(ports.customers).toHaveBeenCalledWith(expect.objectContaining({organizationId:'o1'}));});
it('core receipt null không bắt đầu quan hệ; reload core mismatch không replay update',async()=>{ports.update=vi.fn(async()=>null);await expect(runContractEdit(request,ports)).rejects.toThrow(/đối chiếu/);expect(ports.customers).not.toHaveBeenCalled();expect(await loadContractEditJob('c1')).toMatchObject({corePhase:'sending'});await expect(runContractEdit({...request,updates:{rent_price:999}},ports)).rejects.toThrow(/đối chiếu/);expect(ports.update).toHaveBeenCalledOnce();});
it('unknown core đã thực sự lưu được xác nhận bằng readback trước khi tiếp tục các phần còn thiếu',async()=>{ports.update=vi.fn(async input=>{Object.assign(actual.contract,input.updates);throw new TypeError('Failed to fetch');});await expect(runContractEdit(request,ports)).rejects.toThrow();expect(await loadContractEditJob('c1')).toMatchObject({corePhase:'sending'});await expect(runContractEdit(request,ports)).resolves.toMatchObject({contractId:'c1'});expect(ports.update).toHaveBeenCalledOnce();expect(ports.customers).toHaveBeenCalledOnce();});
it('known insert rejection sau delete giữ phase/ID, reload đọc empty mới insert không delete lại',async()=>{ports.customers=vi.fn(async input=>{input.onPhase?.('deleting');actual.customers=[];input.onPhase?.('deleted');input.onPhase?.('inserting');throw {code:'23514',message:'bad row'};});await expect(runContractEdit(request,ports)).rejects.toThrow();expect(await loadContractEditJob('c1')).toMatchObject({customersPhase:'deleted',corePhase:'done'});ports.customers=vi.fn(async input=>{expect(input.skipDelete).toBe(true);actual.customers=input.customers;input.onPhase?.('done');});await expect(runContractEdit(request,ports)).resolves.toMatchObject({contractId:'c1'});expect(ports.update).toHaveBeenCalledOnce();});
it('unknown insert + authoritative empty không được đoán rollback để insert lại',async()=>{ports.customers=vi.fn(async input=>{input.onPhase?.('deleting');actual.customers=[];input.onPhase?.('deleted');input.onPhase?.('inserting');throw new TypeError('Failed to fetch');});await expect(runContractEdit(request,ports)).rejects.toThrow();await expect(runContractEdit(request,ports)).rejects.toThrow(/đối chiếu/);expect(ports.customers).toHaveBeenCalledOnce();expect(ports.services).not.toHaveBeenCalled();});
it('unknown delete + authoritative empty không được gửi lại delete hoặc insert',async()=>{ports.customers=vi.fn(async input=>{input.onPhase?.('deleting');actual.customers=[];throw new TypeError('Failed to fetch');});await expect(runContractEdit(request,ports)).rejects.toThrow();await expect(runContractEdit(request,ports)).rejects.toThrow();expect(ports.customers).toHaveBeenCalledOnce();});
it('unknown insert thực sự xong: desired relations được read-confirm rồi chỉ tiếp tục services',async()=>{ports.customers=vi.fn(async input=>{input.onPhase?.('deleting');actual.customers=[];input.onPhase?.('deleted');input.onPhase?.('inserting');actual.customers=input.customers;throw new TypeError('Failed to fetch');});await expect(runContractEdit(request,ports)).rejects.toThrow();await expect(runContractEdit(request,ports)).resolves.toMatchObject({contractId:'c1'});expect(ports.customers).toHaveBeenCalledOnce();expect(ports.services).toHaveBeenCalledOnce();});
it('read failure giữ snapshot/ID, không writer mới sau reload',async()=>{ports.update=vi.fn(async()=>null);await expect(runContractEdit(request,ports)).rejects.toThrow();ports.read=vi.fn().mockRejectedValue({code:'42501'});await expect(runContractEdit(request,ports)).rejects.toThrow(/c1/);expect(ports.update).toHaveBeenCalledOnce();expect(ports.customers).not.toHaveBeenCalled();});
it('storage không ghi được chặn trước writer',async()=>{vi.spyOn(Storage.prototype,'setItem').mockImplementationOnce(()=>{throw new Error('quota');});await expect(runContractEdit(request,ports)).rejects.toThrow();expect(ports.update).not.toHaveBeenCalled();});
it('double click chặn update thứ hai trong khi writer đầu đang pending',async()=>{let finish:()=>void=()=>{};ports.update=vi.fn(async input=>{await new Promise<void>(resolve=>{finish=resolve;});Object.assign(actual.contract,input.updates);return actual.contract;});const first=runContractEdit(request,ports);await vi.waitFor(()=>expect(ports.update).toHaveBeenCalledOnce());await expect(runContractEdit(request,ports)).rejects.toThrow(/đang/);finish();await first;expect(ports.update).toHaveBeenCalledOnce();});
it('known deleted phase nhưng relation có row khác không ghi đè thay đổi concurrent',async()=>{ports.customers=vi.fn(async input=>{input.onPhase?.('deleting');actual.customers=[];input.onPhase?.('deleted');input.onPhase?.('inserting');throw {code:'23514'};});await expect(runContractEdit(request,ports)).rejects.toThrow();actual.customers=[{customer_id:'concurrent',is_representative:true}];await expect(runContractEdit(request,ports)).rejects.toThrow();expect(ports.customers).toHaveBeenCalledOnce();});

it('known core rejection zero-write giải phóng intent cũ để sửa trường rồi gửi lại',async()=>{ports.update=vi.fn().mockRejectedValueOnce({code:'23514',message:'invalid amount'}).mockImplementation(async input=>{Object.assign(actual.contract,input.updates);return actual.contract;});await expect(runContractEdit(request,ports)).rejects.toBeDefined();expect(await loadContractEditJob('c1')).toBeNull();await expect(runContractEdit({...request,updates:{rent_price:300}},ports)).resolves.toMatchObject({contractId:'c1'});expect(actual.contract.rent_price).toBe(300);});
it('known read denial sau relation đã xong không đổi phase thành rejected để delete lại',async()=>{let fail=false;const read=ports.read;ports.read=vi.fn(async id=>{if(fail)throw {code:'42501'};return read(id);});ports.customers=vi.fn(async input=>{actual.customers=input.customers;input.onPhase?.('done');fail=true;});await expect(runContractEdit(request,ports)).rejects.toThrow();expect(await loadContractEditJob('c1')).toMatchObject({customersPhase:'done'});fail=false;await expect(runContractEdit(request,ports)).resolves.toMatchObject({contractId:'c1'});expect(ports.customers).toHaveBeenCalledOnce();});

it('unknown delete target empty không được clear marker bằng absence',async()=>{ports.services=vi.fn(async input=>{input.onPhase?.('deleting');actual.services=[];throw new TypeError('Failed to fetch');});actual.services=[{service_id:'old',unit_price:10}];const intent={...request,services:[]};await expect(runContractEdit(intent,ports)).rejects.toThrow();await expect(runContractEdit(intent,ports)).rejects.toThrow(/đối chiếu/);expect(await loadContractEditJob('c1')).not.toBeNull();expect(ports.services).toHaveBeenCalledOnce();});
