// @vitest-environment jsdom
import {beforeEach,expect,it,vi} from 'vitest';
const io=vi.hoisted(()=>({from:vi.fn()}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{from:io.from}}));
vi.mock('@/lib/authSession',()=>({getSessionUser:async()=>({id:'actor'})}));
import {importCustomerBatch,saveImportedCustomerImages} from '../customerImportOutcome';
import {FinancialWorkflowError} from '../financialWorkflow';
function chain(data:unknown){const q:Record<string,unknown>={then:(r:(v:unknown)=>void)=>r({data,error:null})};for(const m of ['update','eq','select','single'])q[m]=vi.fn(()=>q);return q;}
beforeEach(()=>{vi.resetAllMocks();localStorage.clear();localStorage.setItem('ihomecrm.selectedOrganizationId','o1');});
it('image update needs an exact receipt, rather than zero affected rows',async()=>{io.from.mockReturnValue(chain(null));await expect(saveImportedCustomerImages('c1',{front:'stored'})).rejects.toBeInstanceOf(FinancialWorkflowError);});
it('partial image result keeps created customer ID and prevents another batch after reload',async()=>{io.from.mockReturnValue(chain(null));const steps={create:vi.fn().mockResolvedValue('c1'),uploadImages:vi.fn().mockResolvedValue({front:'stored'})};const report=vi.fn();const rows=[{full_name:'Khách',phone:'0900',id_image_urls:['external']}];await expect(importCustomerBatch(rows,steps,report)).rejects.toBeInstanceOf(FinancialWorkflowError);expect(report.mock.lastCall?.[0].partialRows[0].id).toBe('c1');await expect(importCustomerBatch(rows,steps,report)).rejects.toBeInstanceOf(FinancialWorkflowError);expect(steps.create).toHaveBeenCalledTimes(1);});
it('later unknown keeps earlier customer IDs and cannot recreate successful rows',async()=>{const steps={create:vi.fn().mockResolvedValueOnce('c1').mockRejectedValueOnce(new FinancialWorkflowError('Chưa xác nhận khách mới.','unknown',[{id:'c2',label:'Khách cần đối chiếu'}])),uploadImages:vi.fn()};const report=vi.fn();const rows=[{full_name:'A',phone:'0900'},{full_name:'B',phone:'0901'}];let error:unknown;try{await importCustomerBatch(rows,steps,report);}catch(e){error=e;}expect(error).toBeInstanceOf(FinancialWorkflowError);if (!(error instanceof FinancialWorkflowError)) throw error;expect(error.completed.map((v:{id:string})=>v.id)).toEqual(expect.arrayContaining(['c1','c2']));expect(report.mock.lastCall?.[0].unknownRows[0].reason).toContain('c2');await expect(importCustomerBatch(rows,steps,report)).rejects.toBeInstanceOf(FinancialWorkflowError);expect(steps.create).toHaveBeenCalledTimes(2);});

it('all rows rejected keeps the import failed but permits a safe retry',async()=>{const steps={create:vi.fn().mockRejectedValue({code:'23505',message:'SQL secret'}),uploadImages:vi.fn()};const rows=[{full_name:'A',phone:'0900'}];const report=vi.fn();await expect(importCustomerBatch(rows,steps,report)).rejects.toMatchObject({outcome:'failure'});await expect(importCustomerBatch(rows,steps,report)).rejects.toMatchObject({outcome:'failure'});expect(steps.create).toHaveBeenCalledTimes(2);expect(report.mock.lastCall?.[0].failRows).toHaveLength(1);});
