// @vitest-environment jsdom
import {beforeEach,expect,it,vi} from 'vitest';
import {runDurableCollection,PendingCollectionError} from '../pendingCollection';
const scope={userId:'u1',organizationId:'o1',invoiceId:'i1'};
beforeEach(()=>localStorage.clear());
it('receipt trả nhầm hoá đơn giữ khóa và không cho thu lại',async()=>{const send=vi.fn().mockResolvedValue({collection_id:'c1',invoice_id:'wrong',applied_amount:1000});await expect(runDurableCollection(scope,'k1',send,async()=>null)).rejects.toBeInstanceOf(PendingCollectionError);expect(localStorage.length).toBe(1);await expect(runDurableCollection(scope,'k2',send,async()=>null)).rejects.toBeInstanceOf(PendingCollectionError);expect(send).toHaveBeenCalledTimes(1);});
it('timeout giữ tối thiểu identity qua lần gọi mới, lookup trống không mở khóa hay gửi lại',async()=>{const send=vi.fn().mockRejectedValue(new TypeError('Failed to fetch'));await expect(runDurableCollection(scope,'key-old',send,async()=>null)).rejects.toThrow();const persisted=JSON.stringify(localStorage);expect(persisted).toContain('key-old');const next=vi.fn();await expect(runDurableCollection(scope,'key-new',next,async()=>null)).rejects.toBeInstanceOf(PendingCollectionError);expect(next).not.toHaveBeenCalled();expect(persisted).not.toContain('amount');});
it('lookup đúng key khôi phục receipt thật thay vì gửi khoản thu mới',async()=>{await expect(runDurableCollection(scope,'key-old',async()=>{throw new TypeError('timeout');},async()=>null)).rejects.toThrow();const send=vi.fn();const lookup=vi.fn().mockResolvedValue({id:'collection1',invoice_id:'i1',organization_id:'o1',actor_id:'u1',idempotency_key:'key-old',status:'ACTIVE',applied_amount:1000});const result=await runDurableCollection(scope,'key-new',send,lookup);expect(result).toMatchObject({collection_id:'collection1',invoice_id:'i1',recovered:true});expect(send).not.toHaveBeenCalled();expect(lookup).toHaveBeenCalledWith(expect.objectContaining({idempotencyKey:'key-old'}));expect(localStorage.length).toBe(0);});
it('lookup sai invoice/key không mở khóa',async()=>{await expect(runDurableCollection(scope,'key-old',async()=>{throw new TypeError('timeout');},async()=>null)).rejects.toThrow();const send=vi.fn();await expect(runDurableCollection(scope,'key-new',send,async()=>({id:'wrong',invoice_id:'i2'}))).rejects.toBeInstanceOf(PendingCollectionError);expect(send).not.toHaveBeenCalled();expect(localStorage.length).toBe(1);});
it('lỗi nghiệp vụ đã từ chối không giữ khóa, lỗi storage chặn trước RPC',async()=>{const error={code:'22023',message:'bad input'};await expect(runDurableCollection(scope,'key-old',async()=>{throw error;},async()=>null)).rejects.toBe(error);expect(localStorage.length).toBe(0);const spy=vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new Error('quota');});const send=vi.fn();await expect(runDurableCollection(scope,'key-new',send,async()=>null)).rejects.toThrow(/trình duyệt/);expect(send).not.toHaveBeenCalled();spy.mockRestore();});
